### ISSUE TITLE
Translation Error

### ISSUE THREAD

**Issue by phase** [GeyserMC/MCProtocolLib#112]
`vn29 has just earned the achievement [Taking Inventory]`
Calling `getFullText()` on the Message sent from a ServerChatPacket gives this:
`chat.type.achievement`

**Comment by Steveice10** [comment]
MCProtocolLib does not provide translation support. You have to translate it using getTranslationKey, getTranslationParams, and a message format in your language of choice.

**Comment by phase** [comment]
I'm on an vanilla 1.8.9 English server that doesn't need translations.

Calling _Message#getFullText()_ on 

```
{"color":"white","translate":"chat.type.text","with":[{"color":"white","clickEvent":{"action":"suggest_command","value":"/msg Owk "},"hoverEvent":{"action":"show_entity","value":{"color":"white","text":"{id:\"4903aae5-5de1-4266-b78c-f5fbcb8992b7\",name:\"Owk\"}"}},"insertion":"Owk","text":"Owk"},{"color":"white","text":"Hello"}]}
```

returns `chat.type.text`

**Comment by Steveice10** [comment]
Intended behavior. TranslationMessages must be parsedbythe receiver.
