### ISSUE TITLE
ServerPlayerListEntry packet bug 1.8

### ISSUE THREAD

**Issue by MatteCarra** [GeyserMC/MCProtocolLib#116]
When I connect to one minecraft server I receive strange ServerPlayerListEntryPacket profiles.
They have names like this "§Ў ?tab" , but normal uuid.
On new players ServerPlayerListEntryPacket the problem doesn't exist
It is a non-premium server

**Comment by MatteCarra** [comment]
UUID aren't really normal: 40bd24d5-db28-35f6-ab1a-5ce53deb6512
No players with this uuid joined on my test server

**Comment by MatteCarra** [comment]
There is the same problem also in other minecraft servers.
![senza nome](https://cloud.githubusercontent.com/assets/11074527/11595668/df1053b2-9ab0-11e5-9c91-90a74ba26308.png)

**Comment by MatteCarra** [comment]
In those packets displayed name is null.
Server is using bungee cord

**Comment by ensirius** [comment]
I am sorry, but how this affect this project?

**Comment by ghost** [comment]
Can you provide your code snipet at least?

**Comment by MatteCarra** [comment]
I'm using example version with ServerPlayerListEntryPacket check.
I will post snippet but I'm out until tomorrow evening

**Comment by MatteCarra** [comment]
Code: http://pastebin.com/rWfxcTnU
Output: http://pastebin.com/HnvyVjU8
It seems to affect only few servers

**Comment by Steveice10** [comment]
Could you provide output with all of the packet details (number of entries contained, all the entry data, etc.)? Would help to confirm if its a read issue.

**Comment by MatteCarra** [comment]
Yes I will this afternoon.
In any case I can confirm it is a read problem:
I made a few test in the read method of ServerPlayerListEntryPacket.
 I created a temp var with readString(to read the name; I placed it in the right place) then I passed it to GameProfile instead of doing inline operation and then I printed it on the log.
The name is strange also on read.
(This was only a test. There is the same problem without this test)
P.s: this problem exists only with few server.
I can give you the IPs to test the bug

**Comment by MatteCarra** [comment]
Full output: http://pastebin.com/tZWbZpiT

**Comment by Steveice10** [comment]
What servers does this happen on? Sounds more like the server sending weird stuff.

**Comment by MatteCarra** [comment]
I'm testing it in mc.usavsurss.com
I tested it with some playstore chat app and there isn't this bug.
ChatCraft for Minecraft has different minecraft protocol library for example.

**Comment by Steveice10** [comment]
Yeah... I'm pretty sure it's something with that server. Its server list ping player list sends players with names like "§0█§0█§0█§0█§0█§0█§0█§0█§0█§0█§0█§0█§0█§0█§0█§0█§0█§0█§0█".

**Comment by MatteCarra** [comment]
Why does minecraft shows the tab without this strange players?

**Comment by Steveice10** [comment]
I would guess because they don't have a display name set.

**Comment by MatteCarra** [comment]
Your guess is to ignore all playerlistitem with displayname null?

**Comment by Steveice10** [comment]
That would seem to work, yes.
