### ISSUE TITLE
Question/ Auth Bug

### ISSUE THREAD

**Issue by MatteCarra** [GeyserMC/MCProtocolLib#117]
I make a request with this code: http://pastebin.com/TKhwbrza
Then when I connect I get accessToken, and email for a file where i saved them.
They are IDENTICAL to the received ones.
Then I create a minecraft protocol and the problem begins! (new MinecraftProtocol(email, authToken, true) ).
I sometimes receive this exception http://pastebin.com/WfNyy5qP or a similar one but in ClientListener.java (line 55)
What's wrong?

**Comment by Steveice10** [comment]
Are you reusing the access token from the file when it fails? That MinecraftProtocol constructor renews the access token, and the renewed token can be retrieved with MinecraftProtocol.getAccessToken().

**Comment by MatteCarra** [comment]
It worked with AuthenticationService and then (profile, accessToken) constructor
Thank you very much for your work!
Keep on doing it!
