### ISSUE TITLE
Get all online players

### ISSUE THREAD

**Issue by minecraftkeba** [GeyserMC/MCProtocolLib#119]
Hello, I can´t find a way to get a list of all online players.
Is it possible? If yes, how?

**Comment by ghost** [comment]
Hello! Check this example http://git.io/vEv5R

**Comment by minecraftkeba** [comment]
I traid that, but it dosn´t work with Bungeecord? Is there a way to get the entrys of the Tablist?

**Comment by ghost** [comment]
To get tablist you must be logged in game. Bungee not changing anything in packets. It would break multiplayer menu as well. Show please your code snippet.

**Comment by minecraftkeba** [comment]
Ok, how does it work when I am logged in? Is that possible with this api?

**Comment by minecraftkeba** [comment]
I got a seesion if you mean that

**Comment by ghost** [comment]
Yes, it's possible, but you will join server as real player. You should avoid that.

**Comment by minecraftkeba** [comment]
As real Player? You mean without this api?

**Comment by ghost** [comment]
Huh...no. You will emulate ingame player..just dissmiss this idea. Share your code.

**Comment by minecraftkeba** [comment]
```
    Main.main_see = connect(Main.IP, Main.Port, Main.main_name, Main.main_pass);
    if(Main.main_see != null) {
        Main.main_see.addListener(CommandListener.get());
        Main.main_see.addListener(JoinListener.get());
        Main.main_see.addListener(LoginListener.get());
        Main.main_see.connect();
        //Here I Need to get a list of all Players online on the current Server.
    }
```

**Comment by ghost** [comment]
As i see, you already emulating ingame player. So use `ServerPlayListEntryPacket`. This packet sends every time player join/quit game.

``` java
Main.main_see.addListener(new SessionAdapter() {
            @Override
            public void packetReceived(PacketReceivedEvent event) {
                if(event.getPacket() instanceof ServerPlayerListEntryPacket) {
                    ServerPlayerListEntryPacket packet = (ServerPlayerListEntryPacket) event.getPacket();
                    ...
                 }
            }
});
```

**Comment by minecraftkeba** [comment]
Ok great that works...

```
            if(event.getPacket() instanceof ServerPlayerListEntryPacket) {
                ServerPlayerListEntryPacket packet = (ServerPlayerListEntryPacket) event.getPacket();
                for(PlayerListEntry x : packet.getEntries()) {
                    System.out.println("P: " + x.getProfile().getName());
                }
            }
```

Can I force the Server to send this package?

**Comment by ghost** [comment]
This packet sends every time ANY PLAYER join/quit game.

**Comment by minecraftkeba** [comment]
But I can´t force it?

**Comment by ghost** [comment]
No. Why you should? On login you get current players and than just update.

**Comment by minecraftkeba** [comment]
Thanks everything works.
