### ISSUE TITLE
Connection closed

### ISSUE THREAD

**Issue by fillefilip8** [GeyserMC/MCProtocolLib#120]
When i connect to a server using this lib on android.
I get disconnected direcly
with the reason "Connection closed."

Any help please?

**Comment by minecraftkeba** [comment]
Send your code please.

There are many reasons for this error.

**Comment by fillefilip8** [comment]
http://pastebin.com/hbjes7Z4

**Comment by minecraftkeba** [comment]
Are you sure that all variables are set correctly?

**Comment by fillefilip8** [comment]
The login info is correct tho. What reasons can cause it do that disconnect?

**Comment by minecraftkeba** [comment]
Disable the SessionAdapter, just remove it.

**Comment by minecraftkeba** [comment]
Did it work? Can you close?

**Comment by minecraftkeba** [comment]
I think you can close that Issue!

//close

**Comment by fillefilip8** [comment]
I tried removing the session adapter that didnt change anything?
Any ideas?

**Comment by minecraftkeba** [comment]
Do you get any error messages?

**Comment by fillefilip8** [comment]
No just Connection closed. On the disconnected event

**Comment by minecraftkeba** [comment]
I think I got it!

You do not set a passwort at all.. Or is it a cracked server?
Maybe the problem is allreay there before you connect.

Otherwise remove every part of the code which could give you an error.

**Comment by fillefilip8** [comment]
The login works. I dont think its that

**Comment by fillefilip8** [comment]
(logging in with premium account)

**Comment by minecraftkeba** [comment]
And where do you set the passwort?

**Comment by minecraftkeba** [comment]
public static Session connect(String ip, int port, String name, String pw) throws InterruptedException {
        Client c;
        MinecraftProtocol p;
        try {
            p = new MinecraftProtocol(name, pw);
            c = new Client(ip, port, p, new TcpSessionFactory());
            c.getSession().connect();
            return c.getSession();
        } catch (RequestException e) {
            e.printStackTrace();
            return null;
        }
    }

This works for me... Try this.
