### ISSUE TITLE
ClientPlayerPlaceBlockPacket

### ISSUE THREAD

**Issue by minecraftkeba** [GeyserMC/MCProtocolLib#124]
How do I get the Block in front of a Player and the Cursor?

**Comment by Steveice10** [comment]
You'll need to handle chunk packets (unless you're using MCProtocolLib as a server, in which case you already have it) and store the chunk data somewhere. Then, you can figure out the block in front of the player from the block next to their position within the chunk they're in. You can also figure out the block at their cursor using ray tracing or some other technique to figure out what they're looking at from their position and rotation.

**Comment by minecraftkeba** [comment]
And how do I get anything about the world? From the seesion or from the client?

**Comment by Steveice10** [comment]
https://github.com/Steveice10/MCProtocolLib/blob/master/src/main/java/org/spacehq/mc/protocol/packet/ingame/server/world/ServerChunkDataPacket.java

**Comment by huangdihd** [comment]
This repo is just a packet library, so you can get some infomation from packets sent by the server
