### ISSUE TITLE
Get UUID

### ISSUE THREAD

**Issue by minecraftkeba** [GeyserMC/MCProtocolLib#129]
ServerSpawnPlayerPacket p = event.getPacket();
String UUID = p.getUUID().toString();

Is not giving the correct UUID of the Player which joined the Server.
Is there a way to fix that?

**Comment by Steveice10** [comment]
Actual player profiles with UUIDs are sent here: https://github.com/Steveice10/MCProtocolLib/blob/master/src/main/java/org/spacehq/mc/protocol/packet/ingame/server/ServerPlayerListEntryPacket.java
