### ISSUE TITLE
Feature Request: Forge Servers support

### ISSUE THREAD

**Issue by MatteCarra** [GeyserMC/MCProtocolLib#130]
It would be awesome if Forge servers would be supported.
Obviously we don't want to really load mods but only to fake them

**Comment by minecraftkeba** [comment]
Cool Idea. Love Forge.

**Comment by Steveice10** [comment]
MCProtocolLib does not support mod protocols. Plus, I'm fairly certain Forge uses plugin message packets nowadays, so it shouldn't need MCProtocolLib modifications for one to support.

**Comment by MatteCarra** [comment]
This links can be useful http://wiki.vg/Minecraft_Forge_Handshake
https://github.com/ORelio/Minecraft-Console-Client/pull/100
