### ISSUE TITLE
Drop whole Inventory?

### ISSUE THREAD

**Issue by minecraftkeba** [GeyserMC/MCProtocolLib#131]
I know how to drop Items from a Slot in the Hotbar with send(new ClientPlayerActionPacket(PlayerAction.DROP_ITEM_STACK, position, face));
but is it possible to drop all items in the Inventory?

**Comment by MatteCarra** [comment]
I think with a for.
There are 9*4 items in the player inventory

**Comment by minecraftkeba** [comment]
But how? I know there are 36 but I can only acces the on in Hand and that means only the Hotbar...

**Comment by Steveice10** [comment]
https://github.com/Steveice10/MCProtocolLib/blob/master/src/main/java/org/spacehq/mc/protocol/packet/ingame/client/window/ClientWindowActionPacket.java
