### ISSUE TITLE
Using the same protocol to connect to another server after disconnecting

### ISSUE THREAD

**Issue by ghost** [GeyserMC/MCProtocolLib#135]
When disconnecting from a server/Client, the protocol is used again to connect to another server/Client however the connection hangs and eventually "Connection closed." is received.

I'd prefer to keep the protocol open otherwise Mojang blocks my attempts to log in again due to spam-prevention. Is there a certain method or something I have overlooked?

**Comment by Steveice10** [comment]
For various reasons, protocol instances cannot be reused, like java sockets. This is not likely to change. You can, however, pull the access token from a dead protocol instance using the available method and use it to initialize a new instance.
