### ISSUE TITLE
1.9 Support

### ISSUE THREAD

**Issue by MatteCarra** [GeyserMC/MCProtocolLib#137]
Mojang has released 1.9
Minecraft protocol is now enough permanent.

**Comment by FormallyMyles** [comment]
There is a branch for 1.9

**Comment by MatteCarra** [comment]
Yes, but it is snapshot.
It isn't compatible with 1.9 stable

**Comment by Steveice10** [comment]
Done.

**Comment by MatteCarra** [comment]
You are the best.
Thank you.
