### ISSUE TITLE
1.9 Problems

### ISSUE THREAD

**Issue by MatteCarra** [GeyserMC/MCProtocolLib#138]
There are some problems with magic values: http://pastebin.com/YA7jf7DL
and http://pastebin.com/45MAHckp

P.S: I have a problem sending chat. I receive a Translation Message with chat.cannotSend
How can I solve this?

**Comment by Steveice10** [comment]
Should be fixed. Let me know if you run into any further data issues, as it can be easy to miss some value changes.

As for the chat problem, when sending the ClientSettingsPacket, make sure the chat visibility setting is set to one that allows sending normal chat.

**Comment by MatteCarra** [comment]
Fixed. Thank you very much.
