### ISSUE TITLE
Chunk bug

### ISSUE THREAD

**Issue by MatteCarra** [GeyserMC/MCProtocolLib#139]
I was testing chunk read and write.
I realised that writeColumn is bugged.
To test it I did this code with protocolLib:
http://pastebin.com/MyK9xiWj
And this is the output:
`[14:12:25 INFO]: New mask 63 old-> 63
New size: 37257 old-> 221551`
Edited chunks are all dark.

**Comment by Steveice10** [comment]
There are various factors to consider in chunk data size. Have you checked if the written data works when sent to a Minecraft client?

**Comment by MatteCarra** [comment]
Yes. Shadows don't work.
It is all dark

**Comment by Steveice10** [comment]
See what happens if you use true for the skylight boolean.

**Comment by MatteCarra** [comment]
It's the same

**Comment by MatteCarra** [comment]
I tried on this chunk
![2016-03-06_18 30 28](https://cloud.githubusercontent.com/assets/11074527/13555787/bdbfa458-e3c9-11e5-9f02-5827fdd81729.png)

**Comment by MatteCarra** [comment]
column.hasSkylight() is true

**Comment by Steveice10** [comment]
Try checking the values of the skylight and blocklight arrays, then?

**Comment by MatteCarra** [comment]
What should I check?

**Comment by MatteCarra** [comment]
I found the bug

**Comment by MatteCarra** [comment]
If I change only ONE BlockState a lot of BlockState change.
Why?

P.S:
SOLVED!
I wasn't using chunkBlockStorage.set(x, y, z, new BlockState(b.id, b.data));

**Comment by Steveice10** [comment]
Glad you fixed that. Pulled your changes, so everything should be working now.
