### ISSUE TITLE
Nether chunk column detection is not reliable

### ISSUE THREAD

**Issue by yawkat** [GeyserMC/MCProtocolLib#144]
The nether chunk column detection code which checks for remaining bytes in the chunk packet to see whether the chunk has skylight is not reliable, because vanilla will pad chunk packets with a bazillion zero bytes (see this spigot fix https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/c126d6101e8268f6d0691a4a07dc2c928a62a47a ).

**Comment by Steveice10** [comment]
Not sure if there are really any viable alternatives to that check. I'd rather not have to add a hack that tries to keep track of what world the client is in, as I don't think that'd be very reliable.
