### ISSUE TITLE
Disconnected: Internal network exception.

### ISSUE THREAD

**Issue by heke85** [GeyserMC/MCProtocolLib#145]
clean minecraft server function, but 1.9 BungeeCord "Disconnected: Internal network exception."
http://pastebin.com/XiJap3gG

Sorry for my english , I'm from Germany ^^

**Comment by FormallyMyles** [comment]
That's it running out of memory? Have you tried running a java profiler

**Comment by heke85** [comment]
1.8 I had no problems , but with 1.9
it connects to and then it exits

**Comment by heke85** [comment]
the problem lies in the BlockStorage.java
if I in NetUtil.java in line 248 `BlockStorage blocks = new BlockStorage(in);` with `BlockStorage blocks = null;` replaced, it works without propleme.

**Comment by heke85** [comment]
I forgot to say , it is in android

**Comment by goosewoman** [comment]
I'm having the same problem trying to update to 1.10. There's en Exception that's caught before I could possibly see what's wrong with it. This is really annoying when I'm trying to debug problems. Let me catch the exceptions myself or let me at least override the exception catcher so I can debug problems. @Steveice10
