### ISSUE TITLE
Can't move?

### ISSUE THREAD

**Issue by ForLoopMC** [GeyserMC/MCProtocolLib#146]
Using the code

`client.getSession().send(new ClientPlayerPositionPacket(isGrounded, 10,0,0));`

In a runnable, running every 3 seconds doesn't run? It says it runs my debug code, However doesn't run the code above^

**Comment by Steveice10** [comment]
This is for issue tickets, not support questions.

**Comment by heke85** [comment]
With 1.8 and this code move the player, but with 1.9 not
