### ISSUE TITLE
Caused by: java.lang.IllegalArgumentException: Value  has no mapping for key class org.spacehq.mc.v1_9.protocol.data.game.scoreboard.NameTagVisibility

### ISSUE THREAD

**Issue by MatteCarra** [GeyserMC/MCProtocolLib#149]
http://pastebin.com/bbsdmXVs

**Comment by Steveice10** [comment]
Is this from connecting to an unmodified Minecraft server? Otherwise, what kind of server is it?

**Comment by MatteCarra** [comment]
It was a 1.8/1.9 server

**Comment by minecraftkeba** [comment]
Send your code please.

**Comment by Steveice10** [comment]
Have you experienced this again at all?

**Comment by 31415x** [comment]
I am experiencing a very similar crash message ("Value ALWAYS has no mapping for key class org.spacehq.mc.protocol.data.game.scoreboard.NameTagVisibility.") and am not sure whether it is the same or at least a very similar problem, so I am adding it here.

http://pastebin.com/j5ZEr8c0

I am using the McProtocolLib example code and am attempting to connect to what appears to be a Spigot BungeeCoord server. Connecting to normal Spigot or Vanilla servers works fine.

**Comment by marshallwalker** [comment]
I'me having this same issue, 

http://hastebin.com/usegoferas.avrasm

this is the error, EXCEPT  the value is empty

it happens even when I run the example code.

**Comment by 31415x** [comment]
I think I have been able to pinpoint the cause of _"Value ALWAYS has no mapping for key class org.spacehq.mc.protocol.data.game.scoreboard.NameTagVisibility."_: The server uses a custom tab list that displays additional information about the server. This change has been reverted and I can connect fine; a different server that uses a custom tab list is broken, too.

**Comment by marshallwalker** [comment]
Hmm, I can connect to vanilla 1.9 servers just fine & we have a custom tab as well that changes overhead names too, I can't seem to connect to protocol hacked server I.E ViaVersion etc...

**Comment by Steveice10** [comment]
Values are now compared case-insensitively.
