### ISSUE TITLE
Provide proper toString for packets

### ISSUE THREAD

**Issue by yawkat** [GeyserMC/MCProtocolLib#152]
It would be useful for debugging to have proper toStrings for the packet classes.

I can think of two simple approaches to this:
- use lombok (would also allow equals/hashcode)
- use some kind of reflective toString builder and call it from the implementations (probably relatively slow but shouldn't matter for toString)

Generating the toStrings is of course also possible but quite a lot of boilerplate.

I could implement any of these approaches if one can be decided on.

**Comment by Steveice10** [comment]
The main reason this hasn't been done yet is due to the sheer time it would take, so a generation approach would be favorable. I'd rather not be depending on Lombok though, so option 2 sounds more preferable.
