### ISSUE TITLE
Client won't move

### ISSUE THREAD

**Issue by Chraebe** [GeyserMC/MCProtocolLib#154]
Hi. I know this is an issue, which has been asked a couple of times already, but neither of the solutions seemed to work for me. So I'm trying again;

I am trying to get the client to work, however whatever I do, the client won't work. For example, I tried to just copy the code from the solution from #133 completely, but it wouldn't work. Can someone help me with this issue? My code is [here](http://pastebin.com/AujJ78a0).

Thank you..

**Comment by minecraftkeba** [comment]
Which version of the lib do you use?

**Comment by Chraebe** [comment]
@minecraftkeba the latest one, for Minecraft 1.9.2, merge 155

**Comment by MrPowerGamerBR** [comment]
@Chraebe did you find a solution? I tried to use my code I shared on the other issue and it isn't working anymore (idk why, it was working when I tried it)

**Comment by MrPowerGamerBR** [comment]
Already found the solution, you need to add y ~~+~~ - 1.62 when moving the player ;)

Update: Sorry, it is to SUBTRACT 1.6.2, not add.
