### ISSUE TITLE
How to right click with item?

### ISSUE THREAD

**Issue by minecraftkeba** [GeyserMC/MCProtocolLib#158]
How do I right click with a seed for example to plant it?

**Comment by Steveice10** [comment]
https://github.com/Steveice10/MCProtocolLib/blob/master/src/main/java/org/spacehq/mc/protocol/packet/ingame/client/player/ClientPlayerUseItemPacket.java

**Comment by minecraftkeba** [comment]
But how in 1.8.8? And where can I download the lib for 1.8?

**Comment by minecraftkeba** [comment]
Ok, I used the BlockPlacePacket. Worked.
