### ISSUE TITLE
ClientPlayerPlaceBlockPacket not working?

### ISSUE THREAD

**Issue by Chraebe** [GeyserMC/MCProtocolLib#161]
Hi. I am trying to get my client to place a block. In this particular example, where I explain my issue, I will be talking about a situation, where the block is a sand block, and needs to be placed ON TOP of a dirt block. My issue is, that the client does not respond to the sended packet, and never actually places a block. This is my code for sending the packet:

```
Main.session.send(new ClientPlayerPlaceBlockPacket(new Position(95, 66, 198), BlockFace.UP,
                Hand.MAIN_HAND, 0.5f, 0.5f, 0.5f));
```

The issue is not sending packages, for example, this package works:

```
Main.session.send(new ClientPlayerActionPacket(PlayerAction.START_DIGGING, new Position((int)pos.x,
                    (int)pos.y, (int)pos.z), BlockFace.valueOf(face)));
```

Other packets works as well. I am suspecting that I am using the packet wrong, so let me explain my logic:
- The block position is at 95, 66, 198, so the block that it is placed on is at 95, 65, 198.
- The block face I suppose is the face on which the block is placed on. So on the block at 95, 65, 198 it is placed on the face UP.
- The cursor position is multiplied by 16 before being sended, so I suppose I need a value between 0-1.

Can someone see what I am doing wrong here?

**Comment by Chraebe** [comment]
I figured out the problem - when recieving a `ServerPlayerPositionRotationPacket` the server needs a `ClientTeleportConfirmPacket` with the same TeleportID as the server sent with the packet. Otherwise, it will ignore all player actions, including placing and walking.

**Comment by heke85** [comment]
Thanks, this works. ^^
