### ISSUE TITLE
Question on integration and worlds

### ISSUE THREAD

**Issue by GramDev1** [GeyserMC/MCProtocolLib#166]
Hi,
Is there a way to save the world this generates for the server? Also, is this possible to integrate with  bukkit? Thanks

**Comment by Steveice10** [comment]
This is simply a network protocol library. It does not generate worlds itself.

**Comment by GramDev1** [comment]
Then how does the server work.... It needs a world

**Comment by ctian1** [comment]
@mcjp78 it's not a server..

**Comment by GramDev1** [comment]
Server server = new server()

But it is? Unless I am mistaken....
