### ISSUE TITLE
Connecting to a server

### ISSUE THREAD

**Issue by GramDev1** [GeyserMC/MCProtocolLib#167]
Hi,
When I use the server created by this lib it is stuck on downloading terrain. How can I fix this?

**Comment by Steveice10** [comment]
Are you actually sending world data?

**Comment by GramDev1** [comment]
No.. I can't seem to figure out how to send world data/ a world

**Comment by Steveice10** [comment]
You can read up on how to use the protocol here: http://wiki.vg
