### ISSUE TITLE
Interacting with an inventory

### ISSUE THREAD

**Issue by JamMasterz** [GeyserMC/MCProtocolLib#174]
Hello. I apologize for a stiupid question, but after a long time searching and trying i gave up. Maybe this  will also help others with a similar problem. 

I'm trying to open an inventory(chest) and take out some items. I narrowed it down to the ClientPlayerInteractEntityPacket, but i can't get it to work. I don't know the entity ID for the chest if it even has one and I don't know if I'm supposed to use InteractionAction.INTERACT or InteractionAction.INTERACT_AT. I sent the packet with entityID = 0 and both InteractionAction options but i never got a response. How do I do this?

If I ever get this working, I expect a window Id in the response, which i will be able to use in ClientWindowActionPacket to move the items, am I correct?

**Comment by JamMasterz** [comment]
With minecraftkeba's help,I managed to do it. I will describe how for other people who have this problem. To open a chest, you send ClientPlayerPlaceBlockPacket, at the coordinates of the chest(have to specify the same coords twice in the arguments for some reason), on the TOP face of the chest. Then you will receive ServerOpenWindowPacket where you can get a lot of useful information about the window. Then you will receive ServerWindowItemsPacket, which contains the chest and your inventory combined into one array. In this array, the chest comes first, then the inventory, and at the end the hotbar. To shift click items out from one inventory to another, you have to send ClientWindowActionPacket(windowId, actionId++, slot, null, WindowAction.SHIFT_CLICK_ITEM, ShiftClickItemParam.LEFT_CLICK), where actionId is unique for every transaction and slot is the index of the item you are shift clicking in the array you got earlier. For every ClientWindowActionPacket, you will receive a ServerConfirmTransactionPacket, to which you have to respond by sending a ClientConfirmTransactionPacket with the "accepted" field set to true. That pretty much sums it up.

**Comment by PoLsKiPaLaCz** [comment]
@JamMasterz how would i right click a item with a bot?

**Comment by 109C** [comment]
@PoLsKiPaLaCz `ClientWindowActionPacket`
