### ISSUE TITLE
Release minecraft 1.9.4 maven version?

### ISSUE THREAD

**Issue by daboross** [GeyserMC/MCProtocolLib#177]
It seems the latest 1.9.4-SNAPSHOT build is actually a 1.9.10 version. Would it be at all possible to publish a release version of 1.9.4 for access via the maven build server?

If not, that's also fine - I guess using specific snapshot versions works. Awesome library, by the way!

**Comment by ghost** [comment]
well the 1.9.4-SNAPSHOT version for MC 1.10 was my mistake
