### ISSUE TITLE
Connection Exceptions are caught before I can debug them.

### ISSUE THREAD

**Issue by goosewoman** [GeyserMC/MCProtocolLib#185]
Right now there's an exception being thrown in my client that leads to an "Internal Network Exception" error being thrown. The Exception is being caught before I could possibly see what's wrong with my application. This is really annoying when I'm trying to debug problems. Let me catch the exceptions myself or let me at least override the exception catcher so I can actually manage the exceptions that are thrown in my application/connection. @Steveice10

**Comment by Steveice10** [comment]
Listen for DisconnectedEvents and check [getCause](https://github.com/Steveice10/PacketLib/blob/master/src/main/java/org/spacehq/packetlib/event/session/DisconnectedEvent.java#L59) for an exception.
