### ISSUE TITLE
Source and Javadoc as maven artificats

### ISSUE THREAD

**Issue by TuxCoding** [GeyserMC/MCProtocolLib#187]
Is it somehow possible to attach the source and javadoc artificats to the main build of mcprocotollib?

**Comment by minecraftkeba** [comment]
Not that I know, but why would you want to do that?

**Comment by TuxCoding** [comment]
To have the documentation available directly in the IDE.

**Comment by minecraftkeba** [comment]
That is a good idea, but it has nothing to do with this. You should ask the support for Eclipse IDE, shouldn´t you?

**Comment by TuxCoding** [comment]
??? No the javadoc should be just be available as another maven artifact. I think it's the issue that the dependencies are shaded together instead of keeping them seperate.

**Comment by minecraftkeba** [comment]
Yes, you right. But only Steveice10 can fix that then.

**Comment by Steveice10** [comment]
Done.
