### ISSUE TITLE
Get Block at Position

### ISSUE THREAD

**Issue by minecraftkeba** [GeyserMC/MCProtocolLib#188]
I have got an x y z, in the chunck the player is in, is it possible to get the id of the block on this position?
If yes, how?

**Comment by ghost** [comment]
You should keep the data yourself. The library is about the protocol not the game data.

**Comment by phase** [comment]
`ServerChunkDataPacket`s send `Column`s which contain the chunks around the player. You'll want to store these when they are sent to you. You'll also want to look out for `ServerBlockChangePacket` and `ServerMultiBlockChangePacket`.

Here's some pseudocode (actually, it's Kotlin).

``` kotlin
when (packet) {
    is ServerChunkDataPacket -> {
        chunks.add(packet.column)
    }
    is ServerMultiBlockChangePacket -> {
        for (record in packet.records) {
            updateBlock(record)
        }
    }
    is ServerBlockChangePacket -> {
        updateBlock(packet.record)
    }
}
```

where `chunks` is an `ArrayList<Column>` and `updateBlock` is defined as

``` java
void updateBlock(BlockChangeRecord record) {
    // This is where the chunk is located
    int chunkX = record.position.x / 16;
    int chunkY = record.position.y / 16;
    int chunkZ = record.position.z / 16;
    // This is the block's position within the chunk
    int blockX = record.position.x % 16;
    int blockY = record.position.y % 16;
    int blockZ = record.position.z % 16;
    // This gets the Column from the x and z, and the Chunk from the y.
    getChunkColumn(chunkX, chunkZ).chunks[chunkY].blocks.set(blockX, blockY, blockZ, record.block);
}
```

To get the ID of a block at a location, you'll want to get the `BlockState` out of the `Chunk`.

``` java
BlockState getBlockState(int ax, int ay, int az) {
    int blockX = ax % 16;
    int blockY = ay % 16;
    int blockZ = az % 16;
    return getChunkColumn(chunkX, chunkZ).chunks[chunkY].blocks.get(blockX, blockY, blockZ);
}
```

`BlockState` contains the methods `getId()` and `getData`, and you probably know how those work.
