### ISSUE TITLE
PluginChannels

### ISSUE THREAD

**Issue by marshallwalker** [GeyserMC/MCProtocolLib#189]
Is is possible to communicate with Plugin channels, I've tried sending plugin messages to some Custom Channels & am listening to them but not getting any data, do I need to register the channel client-side somehow? if so could you tel me how.

Thanks in advance!

**Comment by TuxCoding** [comment]
You have to register the channel to the server first.

http://wiki.vg/Plugin_channels#REGISTER

**Comment by marshallwalker** [comment]
I have registered the channel in the plugin, I' unsure of the payload for the client to register a plugin channel.

**Comment by TuxCoding** [comment]
As far as I know the client should respond with a register message too including the currently listening channels.

**Comment by marshallwalker** [comment]
Something like this?

http://hastebin.com/eruyajeren.coffee

**Comment by TuxCoding** [comment]
I think I'm wrong, that should only do the server.

Do you use the same channel as on the server?

**Comment by marshallwalker** [comment]
I'm attempting to communicate with BungeeCord plugin channel

**Comment by TuxCoding** [comment]
Could you post your relevant bungee code

**Comment by marshallwalker** [comment]
no, I mean I'm literally trying to interact with BungeeCord channel, no plugin, from what I understand, plugins allow you to run plugin messages as a user on a channel, I want to communicate with the channel without using a plugin

**Comment by TuxCoding** [comment]
BungeeCord reads only internal things like ForwardPlayer from the server -> client direction.

**Comment by marshallwalker** [comment]
Alright thanks
