### ISSUE TITLE
achievement.enchantments has no mapping for key class

### ISSUE THREAD

**Issue by segreeeen** [GeyserMC/MCProtocolLib#194]
Hi!

Getting this error when trying your test class on a 1.10.2 server (pelzz.net:25575)

`Disconnected: io.netty.handler.codec.DecoderException: java.lang.IllegalArgumentException: Value achievement.enchantments has no mapping for key class org.spacehq.mc.protocol.data.game.statistic.Achievement.
io.netty.handler.codec.DecoderException: java.lang.IllegalArgumentException: Value achievement.enchantments has no mapping for key class org.spacehq.mc.protocol.data.game.statistic.Achievement.`

Maybe you can fix it :).

**Comment by phase** [comment]
It looks like `ENCHANTMENTS` is missing from [Achievement.java](https://github.com/Steveice10/MCProtocolLib/blob/master/src/main/java/org/spacehq/mc/protocol/data/game/statistic/Achievement.java), as well as a [few other ones](http://minecraft.gamepedia.com/Achievements#List_of_achievements).

**Comment by segreeeen** [comment]
Thanks, works like a charm!
