### ISSUE TITLE
Blockstorage/serverchunkdatapacket (memory leak)

### ISSUE THREAD

**Issue by Arjenpro** [GeyserMC/MCProtocolLib#195]
heres the error;

http://hastebin.com/ozohegumoj.avrasm

maybe you can fix it, thanks!

**Comment by Steveice10** [comment]
Are you certain this is a memory leak and not just the client not having enough memory?

**Comment by Arjenpro** [comment]
Yes, im starting with 512mb? I think that's enough lol

**Comment by Steveice10** [comment]
Does this still occur on the latest builds?
