### ISSUE TITLE
Error while placing Block

### ISSUE THREAD

**Issue by minecraftkeba** [GeyserMC/MCProtocolLib#196]
When trying to place a Block, the Block disappears after half a secound again.

Code:

Position p = new Position(x, y, z);
bot.send(new ClientPlayerPlaceBlockPacket(p, Face.TOP, items[s], 7, 7 , 7));
bot.send(new ClientPlayerPositionRotationPacket(true, Bot.x, Bot.y, Bot.z, Bot.yaw, 30));

**Comment by phase** [comment]
Are you sure that is the correct face to place off of? Are you sure that you have permission to place blocks in that area?

**Comment by minecraftkeba** [comment]
Yes, but I think it is a generall problem cause when I disconnect the bot
and join normally I still won't be able to place a block. Any Idea why this
happens.

Am 26.09.2016 00:07 schrieb "Jadon Fowler" notifications@github.com:

**Comment by minecraftkeba** [comment]
Could the Server know if I am connecting with the protocollib or with a real client?

**Comment by GravelCZ** [comment]
when you receive ServerPlayerPositionRotationPacket do you respond with ClientTeleportConfirmPacket ?
