### ISSUE TITLE
Move Bot

### ISSUE THREAD

**Issue by P42C41** [GeyserMC/MCProtocolLib#197]
Yo, i'm trying to make a bot system for my Minecraft Modification, atm i can let them connect and write in chat, now i want, that they follow me. Is that even possible with that lib or nor? If yes, how?

**Comment by TuxCoding** [comment]
Yes it's possible. It just requires some work. You have to track the player movement around your bot and send movement packets (http://wiki.vg/Protocol#Player_Position).

**Comment by P42C41** [comment]
Is there anywhere a example of moving the Player?

**Comment by phase** [comment]
``` java
client.getSession().send(new ClientPlayerPositionRotationPacket(onGround, pos.x, pos.y, pos.z, yaw, pitch));
```

**Comment by Mareckoo01** [comment]
I also tried that but bot doesn't move (tested on latest spigot with no plugins and latest mcpl),
no errors/(useful)info in server/bot console...
[code](https://gist.github.com/Mareckoo01/3725dbf0d2302fb6a7a26d7568d5cafe)

**Comment by phase** [comment]
Position packets send absolute coords. You need to get the position from the server, store it, manipulate it, and send the new values. If the distance is too far, the server will ignore it.

**Comment by Mareckoo01** [comment]
i do that, do i need to add/subtract from some coordinates?
[full code](https://gist.github.com/Mareckoo01/3725dbf0d2302fb6a7a26d7568d5cafe)
[output](https://gist.github.com/Mareckoo01/3ce3e0f2e21e58748b47740574abad0b)

EDIT: i tried this code on 1.9.4, didn't work but on 1.8.8 it worked without changing anything just mcpl version (server settings are the same)

EDIT 2: after reading [wiki.vg/Protocol_FAQ](http://wiki.vg/Protocol_FAQ) all i needed to do is add [this line](https://gist.github.com/Mareckoo01/3725dbf0d2302fb6a7a26d7568d5cafe#file-testing-java-L74) to current code and it works...
