### ISSUE TITLE
#Move Bot - MC 1.5.2

### ISSUE THREAD

**Issue by ghost** [GeyserMC/MCProtocolLib#199]
I'm using this version (https://github.com/Steveice10/MCProtocolLib/tree/fe0896efe5060f135cfaf6afdedba206343c1698)

---------------------------

This is my code:

PacketPlayerPosition po = new PacketPlayerPosition(x, y, y - 1.62, z, true);
Client.send(po);

However, the server simply ignores the packet, nothing happens.

(sorry, ask for support for this version, but it's a project I'm doing.)

Edit: Packets as "PacketPlayer", among others, are also ignored by the server.

**Comment by ghost** [comment]
OK, I managed to make the bot move.

Thank you all.

**Comment by FlamestoN** [comment]
Hello.
How you solved this?
