### ISSUE TITLE
Register Entity

### ISSUE THREAD

**Issue by ghost** [GeyserMC/MCProtocolLib#203]
java.lang.IllegalArgumentException: Value 30 has no mapping for key class org.spacehq.mc.protocol.data.game.entity.type.MobType.

**Comment by ghost** [comment]
Register Armor Stand.

**Comment by theminecoder** [comment]
Same issue here.

**Comment by ghost** [comment]
I believe this error relates to armor stands.

**Comment by Steveice10** [comment]
Is it verified that this ID is an armor stand? It's not listed on the protocol wiki's mob list.
