### ISSUE TITLE
Incoming packets

### ISSUE THREAD

**Issue by ghost** [GeyserMC/MCProtocolLib#208]
Is there a method for detecting incoming packets? I'm trying to get the data from chat currently.

**Comment by Steveice10** [comment]
Check the example included in the git repository.

**Comment by ghost** [comment]
It's only registering incoming packets from the package org.spacehq.mc.protocol.packet.login.server , I'm also using the code included in the xample repository.

**Comment by TuxCoding** [comment]
Isn't the ServerChatPacket what you want?

**Comment by ghost** [comment]
@games647 correct but even when i have people say stuff in chat it doesn't event output that is recieved the packet, the code I'm using. http://pastebin.com/w2AecDqT

**Comment by TuxCoding** [comment]
Do you have spawn server activated? I believe it just connects to the MCProtocolLib fake server and then waits for further packets. If you let it connect to a normal Spigot server, you get many other packets including the ServerChatPacket.

**Comment by ghost** [comment]
@games647 Ok so not using the example program currently but I was still running into the same issue, whenever I try to do server.bind(); I get this error: http://pastebin.com/WNH0fiKp

**Comment by TuxCoding** [comment]
Server.bind() makes a server. I thought you want to make a client?

**Comment by ghost** [comment]
@games647 yeah that's what I'm saying. I'm trying to make a client and being able to go through incoming packets that are going to the bot(s).

**Comment by TuxCoding** [comment]
Then you don't need Server.bind(). That's for creating a server. You only need that part: https://github.com/Steveice10/MCProtocolLib/blob/master/example/org/spacehq/mc/protocol/test/MinecraftProtocolTest.java#L141

where Host and PORT is your target running server you want your bots to connect to.

**Comment by ghost** [comment]
@games647 using http://pastebin.com/stD0NABe
My only output is this:
class org.spacehq.mc.protocol.packet.login.server.EncryptionRequestPacket
class org.spacehq.mc.protocol.packet.login.server.LoginSetCompressionPacket
class org.spacehq.mc.protocol.packet.login.server.LoginSuccessPacket
It seems like none of the other packets are getting registered?
But like the ConnectedEvent and DisconnectedEvent events/methods work fine dou.

**Comment by ghost** [comment]
Hmm ok seems to be an issue on my end as after I updated the libraries it now is working.
