### ISSUE TITLE
Maven

### ISSUE THREAD

**Issue by GramDev1** [GeyserMC/MCProtocolLib#210]
Hi,
Is there a maven repo & artifact for this? Or do I have to download the build and use that

**Comment by Steveice10** [comment]
https://repo.spacehq.org/

**Comment by ghost** [comment]
Qustion actual for now again. Thanks for ruining my [code](https://github.com/Ensemplix/Flunky) once again ;)

**Comment by Steveice10** [comment]
Just use something like jitpack like I am in my pom. I'm not hosting a website anymore.

**Comment by ghost** [comment]
Cool story. And where i can get old versions? ty for another shit.

**Comment by TheElectronWill** [comment]
@ensirius You can build any commit with jit pack. https://jitpack.io/#Steveice10/MCProtocolLib

**Comment by TuxCoding** [comment]
>@ensirius You can build any commit with jit pack. https://jitpack.io/#Steveice10/MCProtocolLib

No it's only possible since he migrated to a com.github group id (661faf954146adc562b9ca60266e87157dbb7068). Before Jitpack cannot find the dependencies like OpenNBT.

A build of one commit before the migration:
https://jitpack.io/com/github/Steveice10/MCProtocolLib/ce0b5ca9ec8239528e1867dca76cf18e556152c1/build.log

**Comment by Steveice10** [comment]
If you want to put older builds up for download somewhere or on some maven repository, feel free, but I simply don't have mine anymore.

**Comment by MrPowerGamerBR** [comment]
https://mrpowergamerbr.com/files/mcprotocollib-1.8.8-SNAPSHOT.jar
https://mrpowergamerbr.com/files/packetlib-1.0.jar
https://mrpowergamerbr.com/files/mcauthlib-1.0-SNAPSHOT.jar
https://mrpowergamerbr.com/files/opennbt-1.1.jar

Here's some of the compiled JAR files I have on my local maven repo for all (or at least almost all of them) MCProtocolLib 1.8.8 dependencies & MCProtocolLib 1.8.8 itself.

I used them before and they work fine (at least I could run the MCProtocolLib example successfully), so... have fun!
