### ISSUE TITLE
Generate .mcpr or .tmcpr "Replay-File" with Protocol Lib

### ISSUE THREAD

**Issue by TheSnoozer** [GeyserMC/MCProtocolLib#211]
Hi, I was wondering if there is any way to generate a  .mcpr or .tmcpr "Replay-File" with the Protocol Lib.
This file would basically allow to view whatever happened in a third person perspective.
The only resources I found related to this Topic is here:
https://www.replaymod.com/forum/thread/609#post3335

```
The .tmcpr file can be read using a DataInputStream in Java.
The following pattern repeats until EOF:

1) an Integer which represents the packet's timestamp (in milliseconds from Replay start)
2) an Integer which tells you how many bytes the packet consists of
3) a byte array which represents the packet
```

```java
private static void writePacket(DataOutputStream os, long time, Packet packet) throws IOException {
	ByteBuf buf = PooledByteBufAllocator.DEFAULT.buffer();
	NetUtils.writeVarInt(buf, REVERSE_PACKET_MAP.get(packet.getClass()));
	packet.write(buf);
	int length = buf.readableBytes();

	os.writeInt((int) time);
	os.writeInt(length);
	buf.readBytes(os, length);
	buf.release();
}
```

Here are some further resources that seemed to be some sort of helpful
1) a "replay converter":
https://github.com/ReplayMod/replay-converter/blob/master/src/main/java/de/johni0702/mc/replay/converter/Main.java

2) a "mcpr-File-Reader-api":
https://github.com/Moonlight63/ReplayMod-.mcpr-File-Reader-api-/blob/master/src/bin/MainWindow.java

I tried to get it working, but no chance xD
Any Input would be highly appreciated.

Thanks,

**Comment by Steveice10** [comment]
I would suggest listening for packets as the example code does, and then writing the packets, along with whatever extra info the format needs, to a file.
