### ISSUE TITLE
Question - BlockStorage

### ISSUE THREAD

**Issue by JeromSar** [GeyserMC/MCProtocolLib#213]
Hi,

I was wondering if `BlockStorage.get(x, y, z)` and `BlockStorage.set(x, y, z)` use relative values (0-15) or absolute values (world coordinates)  as arguments. Due to the lack of Javadoc, these types of ambiguities may sometimes arise.

If you could help me out, I would be really grateful.

**Comment by Steveice10** [comment]
As BlockStorage is per-chunk, it uses chunk coordinates (0-15).

**Comment by JeromSar** [comment]
Thanks
