### ISSUE TITLE
Conform naming to wiki

### ISSUE THREAD

**Issue by JeromSar** [GeyserMC/MCProtocolLib#214]
I noticed quite some names (esp. packet names, subprotocol names and field names) are inconsistent with the [wiki.vg protocol specification](http://wiki.vg/Protocol). Would you be accepting PRs that allow MCProtocolLib to become consistent with the protocol spec?

**Comment by Steveice10** [comment]
Depends on the packet. Some I might be flexible on, but others, if I recall correctly, have a wiki name that just doesn't explain the packet's purpose well enough.

**Comment by JeromSar** [comment]
After closer inspection, it seems that your naming indeed makes more sense than the wiki. By grouping for example all player related packets together, a nice structure is achieved. Perhaps the wiki ought to conform to your naming scheme. 😄
