### ISSUE TITLE
Value 33 has no mapping for key class org.spacehq.mc.protocol.data.game.entity.EntityStatus

### ISSUE THREAD

**Issue by 0-x-2-2** [GeyserMC/MCProtocolLib#217]
Stacktrace: http://pastebin.com/bLe689uR

**Comment by Steveice10** [comment]
Fixed in https://github.com/Steveice10/MCProtocolLib/commit/2cf859666879c4e82c2c07dbc37e1cd95c2ab8e0

**Comment by 0-x-2-2** [comment]
thanks
