### ISSUE TITLE
Shulker Box Crash: Value 10 has no mapping for key class org.spacehq.mc.protocol.data.game.world.block.UpdatedTileType.

### ISSUE THREAD

**Issue by 0-x-2-2** [GeyserMC/MCProtocolLib#218]
Stacktrace: http://pastebin.com/5LHd1i40

**Comment by 0-x-2-2** [comment]
oops lol

**Comment by Steveice10** [comment]
Fixed in https://github.com/Steveice10/MCProtocolLib/commit/ce0b5ca9ec8239528e1867dca76cf18e556152c1
