### ISSUE TITLE
Bot won't move

### ISSUE THREAD

**Issue by Xayanix** [GeyserMC/MCProtocolLib#219]
Code below is not moving bot.
Im using version for 1.8.x.

```
while(true){
    Location location = botdata.getLocation();
    if(location != null) {
        bot.getSession().send(new ClientPlayerPositionPacket(true, botdata.getLocation().getX() + 0.215, botdata.getLocation().getY(), botdata.getLocation().getZ()));
    }
					
    try { Thread.sleep(1000); } catch (InterruptedException e) { e.printStackTrace(); }
}
```

**Comment by ghost** [comment]
I think you need to send the ClientTeleportConfirmPacket (something like that), I'm not sure about that.

**Comment by phase** [comment]
Make sure you set you're bot location after you've sent the packet.

**Comment by Xayanix** [comment]
ClientTeleportConfirmPacket does not exist in 1.8.8 build of MCProtocolLib. I'm resetting bot location after sending packet. I've read every topic in that repository and tried everything.

**Comment by phase** [comment]
I [use](https://github.com/phase/PhaseBot/blob/master/src/xyz/jadonfowler/phasebot/Bot.java#L189) `ClientPlayerPositionRotationPacket`.

**Comment by Xayanix** [comment]
Thanks, i will analyze your code and check it soon.

**Comment by Xayanix** [comment]
I've copy&pasted your code to mine.
start loc: [x=-1726.5, y=4.0000000047683715, z=-690.5]
m: -1706.5 4.0000000047683715 -690.5
p: 0.0021728405 y:112.0297
s: 0.536277173913043 0.0010869565230348834 -0.18763586956521738

ProtocolLib detects PacketPlayInPositionLook but bot still stays in place. Do i need to register some packet or simillar stuff before i send move packet?

http://pastebin.com/KvigRSEn

**Comment by jkrossouw** [comment]
When a client spawns or tries to make an invalid move the server sends a ServerPlayerPositionRotationPacket to the client. After sending this packet the server will ignore any movement packets from the client until the client responds with a ClientPlayerPositionRotationPacket that indicates the same position as the packet the server sent. (The client must acknowledge the position the server sent it). 

After you send the ClientPlayerPositionRotationPacket confirming the position you can send your movement packets and the server should process them correctly. 

I wrote a bot and proxy for Minecraft 1.8.x using this library as part of an university project so I can confirm the library works fine for this version.

**Comment by Xayanix** [comment]
@up
That's the solution. Thanks.
