### ISSUE TITLE
BuiltinSound mismatch with 1.11.2

### ISSUE THREAD

**Issue by gouyelliot** [GeyserMC/MCProtocolLib#222]
You forgot to add ShulkerBox sound in BuiltinSound, it's create a mismatch on next id because you're registering BuiltinSound with the Enums.ordinal() method.

See : http://pokechu22.github.io/Burger/1.11.html#sounds:block.shulker_box.close

Ps : Great library !

**Comment by Steveice10** [comment]
Should be fixed.
