### ISSUE TITLE
What is the best way to check if the server is in offline mode?

### ISSUE THREAD

**Issue by stenocyb** [GeyserMC/MCProtocolLib#224]
I already thought of connecting a cracked client to a server and see if it works, but this method seems a bit hacky. Is there any other way?

**Comment by TuxCoding** [comment]
If the server returns the player list, it will include the UUID for each player too. Then you generate the offline UUID using the player name and compare the two uuids. 

This works for some servers, but it also only a workaround.

**Comment by stenocyb** [comment]
Ah, that's a cool idea but unfortunately some servers don't return the player list, so this method is not reliable. Anyways, thanks for your reply :)

**Comment by 0-x-2-2** [comment]
why do you have to check?

**Comment by stenocyb** [comment]
Because if the server is in offline mode, my program will generate some random minecraft usernames and connect to the server. But if this is not the case, it will authenticate with valid minecraft account credentials and then connect to the server.
