### ISSUE TITLE
Different Versions

### ISSUE THREAD

**Issue by GramDev1** [GeyserMC/MCProtocolLib#225]
Hi,
With the old spacehq website I could get older versions of this (1.8,1.9). How can I get them now
thanks

**Comment by Steveice10** [comment]
You could pull a certain source commit for the version you want and build it.

**Comment by GramDev1** [comment]
You mean just revert everything since a certain commit @Steveice10 ?

**Comment by phase** [comment]
`git checkout <commit hash>`
