### ISSUE TITLE
McProtocoLib 1.8.8 version?

### ISSUE THREAD

**Issue by dekros987** [GeyserMC/MCProtocolLib#226]
Close

**Comment by Steveice10** [comment]
You can check out an older commit from back when 1.8.8 was the latest version.

**Comment by dekros987** [comment]
Close

**Comment by PoLsKiPaLaCz** [comment]
hi... i have had problems with the maven imports for the older Proxy server (1.8) and it doesnt seem to find the import could you please help

**Comment by Mareckoo01** [comment]
Just read the error... MCProtocolLib needs dependencies - [MCAuthLib](https://github.com/Steveice10/MCAuthLib), [PacketLib](https://github.com/Steveice10/PacketLib) and [OpenNBT](https://github.com/Steveice10/OpenNBT)
You need to edit pom.xml [just like i did](https://github.com/Mareckoo01/MCProtocolLib/commits/1.8/pom.xml)...
Don't forget that only [latest](https://github.com/Steveice10/MCProtocolLib) MCProtocolLib version **is supported**.
