### ISSUE TITLE
disconnect bots, get full stack strace

### ISSUE THREAD

**Issue by Lennyss** [GeyserMC/MCProtocolLib#229]
how can i get full stack trace on disconnect?
    @Override
    public void disconnected(DisconnectedEvent event) {
        event.getCause().printStackTrace();
        System.out.println("Disconnected: " + event.getReason());
    }
only got: NullPointer... nothink more

**Comment by Steveice10** [comment]
Printing the stack trace of the cause *does* give the full stack trace.

**Comment by Lennyss** [comment]
but this only print me NullPointerException, how can i find error wihout line/class somethink like this?

**Comment by Steveice10** [comment]
If printStackTrace isn't showing that, there isn't really much else that can be done. The only thing I can think of is to make sure you're getting stderr output, not just stdout.
