### ISSUE TITLE
Map icon issue

### ISSUE THREAD

**Issue by DaMatrix** [GeyserMC/MCProtocolLib#232]
I have a map in an item frame, and when joining a server through PacketLib, i get the following error (causes the client to disconnect):
`Disconnecting... Reason: io.netty.handler.codec.DecoderException: java.lang.IllegalArgumentException: Key 1 has no mapping for value class com.github.steveice10.mc.protocol.data.game.world.map.MapIconType.
Disconnected.`

This seems to be caused by line 71 of [this](https://github.com/Steveice10/MCProtocolLib/blob/62bb2240ba46118ad883627878b30b770d712525/src/main/java/com/github/steveice10/mc/protocol/packet/ingame/server/world/ServerMapDataPacket.java#L71).

Am I doing something wrong, or is this a bug? Thanks!

**Comment by Steveice10** [comment]
Should be fixed now.

**Comment by DaMatrix** [comment]
Seems to be working, thanks
