### ISSUE TITLE
Sound decoding issue

### ISSUE THREAD

**Issue by DaMatrix** [GeyserMC/MCProtocolLib#233]
Another one! This time it's
`
Disconnecting. Reason: io.netty.handler.codec.DecoderException: java.lang.IllegalArgumentException: Value 465 has no mapping for key class com.github.steveice10.mc.protocol.data.game.world.sound.BuiltinSound.
`
Thanks!

**Comment by Steveice10** [comment]
While I did find and fix another issue related to sound mappings, I could not reproduce the one you are facing. Make sure you have the latest fixes.

**Comment by NovaBlastHD** [comment]
I have had this same issue. But this only has happened once in my while time using the lib.

**Comment by 0-x-2-2** [comment]
same
