### ISSUE TITLE
Could you add some NBT tag?

### ISSUE THREAD

**Issue by Xayanix** [GeyserMC/MCProtocolLib#236]
Hi,

i noticed that NBTTagEnd does not exist in your OpenNBT library. Could you add this?

**Comment by TheElectronWill** [comment]
Why do you need a TagEnd object ? TagEnd just means the end of a TagCompound, and does not follow the normal tag rules (ie it doesn't have a name despite being in a compoung, and its data size is 0).

**Comment by Steveice10** [comment]
As @TheElectronWill said, end tags are only meant to mark the end of compound tags, and thus are automatically handled by the library.
