### ISSUE TITLE
[Question] Confirm Transaction packet (clientbound)

### ISSUE THREAD

**Issue by Mareckoo01** [GeyserMC/MCProtocolLib#238]
Is [confirm transaction packet](http://wiki.vg/Protocol#Confirm_Transaction_.28clientbound.29) from server always not accepted?
Spigot & minecraft lan(integrated) server send it not accepted when it should be accepted(i think).
Is there a reason why it works like this?
I'm too lazy to search why it is like this, because it works, but i will ask anyway..

**S** = sent packet, **R** = received packet

//...Drop item code sending&receiving packets...
**S**-[Click window](http://wiki.vg/Protocol#Click_Window)(wID:0, s:36, drop stack)

**R**-[CTc](http://wiki.vg/Protocol#Confirm_Transaction_.28clientbound.29)(a:false)
**R**-[WI](http://wiki.vg/Protocol#Window_Items)(wID:0)
**R**-[SS](http://wiki.vg/Protocol#Set_Slot)(wID: 255, s:-1, i:null)
**R**-[SS](http://wiki.vg/Protocol#Set_Slot)(wID:0, s:36, i:null)

**S**-[CTs](http://wiki.vg/Protocol#Confirm_Transaction_.28serverbound.29)(a:false)
**S**-[PPL](http://wiki.vg/Protocol#Player_Position_And_Look_.28serverbound.29)
//..wait, repeat for whole inventory, player will drop everything.. so it works..

On wiki it says
>Packet from server indicating whether a request from the client was accepted, or whether there was a conflict (due to lag)

i don't think 0-14ms(on remote server) would be considered as lag...
(i switched from 1.11 to 1.12 just now and it is still the same)

**Comment by Steveice10** [comment]
I don't provide specific support with how to use the protocol here, only issues specific to the library. I would check the protocol documentation. Perhaps you are trying to perform an invalid action?

**Comment by Mareckoo01** [comment]
I don't think so, my code **works**...
I was asking **why** it works like this, [CTc](http://wiki.vg/Protocol#Confirm_Transaction_.28clientbound.29) packet should send accepted: false when there was a conflict...

log:

> **Sent**-ClientWindowActionPacket(windowId=0, slot=36, param=DROP_SELECTED_STACK, actionId=1, action=DROP_ITEM, clicked=com.github.steveice10.mc.protocol.data.game.entity.metadata.ItemStack@164dd)
**Received**-ServerSpawnObjectPacket(entityId=2759, uuid=5748c9ea-f42a-4c4e-bc91-4b9a0c15d15f, type=ITEM, x=-437.5, y=70.31999999284744, z=-70.5, pitch=0.0, yaw=-135.0, data=com.github.steveice10.mc.protocol.packet.ingame.server.entity.spawn.ServerSpawnObjectPacket$2@8065a60, motX=0.01525, motY=0.138125, motZ=0.298125)
**Received**-ServerEntityMetadataPacket(entityId=2759, metadata=[EntityMetadata(id=0, type=BYTE, value=0), EntityMetadata(id=1, type=INT, value=300), EntityMetadata(id=2, type=STRING, value=), EntityMetadata(id=3, type=BOOLEAN, value=false), EntityMetadata(id=4, type=BOOLEAN, value=false), EntityMetadata(id=5, type=BOOLEAN, value=false), EntityMetadata(id=6, type=ITEM, value=com.github.steveice10.mc.protocol.data.game.entity.metadata.ItemStack@164dd)])
**Received**-ServerEntityVelocityPacket(entityId=2759, motX=0.01525, motY=0.138125, motZ=0.298125)
**Received**-ServerConfirmTransactionPacket(windowId=0, actionId=1, accepted=false)
**Received**-ServerWindowItemsPacket(windowId=0, items=ItemStack[](length=46))
**Received**-ServerSetSlotPacket(windowId=255, slot=-1, item=null)
**Received**-ServerSetSlotPacket(windowId=0, slot=36, item=null)
**Received**-ServerKeepAlivePacket(id=46660041)
**Sent**-ClientConfirmTransactionPacket(windowId=0, actionId=1, accepted=false)
**Sent**-ClientPlayerPositionRotationPacket(x=-437.5, y=69.0, z=-70.5, yaw=0.0, pitch=0.0, onGround=true, pos=true, rot=true)
**Sent**-ClientKeepAlivePacket(id=46660041)
**Received**-ServerEntityVelocityPacket(entityId=2759, motX=0.0065, motY=0.0, motZ=0.126875)

Well this is not that important because it works..
