### ISSUE TITLE
Error when connecting to 1.11.2 with latest source

### ISSUE THREAD

**Issue by HossamMohsen7** [GeyserMC/MCProtocolLib#241]
Hello,
I want to use the latest source code to connect to a 1.11.2 server but it says:
` io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(2) + length(8) exceeds writerIndex(2): PooledUnsafeDirectByteBuf(ridx: 2, widx: 2, cap: 2)`

Can you help me??

**Comment by w-o-a-h** [comment]
the latest version is for 1.12 only

**Comment by 0-x-2-2** [comment]
the latest version is for 1.12 only here is the download for the last 1.11.2 version/commit https://github.com/w-o-a-h/MCProtocolLib/releases/tag/1.11.2-3
