### ISSUE TITLE
TAB

### ISSUE THREAD

**Issue by Dojdik** [GeyserMC/MCProtocolLib#242]
How to get player list by pressing tab in that client?

**Comment by ghost** [comment]
You need Player list packet http://wiki.vg/Protocol#Player_List_Item

**Comment by Dojdik** [comment]
Is it ServerPlayerListEntryPacket and why hasDisplayName=false?

**Comment by Mareckoo01** [comment]
If you want just player names you can do it the same way i did, make map with uuid, string and put player uuid and player name in it..

```java
//...
} else if(p instanceof ServerPlayerListEntryPacket){
	for(PlayerListEntry ple : ((ServerPlayerListEntryPacket) p).getEntries()){
		switch(((ServerPlayerListEntryPacket) p).getAction()){
		case ADD_PLAYER:
			bot.getNicks().put(ple.getProfile().getId(), ple.getProfile().getName());
			break;
		case REMOVE_PLAYER:
			bot.getNicks().remove(ple.getProfile().getId());
			break;
		case UPDATE_DISPLAY_NAME:
			break;
		case UPDATE_GAMEMODE:
			break;
		case UPDATE_LATENCY:
			break;
		}
	}
}
//...
```

**Comment by Dojdik** [comment]
What is property name, property value, property is signed and property signature
