### ISSUE TITLE
minecraftProtocol issue

### ISSUE THREAD

**Issue by 0-x-2-2** [GeyserMC/MCProtocolLib#244]
Trying to reuse a MinecraftProtocol instance after client gets disconnected then try to make another client using it disconnects you after you connect for "Connection closed" this is mostly a issue because if you want to reconnect a lot you get rate limited by mojang

**Comment by Steveice10** [comment]
You aren't supposed to reuse MinecraftProtocol instances.

**Comment by NovaBlastHD** [comment]
You can use their token and gameprofile.
