### ISSUE TITLE
How move bot please help me 

### ISSUE THREAD

**Issue by MALW3R3** [GeyserMC/MCProtocolLib#246]
Hello how i can move bot with mcprotocollib that's my code PlayerListener
https://pastebin.com/dC6dVs8g
And command for move bots
https://pastebin.com/bzXidZwr

Why they don't want to move?
Please help me i try do it since 5 days...

**Comment by Mareckoo01** [comment]
Look at wiki.vg [Player Position And Look](http://wiki.vg/Protocol#Player_Position_And_Look_.28clientbound.29)
_(you need to send teleport confirm packet and you should check if x/y/z/yaw/pitch is absolute or relative)_

**Comment by MALW3R3** [comment]
Can you help me how i can do it because this situation surpasses me and i don't know what i should do?
Can you give me example on this code that i send or can you give me your e-mail adress,skype or something?
@Mareckoo01

**Comment by phase** [comment]
```java
 public void run()
/*      */           {
/*  638 */             for (Player player : botty.SERVER.getOnlinePlayers())
/*      */             {
/*  640 */               Position pos = (Position)PlayerListenerManager.getPositionList().get(player);
/*      */              
/*  642 */               double x = pos.getX();
/*      */              
/*  644 */               for (int i = 0; i < 20; i++)
/*      */               {
/*  646 */                 x -= 0.15D;
/*      */                
/*  648 */                 player.getSession().send(new ClientPlayerPositionPacket(false, x, pos.getY(), pos.getZ()));
/*      */                
/*      */                 try
/*      */                 {
/*  652 */                   Thread.sleep(50L);
/*      */                 }
/*      */                 catch (Exception ex)
/*      */                 {
/*  656 */                   ex.printStackTrace();
/*      */                 }
/*      */               }
/*      */              
/*      */
/*  661 */               Position updatedPos = new Position((int)x, pos.getY(), pos.getZ());
/*      */              
/*  663 */               PlayerListenerManager.getPositionList().remove(player);
/*      */              
/*  665 */               PlayerListenerManager.getPositionList().put(player, updatedPos);
/*      */             }
/*      */            
          }
```

This is some confusing code. Are `Player`s instances of our bot? Add some debug statements to see what's happening in the code. Is the for loop running? Are you sure the packets are sending?

**Comment by Mareckoo01** [comment]
I store bot position in my Bot class,
when adding listener i give it bot instance,
Position is my class with x, y, z as double and yaw, pitch as float..
Code in my listener:
```Java
} else if(p instanceof ServerPlayerPositionRotationPacket){
	Position pos = bot.getPosition();
	pos.setX(((ServerPlayerPositionRotationPacket) p).getX());
	pos.setY(((ServerPlayerPositionRotationPacket) p).getY());
	pos.setZ(((ServerPlayerPositionRotationPacket) p).getZ());
	pos.setYaw(((ServerPlayerPositionRotationPacket) p).getYaw());
	pos.setPitch(((ServerPlayerPositionRotationPacket) p).getPitch());
	bot.getClient().getSession().send(new ClientTeleportConfirmPacket(((ServerPlayerPositionRotationPacket) p).getTeleportId()));
	bot.getClient().getSession().send(new ClientPlayerPositionRotationPacket(true, bot.getPosition().getX(), bot.getPosition().getY(), bot.getPosition().getZ(), bot.getPosition().getYaw(), bot.getPosition().getPitch()));
// if position was relative, the server will send absolute position if we sent position that was too far away from current absolute position on server
}
```
I'm not checking if the movement was relative or absolute so you should add that if you have problems...

**Comment by MALW3R3** [comment]
@phase @Mareckoo01 
Thank you very much for try help me !
@phase 
Yes Player = Client but i named that.
@Mareckoo01 

 there's error
bot.getClient().getSession().send(new ClientTeleportConfirmPacket(((ServerPlayerPositionRotationPacket) p).getTeleportId()));

p.getTeleportId(); <-- doesn't exist !

**Comment by Mareckoo01** [comment]
@MALW3R3 if you are using old MCProtocolLib version maybe it is changed and you need to figure it out by yourself, but in my code
```Java
Packet p = event.getPacket();
```
in your code
```Java
ServerPlayerPositionRotationPacket packet = (ServerPlayerPositionRotationPacket)event.getPacket();
```
so maybe use this?
```Java
event.getSession().send(new ClientTeleportConfirmPacket(packet.getTeleportId()));
```
If this works, you should clearly see in my previous reply what is the code doing... and you should learn java some more..

**Comment by MALW3R3** [comment]
@Mareckoo01 
Ok i found it in MCProtocllib 1.9.4 i will test it now

//I know that i must send ClientTeleportConfirmPacket but in my MCProtocollib this class exist but i can't send packet.getTeleportID() it doesn't exist what should i do now man ? 
Please help me because you know very good java

**Comment by HossamMohsen7** [comment]
You need to put this first in your code before you do getTeleportID:
`ServerPlayerPositionRotationPacket packet = (ServerPlayerPositionRotationPacket)event.getPacket();`

**Comment by MALW3R3** [comment]
@Mareckoo01 
@7osCraft
Okey, .getTeleportId() exist in mcprotocollib 1.9.4 but i do all in mcprotocollib 1.7.4 so it's any method to do this without this class (TeleportID)? ?

**Comment by HossamMohsen7** [comment]
Sorry but I don't know anything in the 1.7.4 protocol so it might be different

**Comment by MALW3R3** [comment]
@Mareckoo01 
@7osCraft 
@phase 
Okey i did it but my bots FLY they move in air how i can take thier fly off ?

**Comment by Mareckoo01** [comment]
@MALW3R3 you need to check if the block under bot is air and move bot down if it is..
but for that you need to have code for world/chunks/blocks so you can check the block under bot..

**Comment by MALW3R3** [comment]
@Mareckoo01 
Ok i will try do this. Is it possible to write proxy in mcprotocollib ? When i join to localhost it connect me to server ? In mcprotocollib i can write automated bots but can i be bot ? i join to localproxy and it connect me to server(i'm bot) and i can use packets from library ?

**Comment by Mareckoo01** [comment]
@MALW3R3 yes it should be possible, but you would have to write bot "server" that you could join..
server <-> bot
bot server <-> you
bot is acting as client and server at the same time
not only you have to have code to handle packets coming from server(bot is client) but you also have to have code to act as server and handle client(you)...

**Comment by MALW3R3** [comment]
@Mareckoo01 
Ok, i have proxy in java (Minecraft server) can you give me example code how to make me a player/Client ?

**Comment by 109C** [comment]
@MALW3R3 https://github.com/Steveice10/MCProtocolLib/blob/master/example/com/github/steveice10/mc/protocol/test/MinecraftProtocolTest.java#L141 is a good example on how to create a client.

Also, you're going to have to do some sort of [teleport](http://wiki.vg/Protocol#Teleport_Confirm) and [entity](http://wiki.vg/Protocol#Other_definitions) id mapping.

**Comment by Mareckoo01** [comment]
@MALW3R3 i made client only, so i can't..
learn more java and you can make it yourself...
and you could look at [this](https://github.com/Steveice10/MCProtocolLib/blob/master/example/com/github/steveice10/mc/protocol/test/MinecraftProtocolTest.java#L53)
