### ISSUE TITLE
MCProtocollib connect me as bot

### ISSUE THREAD

**Issue by MALW3R3** [GeyserMC/MCProtocolLib#247]
Hello i have localhost proxy who connect me to server how i can join as bot, i dont want automated bots but i want be bot and i want send packets from library ?

**Comment by MALW3R3** [comment]
@Steveice10

**Comment by MALW3R3** [comment]
@phase

**Comment by phase** [comment]
You have to write your own bot _using the library_. MCPL only deals with sending a receiving packets, **you** have to write the code that controls what your bot does when it receives/sends them.

**Comment by MALW3R3** [comment]
@phase 
Ye i have bots they perfect join and do everything what i want when reveices/sends packets.
    MinecraftProtocol protocol = new MinecraftProtocol(this.name);
        String ip = "example.com";
        int porcik = 25565;
	    Client client = new Client(ip, porcik, protocol, new TcpSessionFactory());
	    Player player = new Player(this.name, client);
		Connection.registerDefaultListeners(player);
   	      player.getSession().connect(); <-- it connect BOT ! But i want connect me as BOT how ?
How i can add me to Connection.registerDefaultListeners and play as bot with protocollib packets ?

Do you understand what i mean ?

**Comment by Mareckoo01** [comment]
@MALW3R3 yes, but this is packet library so you have to use it to make it do what you want...

**Comment by MALW3R3** [comment]
@Mareckoo01 
But i can't find any example how to do it. Do you have any ?

**Comment by MALW3R3** [comment]
@phase 
Ok, probably i have own bot, i addlistener to him to receive/send packets but i must do getSession().connect and it's unvailable to connect me as bot !

**Comment by 109C** [comment]
@MALW3R3 This snippet might help.

```
        MinecraftProtocol protocol = new MinecraftProtocol(USERNAME);
        Client client = new Client(REMOTE_SERVER, REMOTE_PORT, protocol, new TcpSessionFactory());
        
        Server server = new Server(LOCAL_SERVER, LOCAL_PORT, MinecraftProtocol.class, new TcpSessionFactory());
        server.bind(true);
        
        server.addListener(new ServerAdapter(){
            @Override
            public void sessionAdded(SessionAddedEvent event){
                Session in = event.getSession();
                
                // Don't block this thread. (Clients would not connect otherwise.)
                new Thread(() -> {
                    
                    // Wait for pings to timeout or sessions to connect.
                    while(((MinecraftProtocol)in.getPacketProtocol()).getSubProtocol() != SubProtocol.GAME){
                        if(!in.isConnected()) return;
                        try {Thread.sleep(1000);}catch(InterruptedException ex){}
                    }
                    
                    // Relay all the packets we get from the client to server.
                    in.addListener(new SessionAdapter(){
                        @Override
                        public void packetReceived(PacketReceivedEvent event){
                            Packet p = event.getPacket();
                            if(shouldSend(p) && canSend(client.getSession())){
                                client.getSession().send(p);
                                if(p instanceof ClientChatPacket){
                                    client.getSession().send(new ClientChatPacket("Injected chat packet!"));
                                }
                            }
                        }
                    });
                    // And vice versa.
                    client.getSession().addListener(new SessionAdapter(){
                        @Override
                        public void packetReceived(PacketReceivedEvent event){
                            if(shouldSend(event.getPacket()) && canSend(in)){
                                in.send(event.getPacket());
                            }
                        }
                    });
                    client.getSession().connect(true);
                }).start();
            }
        });
    }
    private static boolean canSend(Session s){
        MinecraftProtocol mp = (MinecraftProtocol)s.getPacketProtocol();
        return mp.getSubProtocol() == SubProtocol.GAME;
    }
    private static boolean shouldSend(Packet p){
        return !(p instanceof LoginSetCompressionPacket || p instanceof LoginSuccessPacket);
    }
```
</details>

**Comment by MALW3R3** [comment]
@109C 
Thank you for reply. But that code don't work for me do you test it (server don't start) ? But i think client.getSession().connect connect BOT it can't connect me

**Comment by 109C** [comment]
@MALW3R3
That's odd, it worked on my machine. Perhaps if you tried the complete version I ran it might work. https://gist.github.com/109C/b75b068706a014ce8f6cbee28c92c83e

> But i think client.getSession().connect connect BOT it can't connect me

You're right, it can't. But by connecting to the bot it *seems* like you did.

**Comment by MALW3R3** [comment]
@109C 
"You're right, it can't. But by connecting to the bot it seems like you did."

How can i connect to BOT ?

**Comment by 109C** [comment]
@MALW3R3 By connecting with the vanilla client to localhost:25566.

**Comment by MALW3R3** [comment]
@109C 
Do you have example code that i can join to any minecraft server using mcprotocollib ? And add me to listen packets ?

**Comment by 0-x-2-2** [comment]
HE sent you the code you are just too dumb to use it fuck off and read the examples.

**Comment by MALW3R3** [comment]
@w-o-a-h 
dafq do you understand that this code connect dumb bot not me ?

**Comment by phase** [comment]
[There's an example in the repo.](https://github.com/Steveice10/MCProtocolLib/blob/master/example/com/github/steveice10/mc/protocol/test/MinecraftProtocolTest.java) What is it you're trying to accomplish? "connect me as bot" makes zero sense. "Bots" are just clients that aren't user controlled, and are usually programmed to do certain tasks. When you use this library to connect to a server, you're making a bot (could be used for a custom client but we're not doing that here).You need to describe what the problem you're having is.

**Comment by Mareckoo01** [comment]
@phase he is trying to make bot that connects to remote server but also has integrated server so he can connect to the bot's integrated server with standard minecraft client and he probably wants to send packets from bot that the bot's server receives, so "he can control it"..
so something like mc proxy?

remote server -> bot
bot's server -> standard mc client(him)

standard mc client(him) -> bot's server
bot -> remote server

**Comment by phase** [comment]
Well that's ridiculously complicated and well out if the realm of his abilities as a programmer. He'd have to setup an entirely different protocol with Netty. I've done it before but it's very advanced.

**Comment by 109C** [comment]
@phase Yes, it's probably too complicated for him.
No, there's no need for netty. McProtocolLib is perfectly fine, and an [extremely simple proxy](https://gist.github.com/109C/b75b068706a014ce8f6cbee28c92c83e) would be <100 lines.

**Comment by Mareckoo01** [comment]
This is probably what he wants https://gist.github.com/Mareckoo01/2c1a014fa89767430a8899d72e2f3c32
With this, it is possible to connect more than 1 client to bot's server and "control" the bot connected to remote server...

**Comment by 0-x-2-2** [comment]
Oh so like a proxy? yeah i have done that before.

**Comment by 109C** [comment]
@w-o-a-h Haven't we all.

**Comment by MALW3R3** [comment]
@phase @Mareckoo01 @109C 
Ye i want connect bot to any server and i want connect to him session, and walk ,mine and when i use .sendPacket() it will connect packet as me

**Comment by MALW3R3** [comment]
@Mareckoo01 
Can you test your proxy that work good for you ? Because i have errors.
@109C 
Idk how fix it but Failed to login: Acces token can not be null or empty i think it's proxy only for premium

**Comment by 0-x-2-2** [comment]
read the code its 1 line to change

**Comment by Mareckoo01** [comment]
@MALW3R3 it works fine on latest MCProtocolLib version, what version are you using?

**Comment by MALW3R3** [comment]
@Mareckoo01 
I join to this localhost proxy server and in terminal "Exception in thread-9" java.lang.NullPointerException
at org.spacehq.mc.protocol.ServerListenerUserAuthTask.run<ServerListener.java:177>


Thank you very much for help

**Comment by 109C** [comment]
@MALW3R3 You're using an old build of MCProtocolLib, so we can't tell exactly what's causing the null pointer. It does seem auth related thought.

**Comment by MALW3R3** [comment]
@109C 
@Mareckoo01 
I added some code from MinecraftProtocolTest and it's work, very slow connect but work (109C proxy) i will test @Mareckoo01 right now.
But there's a problem i can't mine and play like a normal player i must add Block classes ye ? it's hard to do proxy like for normal player for play ?

**Comment by Mareckoo01** [comment]
@MALW3R3 i made video how it should work https://youtu.be/0jUW7uzX9yg
_(when you reconnect to bot, i recommend teleporting to yourself, like /tpa YourName and /tpaccept or /spawn or /home that is far away and that should fix position mismatch between you and server)_

**Comment by MALW3R3** [comment]
@Mareckoo01 @109C 
You are awesome guys, thank you very much but i have one problem with that !
I can join only one session how i can do it to join more than one minecraft session on other nicknames?

I create USERNAME = GenerateRandomString();
but it always connect me to that same nickname and on proxy can play one person?

**Comment by MALW3R3** [comment]
@Mareckoo01 @109C 
I can't join to multiplayer server only on localhost because there's a bad
io.netty.hanlder.codec
Unregistered outgoing packet class: org.spacehq.protocol.packet.login.server.LoginDisconnectPacket

Please fix it and everythink will work very good // 109C proxy

@Mareckoo01 Your proxy is very good but i must join on 2 minecrafts one is Logging in... and second only connect can you fix that i could join to any server with opened one minecraft?

**Comment by Mareckoo01** [comment]
@MALW3R3 you can use just 1 or more minecraft clients... in video i used 2 clients, 3. was just connected to server so you can look at bot... since you are using old MCProtocolLib version you need to change some things.. maybe this will work?
_(if MinecraftConstants.VERIFY_USERS_KEY doesn't exist)_
**change** MinecraftConstants.VERIFY_USERS_KEY **to** ProtocolConstants.VERIFY_USERS_KEY
_(if ClientTeleportConfirmPacket doesn't exist)_
**remove** ClientTeleportConfirmPacket

don't copy imports from my code, import everything by yourself

bot will connect to remote server when you connect to bot's integrated server..
so if you want to connect bot to remote server, you need to connect to bot's integrated server...

**Comment by MALW3R3** [comment]
@Mareckoo01 @109C 
1.How to fix io.netty.hanlder.codec
Unregistered outgoing packet class: org.spacehq.protocol.packet.login.server.LoginDisconnectPacket
i can't join to serveral servers
It's possible that i join to this localhost proxy i will be on empty world and if i say on chat ipserver:port it will connect me to this ? and later if  i write other serverip:port it will connect me to next?

**Comment by MALW3R3** [comment]
@Mareckoo01 @109C 
I found a bad i fixed it, but when i try to do 
    @Override
            public void loggedIn(Session session) {
                session.send(new ServerJoinGamePacket(0, false, GameMode.SURVIVAL, 0, PEACEFUL, 100, DEFAULT, false));
            }
It doesn't connect me to localhost with empty world why ? I want connect to localhost:25565 and i want be on empty world and from there connect to any server how ?

**Comment by Mareckoo01** [comment]
@MALW3R3 you need to do it in order http://wiki.vg/Protocol_FAQ#What.27s_the_normal_login_sequence_for_a_client.3F

**Comment by MALW3R3** [comment]
@Mareckoo01 
Can you do it if i will pay you ?

**Comment by MALW3R3** [comment]
@Mareckoo01 @109C @phase @w-o-a-h @Steveice10 
Guys please help me fix it and all will be good i would close thread.

This is my code, problem is on screenshot on some servers that problem exist but no on all
SCREENSHOT: https://prnt.sc/g0sevi
 CODE: https://pastebin.com/Zu8N33ep

In @Mareckoo01 proxy it bug doesn't exist but exist other problem more advanced (of course clear proxy from you work very good :D). But how fix it there and that's all ?
