### ISSUE TITLE
Packet Not Fully Read

### ISSUE THREAD

**Issue by c-wolfe** [GeyserMC/MCProtocolLib#248]
I'm currently working on creating a bot, and I ran into a little issue when I try to connect to TheArchon. I get the following error (sometimes I get other packets that aren't read properly either) https://hastebin.com/ujilokadiv.lua

**Comment by Steveice10** [comment]
MCProtocolLib is currently written for the 1.12 protocol, and unless I'm mistaken, TheArchon seems to be a 1.11 server.

**Comment by c-wolfe** [comment]
1.8.8-1.10.2. I changed the MC version in MinecraftConstants to 1.10.2. Is
there any download (or specific commit) for it in an earlier version that
supports 1.10.2~?

**Comment by Steveice10** [comment]
If you go back in the commit history, you should be able to find the initial 1.11 support commit. The one before that is what you want.
