### ISSUE TITLE
Using 1.8

### ISSUE THREAD

**Issue by GramDev1** [GeyserMC/MCProtocolLib#249]
hi,
I understand only the latest MC version is tracked, but a 1.8 jar would be extremely helpful for me. Could someone provide this?

**Comment by Steveice10** [comment]
You could checkout a 1.8 commit and build it yourself.

**Comment by GramDev1** [comment]
@Steveice10 could you reference me one please

**Comment by Steveice10** [comment]
https://github.com/Steveice10/MCProtocolLib/commit/4ccf753002a9666a259649061afffa785c0731d6
