### ISSUE TITLE
Proxy not fast enough?

### ISSUE THREAD

**Issue by ghost** [GeyserMC/MCProtocolLib#251]
As the title! I have like 1k of socks5 proxies with less than 1 second timeout and still the first bot joining is fast but then it gets slow! I've been using another bot called deathbot and they are just connecting instant and not slower after 3-4 connections, is there a way on how to fix this?

**Comment by Steveice10** [comment]
I don't think your proxy/connection speed is an MCProtocolLib issue.

**Comment by 0-x-2-2** [comment]
I can use a slow proxy with the normal mc client why cant i use it with MCProtocolLib

**Comment by Steveice10** [comment]
You can. If it's a slow proxy though, the connection will obviously also be slow.
