### ISSUE TITLE
TabList

### ISSUE THREAD

**Issue by MALW3R3** [GeyserMC/MCProtocolLib#253]
Hello,
how can i create own tablist on mcprotocollib proxy when someone look at TAB he will see "asdasdasdasdasd" and no one more ?

Or How can i download server tablist and add my words on that ?

@Mareckoo01 @phase @Steveice10 @109C

**Comment by Mareckoo01** [comment]
If you want to store TAB data from server look at #242 
if you want to send TAB data, you need to send ServerPlayerListEntryPacket to connected player(s), it would look something like this
```Java
PlayerListEntry ple[] = {
		new PlayerListEntry(new GameProfile(UUID.randomUUID(), "T1"), GameMode.SURVIVAL, 0, Message.fromString("Some text")),
		new PlayerListEntry(new GameProfile(UUID.randomUUID(), "T2"), GameMode.SURVIVAL, 0, Message.fromString("Some text with §2color")),
		new PlayerListEntry(new GameProfile(UUID.randomUUID(), "T3"), GameMode.SURVIVAL, 0, Message.fromString("Some text with §bcolor"))};
ServerPlayerListEntryPacket packet = new ServerPlayerListEntryPacket(PlayerListEntryAction.ADD_PLAYER, ple);
for(Session connected : connectedClients){
	connected.send(packet);
}
```

**Comment by 0-x-2-2** [comment]
@MALW3R3 cache the servers tablist
