### ISSUE TITLE
I do not want to load the world

### ISSUE THREAD

**Issue by AdesSki666** [GeyserMC/MCProtocolLib#254]
enter to proxy server that loads the world in infinity. I do not know how to fix it.

**Comment by Steveice10** [comment]
I'm not sure what that's supposed to mean, but this section is mainly for library issues, not usage support requests.

**Comment by AdesSki666** [comment]
When i come in on a proxy server it loads my map in infinity

**Comment by 0-x-2-2** [comment]
what

**Comment by 109C** [comment]
@w-o-a-h When he joins proxy server it gets stuck loading the map (?)
What I suspect is going wrong is that he isn't sending a clientbound position/rotation packet, so the client is stuck on the loading screen.

**Comment by AdesSki666** [comment]
not loading world. how to repair problem?. give me minecraftprotocol
loading world script please.

2017-08-10 9:17 GMT+02:00 109C <notifications@github.com>:

**Comment by phase** [comment]
> give me minecraftprotocol loading world script please.

That doesn't exist. The server is sending you chunk packets because _that's what the server does_. You can ignore them if you want to.

**Comment by AdesSki666** [comment]
Please help me. my class: https://pastebin.com/rP2ZkPH1

**Comment by Mareckoo01** [comment]
This library is used to communicate between client and server, you need to make everything else.. Take a look at [wiki.vg](http://wiki.vg)
