### ISSUE TITLE
ServerChatPacket returning "chat.type.text" instead of chat message

### ISSUE THREAD

**Issue by stenocyb** [GeyserMC/MCProtocolLib#255]
Hello, whenever I receive a chat message from the server, "chat.type.text" is returned by `packet.getMessage().getFullText();`

However, this only happens on my local server which I've downloaded from the official minecraft website. I tested this with the latest 1.8 version and 1.12.1 version of the server, but in both cases it returns the same string. I've also tested this with the latest version of your library but it is still the same. I think it might be related to this: [https://gist.github.com/Dinnerbone/5631634](https://gist.github.com/Dinnerbone/5631634)

On other, public servers, which use bungeecord for example, the problem doesn't appear. Instead, I either retrieve the message successfully or the message is empty.

Here's my code [https://github.com/xTACTIXzZ/Hydrazine/blob/master/src/com/github/hydrazine/module/builtin/ChatReaderModule.java#L250](https://github.com/xTACTIXzZ/Hydrazine/blob/master/src/com/github/hydrazine/module/builtin/ChatReaderModule.java#L250)

**Comment by Mareckoo01** [comment]
Yes it is changed, http://wiki.vg/Chat#Processing_chat
I do it like so(very simle, not that good):
```Java
Packet p = packetreceivedevent.getPacket();
//System.out.println("R-" + p);
if(p instanceof ServerChatPacket){
	if(((ServerChatPacket) p).getMessage() instanceof TranslationMessage){
		//TODO make it better!
		TranslationMessage tm = (TranslationMessage) ((ServerChatPacket) p).getMessage();
		String mess = "";
		for(Message m : tm.getExtra()){
			mess = mess + " " + m.getFullText();
		}
		for(Message m : tm.getTranslationParams()){
			mess = mess + " " + m.getFullText();
		}
		bot.getChat().receivedMessage(mess);
	} else {
		bot.getChat().receivedMessage(((ServerChatPacket) p).getMessage().getFullText());
	}
}
```

**Comment by Steveice10** [comment]
The idea is that you choose the template string for your language that corresponds to the message text, i.e. "chat.type.text", and pass it to String.format with TranslationMessage.getTranslationParams() as the formatting parameters.

**Comment by stenocyb** [comment]
Thank you two for the quick answer :)
