### ISSUE TITLE
Server won't connect me by proxy

### ISSUE THREAD

**Issue by MALW3R3** [GeyserMC/MCProtocolLib#265]
Hello, i have server on mcprotocollib who connect to server - without proxy work good.

` server = new Server(LOCAL_SERVER, randomport, MinecraftProtocol.class, new TcpSessionFactory());

	    
	              server.setGlobalFlag(MinecraftConstants.VERIFY_USERS_KEY, false);
	             server.setGlobalFlag(MinecraftConstants.SERVER_COMPRESSION_THRESHOLD, 100);
	              server.setGlobalFlag(MinecraftConstants.SERVER_INFO_BUILDER_KEY, new ServerInfoBuilder() {
	            	
	                  public ServerStatusInfo buildInfo(Session session) {
	                      return new ServerStatusInfo(new VersionInfo(MinecraftConstants.GAME_VERSION, MinecraftConstants.PROTOCOL_VERSION),
	                              new PlayerInfo(100, 0, new GameProfile[0]), new TextMessage("Server"), null);
	                  }
	              });

	              server.setGlobalFlag(MinecraftConstants.SERVER_LOGIN_HANDLER_KEY, new ServerLoginHandler() {
	                  @Override
	                  public void loggedIn(Session session) {

	              

        			
	                  }
	              });
	        server.bind(true);`

But when i try to connect me by proxy like that

   Client client = new Client(hostname, port, protocol, new TcpSessionFactory(Proxy.getRandomProxy()));
   client.getSession().connect(true);
That don't work, so how i can connect me with proxy

**Comment by Steveice10** [comment]
Have you tried with a proxy that is verified to work, perhaps by trying it with the official client?

**Comment by MALW3R3** [comment]
Yes, because i have list and automated bots join with that proxy. When i try join by that localhost server it only work with my IP adress.

**Comment by Steveice10** [comment]
Ah, the problem is that you're connecting to a server on localhost. The proxy won't know how to reach it.

**Comment by PoLsKiPaLaCz** [comment]
@MALW3R3 would you help me getting proxy from arraylist
