### ISSUE TITLE
ServerMapDataPacket , map in slot

### ISSUE THREAD

**Issue by prysiu** [GeyserMC/MCProtocolLib#266]
The map is shown only if it lies in the left hand, if it lies in the other slots of the inventory, then it simply does not show. Maybe I need some kind of packet, but I do not know which one, help
![2017-08-30_03 40 41](https://user-images.githubusercontent.com/25775360/29850376-e81b73dc-8d35-11e7-8fa0-5e24fd8f9fb1.png)
![2017-08-30_03 44 19](https://user-images.githubusercontent.com/25775360/29850377-e81cd7e0-8d35-11e7-9ba4-10b8382b4d0a.png)``
`ServerMapDataPacket t = new ServerMapDataPacket(0, (byte)1, false, mp , md);
ItemStack d = new ItemStack(358) ;
 s.send(t);
s.send(new ServerSetSlotPacket(wt.ordinal(), 36, new ItemStack(358)));`

**Comment by Steveice10** [comment]
This section is for library issues, not protocol help.

**Comment by prysiu** [comment]
This is library issues
That it is necessary to make that it was possible to see a picture on a card (it is visible only from the left hand)

**Comment by Steveice10** [comment]
It is not an issue with the library, it is likely an issue with how you are using the protocol, which is not what this section is for.

**Comment by Mareckoo01** [comment]
@prysiu did you finish [login sequence](http://wiki.vg/Protocol_FAQ#What.27s_the_normal_login_sequence_for_a_client.3F)?
(Steps 1. to 8. are done by the library)

**Comment by prysiu** [comment]
@Mareckoo01 can u help me? 
I can pay fot that

**Comment by Mareckoo01** [comment]
@prysiu all you need to do is read and try again... And i haven't looked at making a working server but my guess is that you need to finish login sequence as i said before.

**Comment by 0-x-2-2** [comment]
@Mareckoo01 1-8 and 9 is kinda done by the library.
