### ISSUE TITLE
Bot move

### ISSUE THREAD

**Issue by Dojdik** [GeyserMC/MCProtocolLib#271]
How to make bot move 1.8?
I trying
`				if (event.getPacket() instanceof ServerPlayerPositionRotationPacket)
				{
					ServerPlayerPositionRotationPacket packet = (ServerPlayerPositionRotationPacket) event.getPacket();
					event.getSession().send(new ClientPlayerPositionRotationPacket(true, packet.getX(), packet.getY(), packet.getZ(), packet.getPitch(), packet.getYaw()));
					event.getSession().send(new ClientPlayerPositionPacket(true, packet.getX() + 0.5d, packet.getY(), packet.getZ()));
					try {
						Thread.sleep(1000);
					} catch (InterruptedException e) {
						// TODO Auto-generated catch block
						e.printStackTrace();
					}
			
				}`

But nothing

**Comment by Steveice10** [comment]
I don't provide support for issues using the protocol, only bugs within the library itself. https://wiki.vg/ is already a very good source for information on how to use the protocol. Plus, I don't support old versions either, only the latest.
