### ISSUE TITLE
OutOfBoundsException triggers disconnect

### ISSUE THREAD

**Issue by Kevin-Codes** [GeyserMC/MCProtocolLib#274]
OutOfBoundsException gets triggered on servers such as Hypixel (no clue why this occures) however a corrilation between it happens when new chunks gets loaded in meaning that if a chunks loaded the bot will be forced to d/c

**Comment by Steveice10** [comment]
Is this with a build from the latest source, and is the exception originating from MCProtocolLib or your code? Disconnecting on exception is not a bug.

**Comment by Kevin-Codes** [comment]
Yeah it's the latest build, probably more server-side but normally minecraft just prints a stacktrack of the exception instead of disconnecting. You can try it urself with a normal minecraft client and logging into mc.hypixel.net then loading in a chunk if it would be a better explanation of what it is. But then again I believe the exception is probaly due to the servers multicompatibilty and this exception won't be thrown on most servers it won't matter.

**Comment by Steveice10** [comment]
Could you post the stack trace here?

**Comment by Kevin-Codes** [comment]
I can't get on my computer rn but I'll post it ASAP.

**Comment by Mareckoo01** [comment]
Are you sure it is not your code causing this problem? I used [this](https://gist.github.com/Mareckoo01/2c1a014fa89767430a8899d72e2f3c32) and added logging sent & received packets to text file and it had no problem...
(line 72, line 81)

**Comment by Kevin-Codes** [comment]
To reiterate this only occures on mc.hypixel.net
https://gist.github.com/Kevin-Codes/e96482223c6c232021c350357e022a9b
Stacktrace:
https://gist.github.com/Kevin-Codes/80bba5dc0186483967b7bb066a8ef36e

**Comment by 0-x-2-2** [comment]
OutOfBoundsExceptions happen on the vanilla client on hypixel because of there protocol hack but get catched by the vanilla client MCProtocolLib should do the same.

**Comment by Steveice10** [comment]
I just got this from idling after connecting to the server using 1.12.1, so I'm inclined to say this is a server fault rather than an MCProtocolLib issue.

![screenshot](http://i.imgur.com/DExC5DF.png)
