### ISSUE TITLE
Visible server for linux

### ISSUE THREAD

**Issue by MALW3R3** [GeyserMC/MCProtocolLib#276]
My localhost proxy server is only visible for me if i add it on minecraft server list.
But when i upload it on my virtual private server i don't see it

vpsip:port -> is not visible why? How to unlock it ?

**Comment by MALW3R3** [comment]
@Steveice10 
netstat -a show me that port 25565 (my Server) is TIME_WAIT no LISTEN how to change it to be visible for other people ?

**Comment by Steveice10** [comment]
I don't quite understand what you're doing, but I don't provide support for your personal networking issues.

**Comment by MALW3R3** [comment]
Look i create local proxy (Server) in mcprotocollib. I upload it on my linux server (VPS) java -jar server.jar and when i add it on my minecraft it doesn't exist(port isn't open).

**Comment by MALW3R3** [comment]
my SERVER created in mcprotocollib is not visible from other people (only visible for localhost)

**Comment by 0-x-2-2** [comment]
google will help you this is NOT a issue.

**Comment by MALW3R3** [comment]
@w-o-a-h 
So when you write that server i work for other people when you upload it on virtual private server ?

**Comment by MALW3R3** [comment]
@Steveice10 
Maybe it's my BAD look at code. IpAdressMyVirtualPrivateServer:25565 my minecraft don't see that server. But when i enable it on my localhost computer my minecraft see that server.

`   Server server = new Server(HOST, PORT, MinecraftProtocol.class, new TcpSessionFactory());
            server.setGlobalFlag(MinecraftConstants.AUTH_PROXY_KEY, AUTH_PROXY);
            server.setGlobalFlag(MinecraftConstants.VERIFY_USERS_KEY, VERIFY_USERS);
            server.setGlobalFlag(MinecraftConstants.SERVER_INFO_BUILDER_KEY, new ServerInfoBuilder() {
                @Override
                public ServerStatusInfo buildInfo(Session session) {
                    return new ServerStatusInfo(new VersionInfo(MinecraftConstants.GAME_VERSION, MinecraftConstants.PROTOCOL_VERSION), new PlayerInfo(100, 0, new GameProfile[0]), new TextMessage("Hello world!"), null);
                }
            });

            server.setGlobalFlag(MinecraftConstants.SERVER_LOGIN_HANDLER_KEY, new ServerLoginHandler() {
                @Override
                public void loggedIn(Session session) {
                    session.send(new ServerJoinGamePacket(0, false, GameMode.SURVIVAL, 0, Difficulty.PEACEFUL, 10, WorldType.DEFAULT, false));
                }
            });

            server.setGlobalFlag(MinecraftConstants.SERVER_COMPRESSION_THRESHOLD, 100);
            server.addListener(new ServerAdapter() {
                public void sessionAdded(SessionAddedEvent event) {
                    event.getSession().addListener(new SessionAdapter() {
                        @Override
                        public void packetReceived(PacketReceivedEvent event) {
                            if(event.getPacket() instanceof ClientChatPacket) {
                                ClientChatPacket packet = event.getPacket();
                                GameProfile profile = event.getSession().getFlag(MinecraftConstants.PROFILE_KEY);
                                System.out.println(profile.getName() + ": " + packet.getMessage());
                                Message msg = new TextMessage("Hello, ").setStyle(new MessageStyle().setColor(ChatColor.GREEN));
                                Message name = new TextMessage(profile.getName()).setStyle(new MessageStyle().setColor(ChatColor.AQUA).addFormat(ChatFormat.UNDERLINED));
                                Message end = new TextMessage("!");
                                msg.addExtra(name);
                                msg.addExtra(end);
                                event.getSession().send(new ServerChatPacket(msg));
                            }
                        }
                    });
                }`

**Comment by Steveice10** [comment]
Did you set HOST to "0.0.0.0" instead of "127.0.0.1"?

**Comment by MALW3R3** [comment]
@Steveice10 
Yes, i bought third Virtual Private Server and on all my minecraft don't see that Server.
`    	server = new Server("0.0.0.0", 25566, MinecraftProtocol.class, new TcpSessionFactory());
`
Debug say me that Server is Listening but it's only visible for 127.0.0.1

**Comment by Steveice10** [comment]
Make sure you're connecting to port 25566, and that port 25566 is actually open on your server. It could be blocked by an installed firewall or rules specific to your host.

**Comment by MALW3R3** [comment]
I'm sorry i checked now 0.0.0. and it work very well. 
It can't be "localhost" or "127.0.0.1" just "0.0.0.0".

Thank you.
