### ISSUE TITLE
Title/Subtitile

### ISSUE THREAD

**Issue by speedAccount** [GeyserMC/MCProtocolLib#278]
Hello, how to display title / subtitile on screen?
@Steveice10 
@phase

**Comment by Lennyss** [comment]
ServerTitlePacket

**Comment by speedAccount** [comment]
@Lennyss 
Give code, please.

**Comment by Lennyss** [comment]
use brain lol? 
session.send(new ServerTitlePacket(...));
and place in constructor what you need.

**Comment by speedAccount** [comment]
@Lennyss 
session.send(new ServerTitlePacket(TITLE, "test"));
work?

**Comment by Lennyss** [comment]
if boolean is equals to String and static ? TITLE is equals to string or Message, yes should be work but....

**Comment by Steveice10** [comment]
I do not provide support on how to use the protocol. http://wiki.vg/ is a good resource for information on that.
