### ISSUE TITLE
Move player

### ISSUE THREAD

**Issue by speedAccount** [GeyserMC/MCProtocolLib#279]
Hello, i'm have a question. How to move player/bot? I need a fragment of code

**Comment by speedAccount** [comment]
@Steveice10 
@phase

**Comment by Lennyss** [comment]
teleport player where you need
so if you need to move player from x:0 z:0 to x:1 z:0 you need to teleport player f.e 10 times like this
            client.getSession().send(new ClientPlayerPositionRotationPacket(false, pos.x+0.1, pos.y, pos.z, yaw, pitch));
where pos i your object with saved position(yes you need to manualy save bot position), and you need a little math skill nothink more

**Comment by Steveice10** [comment]
I do not provide support on how to use the protocol. http://wiki.vg/ is a good resource for information on that.
