### ISSUE TITLE
Invalid packet id: 0/3 while connecting bots to server

### ISSUE THREAD

**Issue by Lennyss** [GeyserMC/MCProtocolLib#280]
So i when i connect bots to server i have this error
io.netty.handler.codec.DecoderException: java.lang.IllegalArgumentException: Invalid packet id: 0
or 
io.netty.handler.codec.DecoderException: java.lang.IllegalArgumentException: Invalid packet id: 3
i use 1.8.8 version BUT when i try to  use newest i have the same problem so how can i fix this or somethink?

**Comment by Steveice10** [comment]
Can you share your code?

**Comment by Lennyss** [comment]
i will past fragments
creating new Bot
        final Client c = new Client(host, port, new MinecraftProtocol(string), new TcpSessionFactory(Proxy.NO_PROXY));
        final Bot bot = new Bot(this, string, c);
proxy packet from client to bot
https://hastebin.com/cuhojolapo.cs
and from bot to client:
        if (((MinecraftProtocol) bot.getClient().getPacketProtocol()).getSubProtocol() == SubProtocol.GAME) {
            player.lastPacket = packet;
            player.getSession().send(packet);
        }
and i don't know why i have this error sometimes, but when i restart server i can join to server, but later i have same problem

**Comment by Steveice10** [comment]
Yeah... that doesn't really tell me enough to figure out what's going on. Something is causing packets to be received before they are registered by the switch to the appropriate protocol mode.

**Comment by Lennyss** [comment]
ok so look in this hastebin:
https://hastebin.com/gemexekexa.cs
i look in code and packet id 3 is a compresion packet, and while i execute connectTo() few times 
eventually bots will connect to server :)

**Comment by Steveice10** [comment]
Based on that code snippet, I would guess that in the first listener, you are receiving ingame packets from the player and sending them through your Client instance to the server before it has reached ingame mode.

**Comment by Lennyss** [comment]
@Steveice10  my metod canProxy() check bot state :) 
and i check in which state my bot (http://scr.hu/1det/o79gg)

and second question how can i ping server? i try 
send(new HandshakePacket(47, args[0], 25565, HandshakeIntent.STATUS));
but i want to check status before connect to server :)

**Comment by Steveice10** [comment]
A ping example can be found here: https://github.com/Steveice10/MCProtocolLib/blob/master/example/com/github/steveice10/mc/protocol/test/MinecraftProtocolTest.java#L109

**Comment by Lennyss** [comment]
@Steveice10  can't i send HandshakePacket? i must login client and later dc?  so do you know what is problem with this invalid packet error?

**Comment by Steveice10** [comment]
Yes, you can't transition from a status query to a login; they have to be separate connections. That's a Minecraft protocol limitation.

As for the invalid packet error, you should probably be checking for the INGAME state, not LOGIN.

**Comment by Lennyss** [comment]
can you tell me what i should change in my code? cuz i don't know where i make a mistake :/ 

Edit. thanks for ping method :)

**Comment by Steveice10** [comment]
If canProxy is checking for the LOGIN sub-protocol, try changing it to check for INGAME. I'm a bit limited on what I can suggest aside from that as long as I'm working off of snippets.

**Comment by Steveice10** [comment]
Essentially, if a proxy is your goal, you want to only be taking packets received from an ingame client and sending them using an ingame client.

**Comment by Lennyss** [comment]
I think checking this is work, but i will test later, can you tell me last think, why 
when i sending message only first line is colored? (i use your Message class)

**Comment by Steveice10** [comment]
Could you post the line(s) you use to create the Message instance?

**Comment by Lennyss** [comment]
session.send(new ServerChatPacket(Message.fromString(message)));
before this i translatecolorCodes in message

Close cuz you help me with my main problem :)

**Comment by Steveice10** [comment]
I assume message is a JSON string with formatting information. Perhaps it has to do with how you create the formatted JSON string with your translatecolorCodes function? Could you post the contents of "message"?

**Comment by Lennyss** [comment]
My problem is when i try to send reason to client why bot is disconnected:
        if (packet instanceof ServerDisconnectPacket) {
            ServerDisconnectPacket p = (ServerDisconnectPacket) packet;
            send(player.getSession(), "Disconnected: " + p.getReason().getFullText());
            player.disconnect();
            return;
        }
where send()
public void send(Session ses,String s){
//translate colors code
session.send(new ServerChatPacket(Message.fromString(s)));
}

**Comment by Lennyss** [comment]
ok i will check this but
i have still this problem
http://scr.hu/1det/h39a1 but now i check if client has GAME subProtocol

**Comment by Steveice10** [comment]
Why does it say "LOGIN" if it's ingame?

**Comment by Lennyss** [comment]
i printf bot state not player state, cuz i send bot to server and later proxy game packets from bot to client and from client to bot

**Comment by Steveice10** [comment]
Both bot and player state have to be INGAME.

**Comment by Lennyss** [comment]
Ok working, and to your answer:
"I need to know how you are formatting the message in order to figure out the problem; if "s" is a JSON string post it. If not, that's the problem, as fromString on plain text will just create a white, unformatted message containing that text."
String s; is a plain text

**Comment by Steveice10** [comment]
How would there be color, then, if you're just doing fromString(s)?

**Comment by Lennyss** [comment]
but getReason() in  DisconnectedEvent  give me a plainText so i must write own method to change this text to json and send?

**Comment by Steveice10** [comment]
You don't necessarily have to use custom JSON; you could use setStyle on the Message with a MessageStyle instance created with your desired color and formatting. My main point was that you wouldn't get formatting from simply calling fromString on plain text.

**Comment by Lennyss** [comment]
ok i will check this :)
