### ISSUE TITLE
Packet 0/35 (fv)

### ISSUE THREAD

**Issue by ghost** [GeyserMC/MCProtocolLib#284]
I have problem to create server, so i create server server is started but i can't connect to him, server disconnect me with error: Packet 0/35 (fv) was larger than i expected, found 8 bytes extra whilst reading packet 35, my code: https://pastebin.com/eFCdwVfT

**Comment by 0-x-2-2** [comment]
what version are you trying to connect from

**Comment by ghost** [comment]
1.8.8 and protocol mcplib is 47

**Comment by Lennyss** [comment]
@SampTV aka matixdev sory but older protocol version is not supported, just use 1.12 version, or fix it yourself

**Comment by ghost** [comment]
Im trying but i dont have idea how to ;(

**Comment by Mareckoo01** [comment]
**You need**:
to know how to use google,
some Java knowledge,
read errors and/or add debug messages,
change the code..

done.

**Comment by SampTV** [comment]
@Mareckoo01 for you easy, for me level hard >.<
