### ISSUE TITLE
multi-version support?

### ISSUE THREAD

**Issue by DefinitlyEvil** [GeyserMC/MCProtocolLib#286]
hi, 
I am coding AuthServer which only processes ServerChatPacket, 
is it possible to allow multiple versions to connect since I only need to process one type of packet?

**Comment by Steveice10** [comment]
Not planned, as it would be too fragmented and difficult to maintain to have multiple protocol versions at the same time.

You could use a Maven plugin (or the equivalent for whatever your build system is) to map different versions of the MCProtocolLib to unique packages.

**Comment by DefinitlyEvil** [comment]
@Steveice10 wow could you suggest that plugin name?

**Comment by Steveice10** [comment]
It can be done using the shade plugin. See here for information: https://maven.apache.org/plugins/maven-shade-plugin/examples/class-relocation.html

**Comment by DefinitlyEvil** [comment]
so by using this I can use same libraries with different version? wow nice! 
but I have to re-compile MCProtocolLib isn't it. xD

**Comment by Steveice10** [comment]
The shade plugin settings go in the pom for your project; already-compiled builds of the versions you need should be fine,

**Comment by 0-x-2-2** [comment]
@DefinitlyEvil if its really simple i don't think you need mcprotocollib you could just make your own system that 1.7-1.12.2 clients can join on

**Comment by DefinitlyEvil** [comment]
@Steveice10 thanks 
@w-o-a-h I just don't wanna re-implement the protocol and things, too time-comsuming.
