### ISSUE TITLE
actionbar packet

### ISSUE THREAD

**Issue by speedAccount** [GeyserMC/MCProtocolLib#287]
Hello, what is the package to display actionbar?

**Comment by speedAccount** [comment]
@Steveice10

**Comment by Steveice10** [comment]
What do you mean by action bar? I'm a bit rusty on my terminology.

**Comment by speedAccount** [comment]
I want to display actionbar with text
@Steveice10

**Comment by speedAccount** [comment]
@s

**Comment by speedAccount** [comment]
@Steveice10

**Comment by Steveice10** [comment]
Are you referring to text displaying above the inventory do that? If so, I believe that's done with a chat packet.

**Comment by speedAccount** [comment]
@Steveice10 
Yes, I mean what you wrote, but I have a question what kind of things I use to display this action bar.

**Comment by speedAccount** [comment]
@Steveice10 
It helped:
event.getSession().send(new ServerChatPacket("test", MessageType.NOTIFICATION));
I have one more question how to add slots to the tablist?
I'm writing about:
![capture](https://user-images.githubusercontent.com/31792212/30965515-f6a74c1e-a455-11e7-94b7-067b5a775ba2.PNG)

**Comment by m3ku** [comment]
@speedAccount  Polaczek? bo taka tablista u easypeasy ;p

**Comment by speedAccount** [comment]
@m3ku no a jak hehe xDDD

**Comment by m3ku** [comment]
@speedAccount byś sprzedał login sequence stary bo pisze miesiąc i coś nie idzie ;/

**Comment by Steveice10** [comment]
I believe the player list slot count depends on what you send as the maximum player count in the join game packet? If not, it might simply expand as you add more players until it reaches its maximum size.

**Comment by speedAccount** [comment]
Thanks, the last question I have a ready command and I want after typing the IP:PORT teleport the server
@Steveice10

**Comment by m3ku** [comment]
@speedAccount to jak?

**Comment by Steveice10** [comment]
What do you mean by "teleport the server"?

**Comment by speedAccount** [comment]
connect to server

**Comment by speedAccount** [comment]
@Steveice10

**Comment by Steveice10** [comment]
I'm still not sure what you're trying to do. You want to connect to your server and execute a command...? If you're looking to add commands to your server, you could listen for chat packets starting with "/".

**Comment by VenixPLL** [comment]
He want to connect to other server with other server with command
i think
like /join ip:port

**Comment by speedAccount** [comment]
@VenixPLL confirm

@Steveice10

**Comment by Steveice10** [comment]
In that case, you'd have to set up some kind of proxy server to route clients to the correct server and pick up on those commands. Something like BungeeCord.

**Comment by speedAccount** [comment]
@Steveice10 
That's why I'm writing here to learn how to do this.

**Comment by Steveice10** [comment]
That's a bit more complicated of a task than I can simply give you instructions on.

**Comment by speedAccount** [comment]
As you will give instructions I will be happy.

**Comment by speedAccount** [comment]
@Steveice10

**Comment by Steveice10** [comment]
Like I said, that kind of goal is more complex than I can instruct you on.

**Comment by speedAccount** [comment]
please

**Comment by speedAccount** [comment]
@Steveice10 please

**Comment by speedAccount** [comment]
please

**Comment by m3ku** [comment]
@speedAccount  Sprzedałbyś?

**Comment by speedAccount** [comment]
@m3ku ale co ?

**Comment by m3ku** [comment]
@speedAcount login sequence
