### ISSUE TITLE
Connection

### ISSUE THREAD

**Issue by MALW3R3** [GeyserMC/MCProtocolLib#288]
Hello, how can i create localhost SERVER who will listen for all packets received from localhost socks5 proxy on specific port. 
It's possible in java socket that it listen for all packet received on specific port example localhost:1080 when i connect to server

**Comment by MALW3R3** [comment]
In java it's: Socks 5 Server who's listening for minecraft packets

**Comment by Steveice10** [comment]
I think you'd need to have the clients connecting to the server through the proxy. Whatever the means, the proxy must be directing it's connections to the server.

**Comment by MALW3R3** [comment]
@Steveice10 
Can you add that option in mcprotocollib to create server listen on socks5 proxy ?

**Comment by Steveice10** [comment]
No. Server sockets listen on a port and the client connects to the listening server. That's just how TCP sockets work. Some piece of software, whether it be your proxy or some other external process, needs to be receiving connections from the outside, opening a connection with the localhost server, and forwarding data back and forth between the two.

**Comment by MALW3R3** [comment]
@Steveice10 
Yeah i have software on all ports who receive that but i can receive packets from minecraft client but i want save that packets on MCProtocollib as ArrayList<Packet> it's possible to do ?
`ArrayList<Packet>`

**Comment by Steveice10** [comment]
If the connection is getting to the MCProtocolLib server, then yeah, just listen for packets received by those connections and add them to your list.

**Comment by MALW3R3** [comment]
@Steveice10 
Ok, so i can't do it on mcprotocollib ;/ Only on java socket because i don't connect to listening server i just listening on packets on :1080 but i connect to server normally
