### ISSUE TITLE
How to Get Player position with bot mcprotocollib 1.8.8

### ISSUE THREAD

**Issue by VenixPLL** [GeyserMC/MCProtocolLib#289]
i don't know how to get the player position with bot on Minecraft Server can anyone help me?

**Comment by VenixPLL** [comment]
@Steveice10

**Comment by Lennyss** [comment]
read packet, ServerPlayerPositionRotationPacket
and get packet.getX(), y,z, etc

**Comment by VenixPLL** [comment]
i want to get the other player position not the bot

**Comment by Steveice10** [comment]
Listen for packets spawning players and moving entities with their IDs.
