### ISSUE TITLE
How to get player name from uuid

### ISSUE THREAD

**Issue by speedAccount** [GeyserMC/MCProtocolLib#291]
i want convert uuid to player name (protocolib 1.8.8)

**Comment by speedAccount** [comment]
@Steveice10

**Comment by Steveice10** [comment]
If you got the UUID from a GameProfile, it should also have the player's name. Otherwise, you'll have to do an online lookup, which is not part of MCProtocolLib.

**Comment by VenixPLL** [comment]
I have an UUID from ServerSpawnPlayerPacket, can i get the player name from another packet?
Btw , i have an nonpremium acc , i can't check the uuid in "https://api.mojang.com/profiles/minecraft"

**Comment by Steveice10** [comment]
Acording to [the protocol wiki](http://wiki.vg/Protocol#Spawn_Player), the vanilla client gets player names, skins, etc. from data provided in Player List Item packets.

**Comment by Mareckoo01** [comment]
My comment in #253 (#242) could help you. (You get uuid & player name and store it in Map<UUID, String> or however you want...)
