### ISSUE TITLE
When I join the server is still ...

### ISSUE THREAD

**Issue by Example125** [GeyserMC/MCProtocolLib#295]
Hi, I have a problem. When I join the server is still Downloading terrain ...
I using a login method in https://github.com/Steveice10/MCProtocolLib/blob/master/example/com/github/steveice10/mc/protocol/test/MinecraftProtocolTest.java 
How can I fix this, can I ask for a code to fix it?

**Comment by 0-x-2-2** [comment]
http://wiki.vg/Protocol

**Comment by Example125** [comment]
But what exactly do I send to "load terrain"?

**Comment by 0-x-2-2** [comment]
you need to do the login sequence
