### ISSUE TITLE
Internal Network Exception...

### ISSUE THREAD

**Issue by Example125** [GeyserMC/MCProtocolLib#296]
I'm trying to join the server but kick me of proxy for Internal Network Exception.
https://imgur.com/a/WWr20
I send
session.send (new ServerSpawnPositionPacket (pos));
and
 session.send(new ServerJoinGamePacket(0, false, GameMode.SURVIVAL, 0, Difficulty.PEACEFUL, 10, WorldType.DEFAULT, false));
Thanks for all solutions!

**Comment by bddvlpr** [comment]
Any stacktraces?

**Comment by Example125** [comment]
No.

**Comment by Example125** [comment]
@Steveice10

**Comment by Steveice10** [comment]
What Minecraft version is this, and are you sending the join packet before the spawn position packet?

**Comment by HP888** [comment]
Minecraft/McProtocolLib version is 1.8.8, yes i sending join packet.

**Comment by bddvlpr** [comment]
@HP888 anything written in the minecraft log?

**Comment by HP888** [comment]
No, logs are clear.

**Comment by Lennyss** [comment]
Older protocol version is not supported, just use 1.12 or fix this problem yourself :)

**Comment by PoLsKiPaLaCz** [comment]
@HP888 javastart.pl
