### ISSUE TITLE
Packet 0/35 (iw) was larger than I expected, found 15 bytes extra whilst reading packet 35

### ISSUE THREAD

**Issue by speedAccount** [GeyserMC/MCProtocolLib#300]

**Comment by speedAccount** [comment]
https://pastebin.com/HHihbTZT
@Steveice10

**Comment by Steveice10** [comment]
I don't understand, is MCProtocolLib acting as a client or a server? The title of the issue implies that you are trying to make a server and sending a join game packet to the vanilla client, but the stack trace you posted in that pastebin would be an MCProtocolLib client receiving a packet from a vanilla server.

**Comment by speedAccount** [comment]
i have mcprotocllib 1.12 protocol version 47

**Comment by Steveice10** [comment]
The current protocol version is 340...
