### ISSUE TITLE
Trying to redirect packets from my bot to my session

### ISSUE THREAD

**Issue by ghost** [GeyserMC/MCProtocolLib#301]
My code: https://pastebin.com/PuU9yYLf
Bot join to server and later me kicks.
Reason : io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: Unregistered outgoing packet class:
org spacehq.mc.protocol.packet.login.server.LoginSetCompressionPacket

**Comment by Steveice10** [comment]
You are trying to send a server packet from a client. You cannot do that.
