### ISSUE TITLE
1.10.2 Jar?

### ISSUE THREAD

**Issue by kingdevnl** [GeyserMC/MCProtocolLib#302]
I sadly cant compile from src becous your old Site its repo its down
So dous anyone have a 1.10.2 Jar?

**Comment by Johni0702** [comment]
All branches (1.7.10+) in [ReplayMod/MCProtocolLib](https://github.com/ReplayMod/MCProtocolLib/) should compile from source and be available via JitPack.
They may however contain extra commits that aren't in this repo and any commit over there may break compatibility (so be sure to depend on a specific commit).

Alternatively there's also [Mareckoo01/MCProtocolLib](https://github.com/Mareckoo01/MCProtocolLib/) which contains pre-built jars and more branches (1.7.4+) that afaict should also build from source (haven't tried that though).

**Comment by Steveice10** [comment]
I don't support older versions. @Johni0702's solution should work.
