### ISSUE TITLE
connect to other server

### ISSUE THREAD

**Issue by yooniks** [GeyserMC/MCProtocolLib#304]
hello, i already using:

https://hastebin.com/unetufusud.cs

but when i used "#join [...]", and client has connected to new session im kicking with reason "Internal network exception"

**Comment by speedAccount** [comment]
XD trzebalo obeserwowac co sie dzieje tutaj to bys joina dawno mial XD

**Comment by m3ku** [comment]
no właśnie xdd

**Comment by 0-x-2-2** [comment]
this code seems to be the issue.

```java
@Override
public void packetReceived(PacketReceivedEvent event) {
 client.getSession().send(event.getPacket());
}
```

**Comment by Steveice10** [comment]
You shouldn't be trying to send received packets back to the server.

**Comment by yooniks** [comment]
ok, thanks.
