### ISSUE TITLE
Check if packet is clientpacket not server?

### ISSUE THREAD

**Issue by ghost** [GeyserMC/MCProtocolLib#307]
All in title. 
Polaczek xD

**Comment by m3ku** [comment]
Wiedziałem że polaczek XD

**Comment by ghost** [comment]
@m3ku wiesz może jak zrobić te jebane łączenie? xD

**Comment by m3ku** [comment]
join? mam ale cały czas dowloading terrain i próbuje jakoś to zrobić

**Comment by ghost** [comment]
@m3ku zrobiłem tez tak, ze bot wbija pierw i wszystkie pakiety wysyłam do mojej sesji ale tez downloading terrain ciagle... jbc to mozemy sprobowac razem cos ogarnac ;p

**Comment by m3ku** [comment]
Możemy jedynie pisać bo nie gadam. skype; meku public

**Comment by ghost** [comment]
Wysłałem zapro

**Comment by speedAccount** [comment]
xd ja mam joina od paru tyg frajerzy xDDDD

**Comment by speedAccount** [comment]
dzialajacego ;p

**Comment by yooniks** [comment]
@speedAccount podasz skype?

**Comment by m3ku** [comment]
@speedAccount ja też mam już od dawna tylko mu dałem ;]

**Comment by speedAccount** [comment]
@m3ku  o czym ty pierdolisz ja ci joina dalem XD
