### ISSUE TITLE
ListTag 

### ISSUE THREAD

**Issue by MALW3R3** [GeyserMC/MCProtocolLib#315]
Hello how to get ListTag ? I try to change book

`	        StringTag meinebook = new StringTag("pages");
`
How get it in ListTag i can't ListTag meinebook = new ListTag("pages");
i want to modify my book pages

Thank you, i tried with wiki.vg but no information

**Comment by AFYaan** [comment]
xd

**Comment by ghost** [comment]
http://wiki.vg/Plugin_channels#MC.7CBEdit

**Comment by MALW3R3** [comment]
@masste 
Thank you, that was a solution of my problem ! :)
