### ISSUE TITLE
connect to other server (with join command)

### ISSUE THREAD

**Issue by yooniks** [GeyserMC/MCProtocolLib#316]
hello, i did join command, and it's work, but when i join as if he is disconnected from the session, 
I just fall down, and it doesn't work for me, the players don't see me, etc.
Can someone help me?
https://scr.hu/gmNN13
https://scr.hu/MMKK8r

**Comment by Kici33** [comment]
code?

**Comment by yooniks** [comment]
xxx, to close.

**Comment by 0-x-2-2** [comment]
again http://wiki.vg/Protocol

**Comment by PoLsKiPaLaCz** [comment]
javastart.pl ;)

**Comment by HP888** [comment]
moze najpierw sam sie naucz javy, a pozniej sie wypowiadaj jebany cebulaku

**Comment by PoLsKiPaLaCz** [comment]
@HP888 ja umiem ;P

**Comment by kamcio96** [comment]
@PoLsKiPaLaCz od kiedy?  XDDD

**Comment by yooniks** [comment]
Rozwiązane dawno, a @PoLsKiPaLaCz zapierdol sie bo uzywales mojego joina i nadal masz 90% kodu mojego, 10% - join kogoś innego i rekt od kogoś który nie działa bo spada ci tylko ping bo wysyłasz 10 pakietów  X argument1

co do tematu miałem problem z chunkami, zmieniłem wersje mcprotocollib i sie poprawilo.

english:
i had problem with chunks and i changed mcprotocollib version and it fixed.
