### ISSUE TITLE
Player move don't work

### ISSUE THREAD

**Issue by chno9133** [GeyserMC/MCProtocolLib#32]
Hi! When I try to send a packet:
ClientPlayerPositionRotationPacket(isGrounded, playerX, playerY - 1.62, playerY, playerZ, 90, 90)
I see nothing on my server(PlayerMoveEvent print). What is the problem?

**Comment by binarydepartment** [comment]
You are probably sending a position that is not allowed/possible. Check the infos on this site: http://wiki.vg/Protocol#Player_Position

When you join the game the server sends a ServerPlayerPositionRotationPacket. Extract the player position from that and increase one direction by very small steps (0.02 should work if i remember correctly).

**Comment by chno9133** [comment]
Thanks for your answer but it still doesn't move.
Here's my code:
http://wklej.org/id/1329720/
What is the problem?

2014-04-11 17:45 GMT+02:00 viciousmind notifications@github.com:

**Comment by chno9133** [comment]
http://pastebin.com/s01ueawn
Okay, I made it so, and they still don't move and I still don't know whats
the problem... ehh...
Thanks for your answer.

2014-04-12 0:41 GMT+02:00 Steven Smith notifications@github.com:

**Comment by chno9133** [comment]
YEAH! Thanks! It works :D
Here is my code:
http://pastebin.com/m4ydWjkq

2014-04-12 17:02 GMT+02:00 Steven Smith notifications@github.com:

**Comment by serega6531** [comment]
Hi, I have the same problem here. I'm using this code: http://pastebin.com/LBWCQ8ur
But when player joins nothing happens, it just stands still.
Unfortunately, those pastebin pages from @best241 are expired so I cant see the fixes. How can I fix it?
