### ISSUE TITLE
How to check server info (motd, players, etc.) And pingpacket?

### ISSUE THREAD

**Issue by speedAccount2** [GeyserMC/MCProtocolLib#321]
Hi, how to check server info? Like motd, online players, etc.
(other server)

And.. how to send ping packet to the server? (other server)
When i joining to a specific server i was kicked with reason "You must be verify! Add the server to list of the servers"

**Comment by makindotcc** [comment]
wiki.vg 
http://wiki.vg/Protocol#Status

**Comment by speedAccount2** [comment]
okey, but.. how to send a ping packet?

**Comment by 0-x-2-2** [comment]
http://wiki.vg/Protocol https://github.com/Steveice10/MCProtocolLib/blob/master/example/com/github/steveice10/mc/protocol/test/MinecraftProtocolTest.java is all you need basicly

**Comment by Steveice10** [comment]
An example can be found in the source file @w-o-a-h linked under the "status" method.
