### ISSUE TITLE
last packet ms

### ISSUE THREAD

**Issue by speedAccount2** [GeyserMC/MCProtocolLib#322]
How to check how many ms received the last packet from the server?

I using:
			String ll = event.getPacket().toString();
			if(ll.toLowerCase().contains("server")){
                                long lastPacket = ....
				System.out.println(time);
			}
what's next?

**Comment by ghost** [comment]
onRecived
session.send(new ChatPacket("Ostatni pakiet:  " + packet.getClass().getName().toString + "( " + time + " ms");
jakos tak miej litosc pana

**Comment by speedAccount2** [comment]
@masste 
ale mi chodzi o to wlasnie zeby miec te "time", bo nie umiem tego zrobic.

**Comment by makindotcc** [comment]
save System.currentTimeMillis() when received packet and next:
System.currentTimeMillis() - lastReceivedTime
This is issue with mcprotocollib or learning programming lang?

**Comment by speedAccount2** [comment]
to close.
