### ISSUE TITLE
bot don't move

### ISSUE THREAD

**Issue by speedAccount2** [GeyserMC/MCProtocolLib#323]
//command
https://pastebin.com/raw/nLtQNJuZ

//bot listener
https://pastebin.com/raw/WzUCM8xg

bot don't move, why?

**Comment by Mareckoo01** [comment]
You need to send ClientTeleportConfirmPacket, see #246

**Comment by speedAccount2** [comment]
@Mareckoo01 ClientTeleportConfirmPacket doesn't exists in 1.8.8

**Comment by speedAccount2** [comment]
ok, i use this:
//Player == user
player.bot.move(player.getX()mplayer.getY(), player.getZ()); 
//(moveTo(), jump() too.)

but..
my bot has been kicked with reason:
Invalid move packet received

Bot = https://github.com/phase/PhaseBot, https://github.com/phase/PhaseBot/blob/master/src/xyz/jadonfowler/phasebot/Bot.java

**Comment by m3ku** [comment]
XDDDD ja mam mother juz dawno skonczone

**Comment by speedAccount2** [comment]
podasz skype?

Mam duzo rzeczy do zaoferowania, i pieniadze tez.
@m3ku

**Comment by m3ku** [comment]
Pewnie już nie potrzebujesz ale jak coś: meku public
