### ISSUE TITLE
Failed to Login: Access Token can not be null or empty

### ISSUE THREAD

**Issue by speedAccount** [GeyserMC/MCProtocolLib#324]
on join
Failed to Login: Access Token can not be null or empty

**Comment by speedAccount** [comment]
to close

**Comment by speedAccount2** [comment]
Wchodzisz na serwer tylko dla premek idioto XD

**Comment by ghost** [comment]
wiki.vg EncryptionRequest

**Comment by speedAccount** [comment]
napisalem... to close debile po 2 jaki kurwa serwer dla premek to bylo proxy a nie serwer jakis

**Comment by ghost** [comment]
server.setGlobalFlag(MinecraftConstants.VERIFY_USERS_KEY, false);
