### ISSUE TITLE
Error when there are 2 people

### ISSUE THREAD

**Issue by speedAccount** [GeyserMC/MCProtocolLib#325]
Error: internal network exception

**Comment by speedAccount** [comment]
ENGLISH: to close xDDD sorry
POLISH: do zamkniecia jednak naprawilem po 1 minucie

**Comment by PoLsKiPaLaCz** [comment]
@speedAccount  masz skype?

**Comment by kamcio96** [comment]
![](https://ibin.co/3lH4Gw9Lcx6m.jpg)

**Comment by PoLsKiPaLaCz** [comment]
@kamcio96 ty najlepszy

**Comment by kamcio96** [comment]
thx
