### ISSUE TITLE
Edit book v2

### ISSUE THREAD

**Issue by MALW3R3** [GeyserMC/MCProtocolLib#326]
Hello i have all NBT who edit book but i want now send plugin message packet who will send book to server but i know that in channel will be "MC|BEdit" but second argument byte[] ?

**Comment by Steveice10** [comment]
The byte array argument is for the raw message data. See https://wiki.vwiki.vg/ for protocol usage documentation.

**Comment by MALW3R3** [comment]
@Steveice10 
Sorry but it doesn't tell me anything, could you give me some clue ? I have all NBT but how prepare MC|BEdit data

**Comment by Lennyss** [comment]
@MALW3R3  just fucking learn minecraft_protocol and java... is not mcprotocolib issues lol just use brain....

**Comment by speedAccount2** [comment]
code?

**Comment by speedAccount** [comment]
@speedAccount2 sprzedam mothera, joina itp chcesz cos kupic?

**Comment by 0-x-2-2** [comment]
http://wiki.vg/Protocol

**Comment by speedAccount2** [comment]
TA, PODAJ SKYPE
@speedAccount

**Comment by MALW3R3** [comment]
@w-o-a-h 
Yes i know, I have dealt with everything but i have just problem with data byte[] mc|bedit @Steveice10  any clue ?

**Comment by speedAccount2** [comment]
@MALW3R3 use a buffer.
and next get array byte[] from buffer

**Comment by kamcio96** [comment]
odezwał się spec ^ XDDDDDDD
