### ISSUE TITLE
how to edit this name

### ISSUE THREAD

**Issue by speedAccount** [GeyserMC/MCProtocolLib#327]
How to edit this name:
![axa](https://user-images.githubusercontent.com/31792212/31863494-55e4c34a-b74e-11e7-8293-436a94451486.png)

**Comment by speedAccount** [comment]
@Steveice10

**Comment by 0-x-2-2** [comment]
modify the tablist add packet to change the name also http://wiki.vg/Protocol

**Comment by SampTV** [comment]
@speedAccount jakiś kontakt do ciebie?
