### ISSUE TITLE
bossbar on 1.8.8

### ISSUE THREAD

**Issue by speedAccount** [GeyserMC/MCProtocolLib#328]
how to display bossbar on mcprotocollib 1.8.8?

**Comment by 0-x-2-2** [comment]
http://wiki.vg/Protocol also 1.8.8 is not supported.

but... 

 http://wiki.vg/index.php?title=Protocol&oldid=7368 should be for 1.8-1.8.9

**Comment by 0-x-2-2** [comment]
On 1.8 I think you can spawn a enderdragon with a custom name at like y -5 just make sure it moves with the player

**Comment by speedAccount** [comment]
@w-o-a-h 
how to spawn enderdragon,what packet use?

**Comment by speedAccount** [comment]
ok, how to get enderdragon/wither name?

**Comment by noisereal** [comment]
ServerSpawnMobPacket(entityId, type, x, y, z, yaw, pitch, headYaw, motX, motY, motZ, metadata)

**Comment by speedAccount** [comment]
@Steveice10 
@noisereal 

how to get enderdragon/wither name?

**Comment by kamcio96** [comment]
@Steveice10 why you didn't ban him? XD

**Comment by speedAccount** [comment]
h o w _ t o _ g e t _ e n d e r d r a g o n _ n a m e?

**Comment by noisereal** [comment]
http://wiki.vg/Entities#Entity_Metadata_Format
Ctrl + F, then search for: custom name

**Comment by ghost** [comment]
@speedAccount jakiś kontakt do ciebie?

**Comment by kamcio96** [comment]
@SampTV a po co? XDDD

**Comment by ghost** [comment]
@kamcio96 a joina chce kupić xd

**Comment by kamcio96** [comment]
@SampTV yyyyy, totalnie nie kumam dlaczego chcesz kupić coś od kogoś kto niczego nie wie XD
chyba że Pan speedAccount trolluje od wielu wielu issues 😄

**Comment by ghost** [comment]
@kamcio96 a ty nie masz joina? ;c

**Comment by kamcio96** [comment]
Discord: kamcio96#8278

**Comment by ghost** [comment]
@kamcio96 jtr mój ziomek do cb napisze w sprawie tego joina, a ja już się zmywam :P
