### ISSUE TITLE
PacketBuffer?

### ISSUE THREAD

**Issue by speedAccount2** [GeyserMC/MCProtocolLib#330]
Hi, how i can get packetbuffer in mcprotocollib?

like it:
ByteBuf buffer = Unpooled.buffer();
PacketBuffer pBuffer = new PacketBuffer(buffer);

**Comment by speedAccount2** [comment]
PacketBuffer only exists in net.minecraft

**Comment by kamcio96** [comment]
Jakieś rozdwojenie jaźni że sam sobie odpowiadasz? XDD

**Comment by m3ku** [comment]
XDDD
