### ISSUE TITLE
Where is ...

### ISSUE THREAD

**Issue by Example125** [GeyserMC/MCProtocolLib#331]
Where is: MinecraftConstants.HOSTNAME_KEY, in MCProtocolLib ?

**Comment by noisereal** [comment]
@Example125 Probably HOSTNAME_KEY is in older or newer version than yours.
https://github.com/Steveice10/MCProtocolLib/blob/299efaf2481b367d310d2836755b6b1da18600bc/src/main/java/com/github/steveice10/mc/protocol/MinecraftConstants.java
