### ISSUE TITLE
achievement.openInventory not registered

### ISSUE THREAD

**Issue by KevinPriv** [GeyserMC/MCProtocolLib#334]
Getting this on login which is triggering a disconnect:
 io.netty.handler.codec.DecoderException: java.lang.IllegalArgumentException: Value achievement.openInventory has no mapping for key class com.github.steveice10.mc.protocol.data.game.statistic.GenericStatistic

This seems like enough information but if it isnt i can post a full stacktrace 
Protocol version: 1.12.1
Server attempting to join: mc.hypixel.net

**Comment by Steveice10** [comment]
1.12.1 does not have achievements IIRC, they were replaced with advancements. Blame the server.
