### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by PoLsKiPaLaCz** [GeyserMC/MCProtocolLib#336]
how do i randomly choose a proxy from my list... i want to randomly pick a proxy :
public static List<String> PROXYLIST;
        PROXYLIST.add("194.15.120.42:19194");
        PROXYLIST.add("83.230.5.31:53046");
        PROXYLIST.add("89.161.27.18:56188");
        PROXYLIST.add("155.133.36.26:19808");
        PROXYLIST.add("178.36.62.46:15573");
        PROXYLIST.add("212.91.25.98:21750");
        PROXYLIST.add("194.15.120.42:19194");
        PROXYLIST.add("81.190.75.183:33734");
        PROXYLIST.add("89.161.27.18:56188");
        PROXYLIST.add("194.15.120.42:19194");
        PROXYLIST.add("155.133.36.26:19808");
        PROXYLIST.add("81.190.75.183:33734");
        PROXYLIST.add("83.16.187.101:29114");
        PROXYLIST.add("212.91.25.98:21750");
        PROXYLIST.add("178.36.62.46:15573");

**Comment by noisereal** [comment]
Issues area is for reporting bugs, etc. with protocol code.

Here you have an example: https://hastebin.com/uforimayeq.java

**Comment by PoLsKiPaLaCz** [comment]
@noisereal thank you bro

**Comment by noisereal** [comment]
@PoLsKiPaLaCz np
