### ISSUE TITLE
bot

### ISSUE THREAD

**Issue by PoLsKiPaLaCz** [GeyserMC/MCProtocolLib#338]
i would like bots to join from a specified client how do i do this?

**Comment by speedAccount2** [comment]
get client session host and port, and connect bots with this lol?
this is issues area with bugs/problems with protocol code or mcprotocollib, not learning. try learn java and see wiki.vg?

**Comment by PoLsKiPaLaCz** [comment]
@speedAccount2 ja chce ja z blazinga polaczyc idioto

**Comment by speedAccount2** [comment]
wiec nie potrafisz zrobic prostej rzeczy, wyslac pakietu tabcomplete, a chcesz robic obejscie? no to piekniiie

**Comment by kamcio96** [comment]
PL: Ej, ja mam propozycję. Zrobicie sobie 1 issue w którym będziecie wymieniać wasz brak doświadczenia XD Dajcie jakiś tytuł "Polish idiots want be rich" czy jakoś tak 😂😂😂

EN: Guys, I have suggestion. Let's create 1 issue with yours problems XD Make the tittle "Polish idiots want be reach" or something like this 😂😂😂

**Comment by Lennyss** [comment]
@Steveice10 just ignore this noobs, they want to make 'botting service' to crash others server and earn money for this but they don't know how to programming...

**Comment by m3ku** [comment]
XDDDDDDDDDDDDDDDDDDDDDD

**Comment by Mareckoo01** [comment]
They should stop because it is illegal, they should instead learn programming and make something cool/useful like custom minecraft client or tools to help/contribute to minecraft community...

**Comment by 0-x-2-2** [comment]
well its not really illegal but no one would want to help them if they just googled for a little they would find a spambot created with MCProtocolLib on github.

**Comment by phase** [comment]
> They should stop because it is illegal

That made me chuckle.
