### ISSUE TITLE
commands

### ISSUE THREAD

**Issue by PoLsKiPaLaCz** [GeyserMC/MCProtocolLib#339]
so when i type a command when im on a server joined then it displays it on chat... the way i make my commands:                                 final String[] args = packet.getMessage().split(" ");
                                args[0] = args[0].toLowerCase();
                                Session session = event.getSession();
                                if (args[0].equals(",commands")||args[0].equals(",help")){
                                    //messages here
                                }

**Comment by 0-x-2-2** [comment]
Cancel the event but if your using outdated MCProtocolLib this might not be possible.

**Comment by PoLsKiPaLaCz** [comment]
@w-o-a-h im using protocollib 1.8.8

**Comment by m3ku** [comment]
No i dużo idiota potrafi ;p

**Comment by m3ku** [comment]
nie umie prostej wiadomości wysłać

**Comment by noisereal** [comment]
@PoLsKiPaLaCz use ServerChatPacket

**Comment by speedAccount2** [comment]
just fucking learn java and protocol
