### ISSUE TITLE
How to get...

### ISSUE THREAD

**Issue by Example125** [GeyserMC/MCProtocolLib#340]
How to generate a list of socks proxies then replace it with
String proxy_ip = "ip_proxy"
int proxy_port = "port_proxy"

**Comment by noisereal** [comment]
Issues area is for reporting bugs, etc. with protocol code.

Here you have an example: https://hastebin.com/uforimayeq.java

**Comment by Example125** [comment]
Everything is ok, but it's about me replace proxy_ip:proxy_port to proxy_ip to String and proxy_port to integer.

**Comment by PoLsKiPaLaCz** [comment]
oh check this: https://hastebin.com/yifedemefu.java

**Comment by Example125** [comment]
error at line 18: Type mismatch: cannot convert from InetSocketAddress to String
