### ISSUE TITLE
io.netty.handler.codec.DecoderException: achievement.openInventory has no mapping for key class com.github.steveice10.mc.protocol.data.game.statistic.GenericStatistic.

### ISSUE THREAD

**Issue by Vadmeme** [GeyserMC/MCProtocolLib#341]
`io.netty.handler.codec.DecoderException: java.lang.IllegalArgumentException: Value achievement.openInventory has no mapping for key class com.github.steveice10.mc.protocol.data.game.statistic.GenericStatistic.`
i started getting this error when joining hypixel i have no clue how to fix it

**Comment by Steveice10** [comment]
Blame the server, achievements were replaced with advancements in 1.12.

**Comment by DaMatrix** [comment]
This is a bug, and should be fixed.  I'm getting this too, even on a vanilla server.  Advancements also cause a similar missing key exception.

Also this has nothing to do with achievements, this is for statistics.

(Sorry for double-post)

**Comment by DaMatrix** [comment]
Also this has nothing to do with achievements, this is for statistics.

**Comment by Steveice10** [comment]
I just checked the 1.12.2 Minecraft Server, and there are no instances of "achivement." or "openInventory" anywhere in the code. This is not an issue if you are using a vanilla server.

**Comment by 0-x-2-2** [comment]
this should be handled in a better way then crashing the program because in the vanilla client it does not crash this also happens with advancements or custom server advancements if I think correctly.

**Comment by Steveice10** [comment]
Advancements are not mapped to enums, so this does not happen for custom advancements. I suppose I could change statistics to just use strings, although I'm away for Thanksgiving holiday right now.

**Comment by Steveice10** [comment]
Added CustomStatistic as a fallback for any unknown statistic IDs. Let me know if there are any further problems.
