### ISSUE TITLE
Captcha bypass

### ISSUE THREAD

**Issue by speedAccount2** [GeyserMC/MCProtocolLib#342]
Hi, i think about make captcha bypass, but i haven't got idea, how do it.

                            else if (event.getPacket() instanceof ServerChatPacket){
                               ServerChatPacket p = event.getPacket();
                               String msg = p.getMessage().getFullText();
and when msg contains captcha i want get it.
like:
Captcha: Kx8N1
and get this from serverchatpacket, how?

I know.. this is issues for problems with protocol etc...

**Comment by kamcio96** [comment]
http://javastart.pl

**Comment by m3ku** [comment]
XDDDD

**Comment by m3ku** [comment]
januszu sprawdzaj string np. captch == "ta twoja captcha"?

**Comment by kamcio96** [comment]
@m3ku januszu, Tobie też polecam http://javastart.pl
https://stackoverflow.com/questions/767372/java-string-equals-versus

**Comment by speedAccount2** [comment]
@m3ku co ty kurwa pierdolisz jebany idioto

**Comment by m3ku** [comment]
@speedAccount2  idioto? to ja kurwa umiem taki prosty kod napisać a ty nie lol

**Comment by yooniks** [comment]
@m3ku ty nawet nie wiesz chyba o co mu chodzi XD w zyciu bys tego nie zrobil

**Comment by m3ku** [comment]
jak gracz czy bot wejdzie na serwer i wyswietli sie wiadomosc przepisz kod: kakdkasd to ma go przepisac o to chodzi ;p

**Comment by HP888** [comment]
dla januszy ktorzy tylko czekaja aż ktos udostepni:
https://hastebin.com/ituvipamux.swift
