### ISSUE TITLE
laggs

### ISSUE THREAD

**Issue by PoLsKiPaLaCz** [GeyserMC/MCProtocolLib#343]
when i joinbot in my proxy it lags the proxy but after its ok so how do i fix this.

**Comment by 109C** [comment]
Stagger the bot joining.

**Comment by PoLsKiPaLaCz** [comment]
@109C how do i do this?

**Comment by 109C** [comment]
@PoLsKiPaLaCz Wait in between starting different bots. That way all the bots will not be competing for whatever limited resource at the same time.
