### ISSUE TITLE
proxy does not work on vps

### ISSUE THREAD

**Issue by PoLsKiPaLaCz** [GeyserMC/MCProtocolLib#344]
the proxy server works when i start it on my pc... when i put it on the vps it turns on and then turns back off... main class: https://hastebin.com/egoxuvegep.java

**Comment by kamcio96** [comment]
Da się to odzobaczyć?

**Comment by 109C** [comment]
A reminder: Mojang's services are like quantum mechanics. Sometime they're up, sometimes down, sometimes both at the same time.

**Comment by noisereal** [comment]
@PoLsKiPaLaCz check if the port is already in use.
Paste us exception

**Comment by dekros987** [comment]
https://javastart.pl/
http://wiki.vg/Main_Page

**Comment by PoLsKiPaLaCz** [comment]
@noisereal it doesnt have an exception it turns on then off

**Comment by noisereal** [comment]
@PoLsKiPaLaCz try to get it

**Comment by m3ku** [comment]
Śmiechłem zamień 127.0.0.1 na 0.0.0.0 pajacu

**Comment by VenixPLL** [comment]
Debian nie obsłuzy z Terminala JFrame , Sciezka do pliku z proxy "C:\\Users\\User\\Desktop\\SOCKS 5.txt" powinna byc zmieniona :)
