### ISSUE TITLE
problem with GameProfile [and others!, please help]

### ISSUE THREAD

**Issue by speedAccount2** [GeyserMC/MCProtocolLib#348]
https://hastebin.com/uwoqoconof.lua

code:
                        final GameProfile profile = session.getFlag(MinecraftConstants.PROFILE_KEY);

**Comment by ghost** [comment]
`session.getFlag("profile");`

**Comment by Steveice10** [comment]
It sounds like you have two different instances of MCAuthLib, one with org.spacehq.mc.auth.GameProfile and one with org.spacehq.mc.auth.data.GameProfile, and you're trying to use the wrong one.

**Comment by speedAccount2** [comment]
https://scr.hu/aDok3P

ohh, when im pinging the server:

[WARNING] Throwable caught while firing event.
java.lang.NoSuchMethodError: org.spacehq.mc.protocol.data.status.PlayerInfo.<ini
t>(II[Lorg/spacehq/mc/auth/data/GameProfile;)V
        at xxx.Main$2.buildInfo(Main.java:444)
        at org.spacehq.mc.protocol.ServerListener.packetReceived(ServerListener.
java:123)
        at org.spacehq.packetlib.event.session.PacketReceivedEvent.call(PacketRe
ceivedEvent.java:45)
        at org.spacehq.packetlib.tcp.TcpSession.callEvent(TcpSession.java:155)
        at org.spacehq.packetlib.tcp.TcpSession$PacketHandleThread.run(TcpSessio
n.java:398)

when im starting the 'proxy' with intellij>run>main its fine, but  when im export it with build artifact..>build, and start proxy.jar with file start.bat, with command 'java -jar proxy.jar', its not fine and throw errors;/

@Steveice10

**Comment by Steveice10** [comment]
One of your dependencies might itself include a version of MCProtocolLib. Also, older versions are unsupported.

**Comment by speedAccount2** [comment]
@Steveice10 no, im using the same depends that i used before, and before that's was working..

**Comment by PoLsKiPaLaCz** [comment]
@speedAccount2 yooniks wypierdalaj chuju 2 konto masz zjebie 
widac twoj nick: `sended packet: org.spacehq.mc.protocol.packet.ingame.server.scoreboard.ServerUpdateScorePacket
sended packet: org.spacehq.mc.protocol.packet.ingame.server.scoreboard.ServerUpdateScorePacket
sended packet: org.spacehq.mc.protocol.packet.ingame.server.scoreboard.ServerTeamPacket
Uzytkownik yooniks/e0c372a0-8916-3fc0-bbc4-594f493c48fa(0) - 127.0.0.1:52805 wyszedl!
sended packet: org.spacehq.mc.protocol.packet.ingame.server.scoreboard.ServerTeamPacket
sended packet: org.spacehq.mc.protocol.packet.ingame.server.scoreboard.ServerTeamPacket
sended packet: org.spacehq.mc.protocol.packet.ingame.server.scoreboard.ServerTeamPacket
sended packet: org.spacehq.mc.protocol.packet.ingame.server.scoreboard.ServerTeamPacket
sended packet: org.spacehq.mc.protocol.packet.ingame.server.scoreboard.ServerTeamPacket
sended packet: org.spacehq.mc.protocol.packet.ingame.server.scoreboard.ServerTeamPacket`

**Comment by speedAccount2** [comment]
@PoLsKiPaLaCz Yooniks mi pomagał z proxy i je testował u siebie, i poszukaj sobie gdzieś komentarz jak mi Yooniks skomentował, chyba sam siebie bym nie poprawiał z kodem lub pouczał? 
I poza tym pożyczył system userów za który dziekuje <3

**Comment by yooniks** [comment]
@PoLsKiPaLaCz pomagałem mu tak jakby debugować pakiety i w inny sposób niż edytowanie mcpl poprawić Internal Network Exception podczas wbijania na niektóre serwery, bo mam podobnie to fixniete, ale kodu mu nie dam bo jestem zdania ,że lepiej dochodzić do czegoś samemu.
I ja mam od dawna to co on chce.

**Comment by PoLsKiPaLaCz** [comment]
@yooniks nom ja sam se fixnalem libke xd
