### ISSUE TITLE
OpenNbt, get array byte?

### ISSUE THREAD

**Issue by speedAccount2** [GeyserMC/MCProtocolLib#350]
hi guys, how i can get from itemstack (or tag?) "byte[]"?
                       
                        session.send(new ClientPluginMessagePacket("MC|BEDIT",
                                          hereByte[]));

**Comment by kamcio96** [comment]
http://wiki.vg/Slot_Data
http://wiki.vg/NBT

**Comment by ghost** [comment]
kurwy jebane polskie wypierdalac

**Comment by speedAccount2** [comment]
@kamcio96 dzięki
