### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by Koiczek** [GeyserMC/MCProtocolLib#352]
I have a problem that when the calls for a few sessions it gets a message from all of them that is, for example, how a player writes something on the server and I'm in 2 sessions of this on my chat: 
Steve > Hello! 
Steve > Hello!

**Comment by speedAccount2** [comment]
dziwnie ten tlumacz google ci przetlumaczyl, napisz po polsku to ci moge pomóc, ale wiem chyba o co chodzi, pewnie jak dolaczasz na serwer to masz 2 listenery, u bota i u obecnej sesji, i przy 2 nasluchujesz pakiet chatu i wtedy go wysylasz podwójnie.

**Comment by ghost** [comment]
github pls add censor for shit countries

**Comment by Steveice10** [comment]
I assume @speedAccount2's response likely addressed your problem.

**Comment by 0-x-2-2** [comment]
translated with google translator

>speedAccount2: strangely this translator google translated it, write in polish I can help you, but I know probably what's going on, probably as you attach to the server you have 2 listeners, the bot and in the current session, and 2 you listen to the chat package and then send it twice.
