### ISSUE TITLE
right click item

### ISSUE THREAD

**Issue by PoLsKiPaLaCz** [GeyserMC/MCProtocolLib#353]
i want my bots to right click a sword ... what packet does this

**Comment by PoLsKiPaLaCz** [comment]
@Steveice10

**Comment by PoLsKiPaLaCz** [comment]
@metamolecular

**Comment by PoLsKiPaLaCz** [comment]
@Johni0702

**Comment by Steveice10** [comment]
Check http://wiki.vg/ for protocol documentation.

**Comment by PoLsKiPaLaCz** [comment]
@Steveice10 that doesnt help :(

**Comment by Steveice10** [comment]
Yes it does... Go to "Current Protocol Specification", then find "Use Item".

**Comment by PoLsKiPaLaCz** [comment]
@Steveice10 is there any chance of you giving me the class?

**Comment by Steveice10** [comment]
ClientPlayerUseItemPacket

**Comment by PoLsKiPaLaCz** [comment]
@Steveice10 thank you

**Comment by PoLsKiPaLaCz** [comment]
@Steveice10 this doesnt work as i have 1.8.8 mcprotocollib

**Comment by Steveice10** [comment]
Old versions are not supported.

**Comment by PoLsKiPaLaCz** [comment]
@Steveice10 if i add the class and needed imports will this work?

**Comment by ghost** [comment]
wypierdalaj kurwa

**Comment by PoLsKiPaLaCz** [comment]
@masste idz sie zabij lepiej

**Comment by yooniks** [comment]
"if i add the class and needed imports will this work?" XDXDXDXDXD

**Comment by kamcio96** [comment]
![352183393225801728](https://user-images.githubusercontent.com/1339911/33799148-e4554f8a-dd25-11e7-95ec-20bf5912d602.png)
@PoLsKiPaLaCz  ?

**Comment by PoLsKiPaLaCz** [comment]
@kamcio96 ty sie powiesz raku napisz lepsze proxy to pogadamy...

**Comment by kamcio96** [comment]
lul, napisałem lepsze proxy
