### ISSUE TITLE
Message to all players

### ISSUE THREAD

**Issue by Koiczek** [GeyserMC/MCProtocolLib#354]
How to send message to all players on server ?

**Comment by yooniks** [comment]
get the server sessions and send serverchatpacket..
like:
server.getSessions().forEach(session->session.send(new ServerChatPacket("kkproxy to gowno"));

A tak ps, nie umiesz takiej rzeczy a chcesz sprzedawać te proxy?

**Comment by m3ku** [comment]
XDDDDDDDDDDDDDDDDDDDDDDDDDDD
