### ISSUE TITLE
NIC!

### ISSUE THREAD

**Issue by XoresX** [GeyserMC/MCProtocolLib#356]
NIC TU NIE MA yooniksie i Snyxie!

**Comment by Steveice10** [comment]
This section is for reporting library bugs, not asking for help solving problems with your own code.

**Comment by yooniks** [comment]
Japierdole zabijcie sie kurwa błagam, używasz mojego usera i usermanager które w 50% nie działa i sie dziwisz kurwa czemu ci wywala błędy kurwa zabijcie sie sunny i xores, dwóch super programistów, nie znacie najłatwiejszych podstaw javy, a już sie za proxy bierzecie używając 80% mojego kodu, jeszcze kilka takich proxy zobacze i serio udostepniam gdzieś całe działające proxy na githubie i yt ,żeby rozwalić te wasze gówno proxy.

O nawet kod z ptproxy które ma mój kod znalazem japierdole

jeszcze do tego niepotrzebne exceptiony w kodzie które nic nie podpowiadają i kod idzie dalej, no serio?

 "WARNING: Failed to find a usable hardware address from the network interfaces; using random bytes: 2a:6f:b7:51:49:c2:8e:57
Wlaczono SXProxy - Proxy By Xores & SuNNyTM <3"
jak zobacze to u was na yt to na serio udostepnie całe działające proxy ,żeby nikt nie musiał kupywać waszych gówien, no i oczywiście jak proxy to też fixa, ktory działa od 1.7 do 1.12.

**Comment by kamcio96** [comment]
popieram tego Pana ^

**Comment by phase** [comment]
> Japierdole, kill me, I'm begging you, you use my user and usermanager which does not work 50% and you are wondering why we fuck you kill killer sunny and xores, two super programmers, you do not know the easiest basics of java, and you take a pro with 80 % of my code, I'll see a few more such proxies and I'm seriously sharing a whole proxies on github and yt to smash your proxy shit.
> 
> For even the code from ptproxy which has my code I found japierdole
> 
> there are also unnecessary exceptions in the code that do not suggest anything and the code goes on, really seriously?

> "WARNING: Failed to find a usable hardware address from the network interfaces; using random bytes: 2a: 6f: b7: 51: 49: c2: 8e: 57
SXProxy - Proxy By Xores & SuNNyTM <3 "enabled
If I see you on the floor, it will give you a full working proxy so that no one has to buy your shit, and of course a proxy is also a fix that works from 1.7 to 1.12.

This isn't the place for your Polish proxy arguments. Sometimes I wonder if you guys are even on the right website.

**Comment by Lennyss** [comment]
@phase One people make proxy with this lib and "polish scums" want to copy that proxy and make $$$ but they don't know java :/ Owner should block those people in repo, thats my opinion

**Comment by phase** [comment]
I can make $$$ from a Minecraft bot? Where can I sign up for that?

**Comment by 109C** [comment]
@phase You need good marketing skills. That's all.

**Comment by PoLsKiPaLaCz** [comment]
popieram
