### ISSUE TITLE
Problem with starting server on VPS

### ISSUE THREAD

**Issue by VenixPLL** [GeyserMC/MCProtocolLib#357]
Dec 11, 2017 1:00:01 PM io.netty.channel.DefaultChannelId defaultMachineId
WARNING: Failed to find a usable hardware address from the network interfaces; using random bytes: 02:f3:49:d6:d2:76:a9:59

MCProtocolLib 1.8.8 (My friend does not have this problem, but he has the same libraries)
TEST CODE: https://hastebin.com/apagofucoh.vbs

**Comment by VenixPLL** [comment]
To close , Problem solved

**Comment by Xayanix** [comment]
jebane polskie robaki wypierdalać XD zrobiłem xproxy to teraz każdy musi zrobić to samo XD

**Comment by Xayanix** [comment]
@Steveice10 close this pls

**Comment by VenixPLL** [comment]
Jebany polski robaczku próbuje zrobić lobby na serwer :v , please reopen this

**Comment by VenixPLL** [comment]
@Steveice10 please reopen this

**Comment by Xayanix** [comment]
To może wejdziesz na javastart.pl i poduczysz się podstaw, a nie swoje problemy i niewiedzę wylewasz na issues od McProtocolLib?

**Comment by VenixPLL** [comment]
Próbowałem aktualizowac netty. Nie pomoglo innych rozwiązań nie widzę.

**Comment by XoresX** [comment]
W jakiej linijce masz błąd?
