### ISSUE TITLE
x

### ISSUE THREAD

**Issue by DamageDMG** [GeyserMC/MCProtocolLib#358]
x

**Comment by kamcio96** [comment]
Lib works great, I tested it few times. Your code doesn't work because you don't know how write working code. 
Did you try read java tutorial? I think it may help...

**Comment by DamageDMG** [comment]
The idiot did not understand that it was an troll XDD
At the end of the guide I added the name of the engine on which it was tested: /

Idiota nie ogarnal ze to troll XDD
Kij ze na koncu poradnika dodałem nazwe silnika na którym było to testowane :/

**Comment by kamcio96** [comment]
Trollem nazywasz zniżenie się do poziomu 0? 🤔 Nooo, powiem szczerze, śmieszne w chuj

**Comment by DamageDMG** [comment]
Nie, ale śmieszne jest dla mnie całe to issue, chciałem dodać coś od siebie :D
