### ISSUE TITLE
proxy basis

### ISSUE THREAD

**Issue by Code2k17** [GeyserMC/MCProtocolLib#359]
Hey
I have a question about how to make the proxy base connect to the server

**Comment by DamageDMG** [comment]
https://javastart.pl/ - best reply

**Comment by Xayanix** [comment]
@Steveice10 close

**Comment by m3ku** [comment]
@Steveice10 yes. To close

**Comment by yooniks** [comment]
i think the best solution will be to learn java

**Comment by DamageDMG** [comment]
@yooniks pisze to osoba która na discordzie się pyta o nulla które wyświetla się na nssv XDDDDDD

**Comment by DamageDMG** [comment]
Nie ten issue, sorka xD

**Comment by XoresX** [comment]
No no i kogo ja tutaj widze xDDDDDD pierw wyzywasz Code2k17 a potem sam pytasz xDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
