### ISSUE TITLE
PacketBuffer for mcprotocollib

### ISSUE THREAD

**Issue by PoLsKiPaLaCz** [GeyserMC/MCProtocolLib#360]
@Steveice10 help pls PacketBuffer is not available in mcprotocollib what do i do?

**Comment by Steveice10** [comment]
Check the example in the source repo if you want to know how to use this library.

**Comment by PoLsKiPaLaCz** [comment]
@Steveice10 it doesnt say anything about packetbuffer in the example

**Comment by HP888** [comment]
zabij się, tam jest wszystko wystarczy się znać...

**Comment by PoLsKiPaLaCz** [comment]
@HP888 idz sie zajeb

**Comment by 109C** [comment]
`net.minecraft.network.PacketBuffer` is not available in MCProtocolLib. The closest thing to that I can find is `com.github.steveice10.packetlib.io.buffer.ByteBufferNet{Input,Output}`.

It really depends on what your use case is.

**Comment by yooniks** [comment]
seriously? 
if you wanna do nbt crashers use OpenNBT, look here: https://github.com/Steveice10/OpenNBT
you can't do easy things and you wanna do nbt crashers? XD

i wonder why you writing comments still, you mock XD
