### ISSUE TITLE
Which Packet

### ISSUE THREAD

**Issue by MALW3R3** [GeyserMC/MCProtocolLib#361]
Hello, which packet from http://wiki.vg/Protocol is responsible for update display below name on my sessions, which other sessions would be able to see ?

Thank you.

**Comment by yooniks** [comment]
i think you are looking for 'ServerDisplayScoreboardPacket'
create new instance of serverdisplayscoreboardpacket and set first constructor to ScoreboardPosition.BELOW_NAME

Remember guys .. this is not issue area for your problems with code or learning java and protocol ..

**Comment by MALW3R3** [comment]
I used it before I write that issue but i doesn't work for me. Could you check it ?

**Comment by MALW3R3** [comment]
@Steveice10

**Comment by yooniks** [comment]
Do you use newest version of mc protocollib?
You even can join to servers with 'SideBar' and copy packets and check it.
