### ISSUE TITLE
How to import mcprotocollib?

### ISSUE THREAD

**Issue by ghost** [GeyserMC/MCProtocolLib#363]
//deleted

**Comment by Xayanix** [comment]
I think you will get answer here: www.javastart.pl.
I'm glad i could help you.

**Comment by Xayanix** [comment]
Tell me why do you start learning java by making destructive tool like proxy?

**Comment by Code2k17** [comment]
@Xayanix on jest polakiem xD 
Importujesz jak zwykły plugin. :P

**Comment by ghost** [comment]
@Code2k17 Na jakiej zasadzie? Co trzeba zrobić w Intellij IDEA? Zupełnie się nie znam na tym :(

**Comment by Code2k17** [comment]
javastart.pl - tu znajdziesz wszystko :)
 https://youtu.be/e-kCAMBpTtI

**Comment by kvbus** [comment]
https://www.youtube.com/watch?v=oA_CZ0wsk6A&t=786s

**Comment by yooniks** [comment]
Pobierz sobie jarke mcprotocollib 1.8.8 (na necie gdzieś znajdziesz), wchodzisz w intellij, file > project structure > libraries > "+" > java > i tutaj dajesz scieżke do tej jarki, na dole klikasz apply, okej i to tyle.

ale nie polecam używać starej wersji mcprotocolliba (1.8.8) bo ma dużo rzeczy zbugowanych, które są poprawione chyba w wyższych, no chyba ,że sam sobie fixniesz wersje 1.8.8.

english:
download jar file of mcprotocollib 1.8.8 from web (you will find it somewhere), then enter to the intellij idea, then select file > project structure > libraries > "+" > java > and there you have to enter path to jar file, and finally click 'apply', 'ok' - and it's over :)

**Comment by UnixPL** [comment]
Do you still have a problem with that?

**Comment by levss** [comment]
Nie wiem, nie zaczynaj pisac proxy jak nie wiesz kompletnie nic.
