### ISSUE TITLE
PlayerInfo

### ISSUE THREAD

**Issue by PoLsKiPaLaCz** [GeyserMC/MCProtocolLib#364]
new PlayerInfo(100, 0, new GameProfile[1]),
how to change the gameprofile to what i want?

**Comment by PoLsKiPaLaCz** [comment]
so that i have text on the server info like this: http://prntscr.com/hs9run

**Comment by Steveice10** [comment]
Create an array and fill it with GameProfiles for the "player name" entries you want to send.

**Comment by PoLsKiPaLaCz** [comment]
@Steveice10  an arraylist?

**Comment by PoLsKiPaLaCz** [comment]
public static ArrayList<GameProfile> SEND = new ArrayList<GameProfile>(); like so?

**Comment by PoLsKiPaLaCz** [comment]
DONE IT THANK YOU http://prntscr.com/hsaf3z

**Comment by Inder00** [comment]
Idź się zabij typie. Gówno umiesz, przychodisz z byle gównem na github.. Boże...

**Comment by kamcio96** [comment]
`Najlepsze proxy` XDDDDD

**Comment by UnixPL** [comment]
To niezły polaczek cebulaczek.

**Comment by yooniks** [comment]
learn java & protocol >>>> come back.

"public static ArrayList SEND = new ArrayList(); like so?" ~PolskiPajac
so cool, creating arraylist like jd-gui decompiler

**Comment by 0-x-2-2** [comment]
um that's how you create a arraylist @yooniks

**Comment by yooniks** [comment]
@w-o-a-h an arraylist*
No, i don't create arraylist like that

**Comment by phase** [comment]
Well he's not using generics, but that's how you initialize an ArrayList object.

For anyone reading this, it is _impossible_ to debug your code when you post **one line**.
The more context, the easier it is to debug.

**Comment by PoLsKiPaLaCz** [comment]
@Inder00 zabij sie amebo jebana twoje itools.pl lata jak gowno i to dotego ten darmowy hosting hahahahahhahaha

**Comment by phase** [comment]
Translation for others:
```
PoLsKiPaLaCz: kill yourself fuck your itools.pl years like shit and this is the free hosting hahahahahhahaha
```

...


wow

@Steveice10 do you want to just block these kids? They're not contributing anything useful.
