### ISSUE TITLE
MinecraftProtocol.class for 1.8.9

### ISSUE THREAD

**Issue by TrevorCow** [GeyserMC/MCProtocolLib#365]
I was wondering if there was a 1.8.9 MinecraftProtocol class with all the 1.8.9 registers? I might be blind and missed it or it might just not exist. If not could someone point me in the right direction for making my own? Thank you

**Comment by Steveice10** [comment]
Old Minecraft versions are not supported.

**Comment by TrevorCow** [comment]
You should see if u can request an update on http://wiki.vg/Library_List. It says you support 1.6.4-1.11.2
Thank you anyway

**Comment by Steveice10** [comment]
There are technically versions of MCProtocolLib that support those versions, yes. However, I don't provide updates for or answer questions related to older versions.

**Comment by TrevorCow** [comment]
Is there a place I could get the old versions?

**Comment by 0-x-2-2** [comment]
he just said where you can get them from.

**Comment by TrevorCow** [comment]
Oh sorry, I didn't see that message edit when I sent that. Thank you!
