### ISSUE TITLE
Can you add a guide installation?

### ISSUE THREAD

**Issue by kratess** [GeyserMC/MCProtocolLib#366]
I test it for 2 hours and 0 results. Can you make a tutorial... or release it as a .jar?

**Comment by phase** [comment]
I have a 1.11 example project [here](https://github.com/phase/fisher) (<sub><sup>polish people please don't raid me</sup></sub>), written in Kotlin. I'm using JitPack to retrieve MCPL.


This is what you want to add to your `build.gradle` if you're using Gradle:

```
repositories {
    maven { url 'https://jitpack.io' }
}

dependencies {
    compile "com.github.Steveice10:MCProtocolLib:1.12.1-1"
}
```

Add these to your `pom.xml` if you're using Maven:

```
	<repositories>
            <repository>
                <id>jitpack.io</id>
                <url>https://jitpack.io</url>
	    </repository>
	</repositories>

	<dependency>
	    <groupId>com.github.Steveice10</groupId>
	    <artifactId>MCProtocolLib</artifactId>
	    <version>1.12.1-1</version>
	</dependency>
```

**Comment by kratess** [comment]
i found the solution thanks. Can you help me with proxies?

**Comment by phase** [comment]
[There are already tutorials to do that](https://www.codeleakers.com/showthread.php?65726-How-to-use-a-proxy-on-Minecraft-unban-yourself-on-any-server).

**Comment by kratess** [comment]
i need proxy for bots but socks not work can you have another code for bots?

**Comment by phase** [comment]
I haven't made a proxy bot, but I might if all these polish kids will be giving me that sweet, sweet $$$.

**Comment by kamcio96** [comment]
@phase i love you, they are so greedy :heart:
