### ISSUE TITLE
Proxy don't work.

### ISSUE THREAD

**Issue by kratess** [GeyserMC/MCProtocolLib#367]
See the title. Please fix it! If you have a fix write it.

**Comment by phase** [comment]
There isn't a proxy here. No proxies around here. This is a library for interfacing with Minecraft's protocol.

**This library is not a proxy**.

**Comment by kratess** [comment]
Not work connect with proxy socks

**Comment by phase** [comment]
**There is no proxy here. This is not a proxy.**

**Comment by 109C** [comment]
@phase There is a proxy here: https://github.com/Steveice10/MCProtocolLib/blob/master/example/com/github/steveice10/mc/protocol/test/MinecraftProtocolTest.java#L155

@kratess Bugs don't fix if reports don't report the issue at hand with enough detail.

**Comment by phase** [comment]
MCPL does allow for you to _use_ a proxy, but _it_ is not a proxy.

**Comment by kratess** [comment]
proxy like: new Proxy(Type.SOCKS, new InetSocketAddress("124.23.42.345", 10000)) not work :(

**Comment by kratess** [comment]
private static Proxy PROXY = new Proxy(Type.SOCKS, new InetSocketAddress("184.178.217.66", 3128));

not work

**Comment by phase** [comment]
Define "not work". I need more information then one line of code. More code and an actual error could help me solve your issue.

**Comment by kratess** [comment]
There are no errors but bots don't enter in server.

**Comment by phase** [comment]
That makes zero sense, but okay. Do you have any console logs? Any **_code_**? I can't fix code if I can't see it.

**Comment by kratess** [comment]
I haven't any logs. the code is this: https://hastebin.com/rupobadipi.cs

**Comment by phase** [comment]
It's probably the proxy you're using.

**Comment by kratess** [comment]
can you write a code for a proxy

**Comment by phase** [comment]
I could, but I'm not going to write a tool for you polish kids to unban yourselves.

**Comment by kratess** [comment]
... deh

**Comment by yooniks** [comment]
Maybe server what you trying to connect have a firewall or antiproxy?
@edit ugh code looks like shit

**Comment by Xayanix** [comment]
@phase they aren't making tool for unbaning themselves, they try to make proxy to crash other servers XD

**Comment by PoLsKiPaLaCz** [comment]
@Xayanix no wlasnie polskie robaczki pisza bo widzieli xproxy... sam pisze i sam nie ogarnialem ale po chuja tak wulgarnie pisac...
