### ISSUE TITLE
NullPointerException when join

### ISSUE THREAD

**Issue by MALW3R3** [GeyserMC/MCProtocolLib#368]
@Steveice10 When you join from 1.8.8 library to server 1.8-1.12 with ViaVersion you got NullPointerException, could you fix it ? (Probably problem with Chunks)

**Comment by Steveice10** [comment]
Old versions are not supported. It would be too much work to provide bugfixes for every single Minecraft version ever supported.

**Comment by MALW3R3** [comment]
@Steveice10 So can you give me clue what should i fix with chunks ? Because other people can easy join with that library to that server,and probably it's easy to fix

**Comment by phase** [comment]
The stack trace will provide you with details on what going wrong. You can clone the repo and follow the path to the code.

**Comment by yooniks** [comment]
Print stack trace and have fun :)
I fixed that, you have to edit mcprotocollib code.

Or use newest mcprotocollib's version.

And viaversion is not the only problem.

**Comment by MALW3R3** [comment]
@yooniks 
Could you explain what i should to change in library code? Which packet maybe ?
And newest version is 1.12 ye ? I would stay at currently version so change is dropped.

**Comment by MALW3R3** [comment]
@phase 
StackTrace of disconnect event just say me NullPointer Exception
@yooniks 
Which class i should rechange ?
