### ISSUE TITLE
1.8.8-1.12 Bug

### ISSUE THREAD

**Issue by MALW3R3** [GeyserMC/MCProtocolLib#369]
#### Question for only good programmers####
@phase @Steveice10 @w-o-a-h

Could you explain me what's wrong in 1.8.8 library that i can't join to 1.8-1.12 server with ViaVersion spigot 1.12 something bad with chunks i think (ServerChunkPacket).

**Comment by Inder00** [comment]
Old versions are not supported. To close

**Comment by MALW3R3** [comment]
@Inder00 
I know that but persons which i marked could explain that because they know that library very well.

**Comment by Xayanix** [comment]
Maybe you should take some java lessions if you can't fix simple null pointer exception for 3 days?

**Comment by Steveice10** [comment]
Not only are old versions not supported, but I also don't tend to deal with protocol hacks to support multiple client versions.

**Comment by MALW3R3** [comment]
@Steveice10 
Ok i understand you don't want support older version. But could you just look and tell what's to change with chunks to join multiple version it's just one error with chunks StackTrace tell me only NullPointerException
I would be grateful

**Comment by MALW3R3** [comment]
@Steveice10

**Comment by Xayanix** [comment]
Stop tagging him. We won't help you since you are using outdated version of library.

Pro tip: try to catch all exceptions in serverchunkdatapacket in write method. Maybe thrown stacktrace will help you to solve this simple problem. lmao

**Comment by PoLsKiPaLaCz** [comment]
@Xayanix very good english xd
