### ISSUE TITLE
Failed to read chunk data.

### ISSUE THREAD

**Issue by TrevorCow** [GeyserMC/MCProtocolLib#373]
This is a reopening of #198. It does, in fact, happen on the newest version. I can only get this to happen on bungee-cord servers and I think I know why. Many big servers (Hypixel) have an afk server, which is in the end but that's not the reason it's crashing. I think the reason its crashing is because since these servers are so big, they save cpu/mem by only loading small amounts of a map. When these fake chunks are sent to a real Minecraft client they are just ignored, rendering as void but when trying to parse these packets it crashes MCProtocolLib because a lot of chunk data is missing, throwing the "BitsPerEntry "0" is outside of accepted range." error. This could be fixed by just not throwing the error and ignoring the corrupted chunks (like Minecraft does) or by making a way to catch those errors. (I don't think you can catch it because it's fired by packet events)

**Comment by MALW3R3** [comment]
@TrevorCow 
I have that same problem and i'm looking for solution. If you know something, please write.

**Comment by TrevorCow** [comment]
Right now I just edited the source and added a try/catch to the chunk loading @MALW3R3

**Comment by MALW3R3** [comment]
@TrevorCow I tried that too but it did not work. I still have error NullPointerException with chunks. If you you'll fix it or you'll find what you need to fix write please

**Comment by TrevorCow** [comment]
Idk that worked for me @MALW3R3

**Comment by MALW3R3** [comment]
@TrevorCow Could you send me your .jar file please ? Could you give me your e-mail address ? 
which class did you edit?

**Comment by MALW3R3** [comment]
which class did you edit?

**Comment by TrevorCow** [comment]
ServerChunkDataPacket's read method

**Comment by MALW3R3** [comment]
@TrevorCow Idk i did it two days ago and it didn't worked...
Would you be so kind and send me your jar file, please ?

**Comment by MALW3R3** [comment]
@TrevorCow Or send me your ServerChunkDataPacket class

**Comment by MALW3R3** [comment]
@TrevorCow I added try/catch i write method's of this class and still NullPointerException !

**Comment by TrevorCow** [comment]
```
@Override
public void read(NetInput in) throws IOException {
	int x = in.readInt();
	int z = in.readInt();
	boolean fullChunk = in.readBoolean();
	int chunkMask = in.readVarInt();
	byte data[] = in.readBytes(in.readVarInt());
	CompoundTag[] tileEntities = new CompoundTag[in.readVarInt()];
	for(int i = 0; i < tileEntities.length; i++) {
		tileEntities[i] = NetUtil.readNBT(in);
	}
	try {
		this.column = NetUtil.readColumn(data, x, z, fullChunk, false, chunkMask, tileEntities);
	} catch (java.io.IOException ex) {
		ex.printStackTrace();
	}		
}
```

**Comment by MALW3R3** [comment]
@TrevorCow 
Oh you are using +1.8.8 version ?
Do you know how to fix it on 1.8.8 ?

**Comment by TrevorCow** [comment]
No sorry

**Comment by Steveice10** [comment]
Could you verify that [this commit](https://github.com/Steveice10/MCProtocolLib/commit/63e06fabadccee5fd2fd0a5a91ecba6a43e52eb1) fixes your problem?

**Comment by MALW3R3** [comment]
@Steveice10 
That doesn't exist in mcprotocollib 1.8.8 that class/function and field bitsPerEntry

**Comment by Steveice10** [comment]
That's because it's not for 1.8.8, it's for @TrevorCow's issue.

**Comment by TrevorCow** [comment]
I'm in class right now but I will run tests in a bit.

**Comment by TrevorCow** [comment]
Can verify that commit 63e06fabadccee5fd2fd0a5a91ecba6a43e52eb1 fixes #373. Can mark as resolved.

**Comment by Steveice10** [comment]
Great, thanks for testing. I believe the old behavior was a result of examining vanilla behavior back when the current chunk format was new, and that at some point it changed to what it does now.

**Comment by MALW3R3** [comment]
@phase @TrevorCow @w-o-a-h 
I can pay for fix chunks on 1.8.8

**Comment by TrevorCow** [comment]
Add me on discord TrevorCow#6124 @MALW3R3

**Comment by MALW3R3** [comment]
@TrevorCow 
I sent
