### ISSUE TITLE
Make MinecraftConstants edittable

### ISSUE THREAD

**Issue by Cubxity** [GeyserMC/MCProtocolLib#375]
@Steveice10 Please make MinecraftConstants NOT final.
I would like to edit protocol version, server version and more
so please don't make them Final

**Comment by Steveice10** [comment]
There is no reason to edit these. They are fixed for a given version of the library, and changing it will not magically make it work with a different Minecraft version.

**Comment by Cubxity** [comment]
minecraft console client can change protocol versions 🤷‍♂️

**Comment by phase** [comment]
You'd need a different version of the library, not a different number in a variable. Modifying the number at runtime won't do anything.

**Comment by Cubxity** [comment]
could u make th library contains multiple Protocol supports? im planning to make a huge project with this

**Comment by phase** [comment]
Just use two different versions of the library. Put them in different packages.

**Comment by Cubxity** [comment]
oh god. If i would use 1.7.10-1.12.2 protocols
I need to put like... how many ... ?

**Comment by phase** [comment]
How every many versions you want to support you would need versions of the library. I recommend targeting only one version.

**Comment by Cubxity** [comment]
I need to use it for multi versions, could you guys please add support for 1.7.10  -1.12.2

**Comment by phase** [comment]
Support for multiple versions will **never** be in the library. That would be a lot of code to write to support it.

**Comment by 0-x-2-2** [comment]
@VRCube if you are making a huge project already there is no need to use this just write it yourself then you can only implement the packets you need and can do multiversion. btw you can use reflection to change final fields

**Comment by Cubxity** [comment]
meh I'll make connection and handler myself then
