### ISSUE TITLE
use latest packetlib

### ISSUE THREAD

**Issue by DefinitlyEvil** [GeyserMC/MCProtocolLib#377]
it would be nice if we can use `packetSending()` event! ;)

**Comment by 0-x-2-2** [comment]
he does use it or should... just compile yourself if its not there

**Comment by DefinitlyEvil** [comment]
@w-o-a-h ofc i can, but I am suggesting this

**Comment by w-o-a-h** [comment]
It's using latest packetlib for me so...

**Comment by Steveice10** [comment]
Updated.

**Comment by DefinitlyEvil** [comment]
thanks!
