### ISSUE TITLE
Cannot resolve symbol NBTIO.

### ISSUE THREAD

**Issue by xdev-pl** [GeyserMC/MCProtocolLib#378]
Hi, i have problem with NetUtil class, it need NBTIO but the class doesn't exist in opennbt, i have the latest version of mcprotollib here's my pom.xml: https://hastebin.com/vusucupede.xml
https://imgur.com/a/dENFN

**Comment by Steveice10** [comment]
NBTIO exists: https://github.com/Steveice10/OpenNBT/blob/master/src/main/java/com/github/steveice10/opennbt/NBTIO.java

**Comment by xdev-pl** [comment]
I know but i only have "NBTIOUtils" etc. in opennbt lib, i think its downloading wrong version.

**Comment by Steveice10** [comment]
Then you should get the right version.
