### ISSUE TITLE
timeout problem?

### ISSUE THREAD

**Issue by DefinitlyEvil** [GeyserMC/MCProtocolLib#379]
by using the updated version, servers will tell that the client was timed out but it was just connected. 
maybe that has something to do with my implmentation of the API but i am not really sure. ;)

**Comment by Steveice10** [comment]
That's a bit vague. Could you provide more details, such as what you're trying to do, or possibly code snippets? Also, have you tried connecting to a different server?

**Comment by DefinitlyEvil** [comment]
hello, I'm sorry because that was my problem haha, I injected wrong value to LoginStartPacket xD thanks anyways
