### ISSUE TITLE
Problem when sending a ServerChunkDataPacket packet

### ISSUE THREAD

**Issue by leomelki** [GeyserMC/MCProtocolLib#380]
Hello, today i have a problem with the ServerChunkDataPacket packet.
I made some chunks by setting blocks on the BlockStorage, blocklight and skylight but when i am sending the packet to the client, some chunks are not rendered by it (but they exists (we can see the hitbox of the blocks but they don't render). Do you know what i did wrong ? Thanks you really much.
(I know this is probably not a problem of your fantastic lib but any help would be really nice 👍 )

**Comment by 109C** [comment]
Make sure you're sending enough chunks to fully load around the player.

**Comment by leomelki** [comment]
Yes, I tried to send a 16x16x16 block of chunks but it's not rendering properly :(

**Comment by leomelki** [comment]
Did you try this packet with a vanilla minecraft client ? I am on this problem for more than 2 days :,(

**Comment by Steveice10** [comment]
Does the solution in this issue apply to you? https://github.com/Steveice10/MCProtocolLib/issues/220

**Comment by leomelki** [comment]
No, i will send you a video tomorrow (some chunks are loading but the others doesn't). They aren't rendering but the client handle them. The hitbox of the block are here. It is really weird. Thanks you for replying

**Comment by leomelki** [comment]
Here is the video : https://youtu.be/pYPrXIiP588
Thank you very much

**Comment by 0-x-2-2** [comment]
you are sending the chunks wrong then i have been sending chunks perfectly fine and they work as intended

**Comment by leomelki** [comment]
w-o-a-h, can you send me how you send the chunks please ? I really don't know whats wrong with my code ^^
Thank you very much for responding !

**Comment by 0-x-2-2** [comment]
I have no idea what your issue is its most likely something todo with lazy chunks tho  http://wiki.vg/Protocol should help you

**Comment by leomelki** [comment]
I already spent much time on it ^^
I do something like:
 Create a chunk instance 
 Setting blocks in getBlocks(), getMetadata() and getSkyLight()
 Sending the chunks in multiple server chunk packets at the same time (1 packet for 1 colmun)

**Comment by Inder00** [comment]
To close

**Comment by PoLsKiPaLaCz** [comment]
@Inder00 utkaj pizde 11 latku
