### ISSUE TITLE
Suggestion: build.sh

### ISSUE THREAD

**Issue by MichelleWinters** [GeyserMC/MCProtocolLib#385]
Hello there,
Little suggestion to make it easier for newbies so to speak. I had no idea how to compile a maven package for a while. I managed to find the code to do it eventually. Here's what I suggest: A file called download.sh or build.sh with code:
`git clone https://github.com/Steveice10/MCProtocolLib.git`
 `cd MCProtoclLib`
 `mvn package`
  `echo "Done :)"`

**Comment by Steveice10** [comment]
It says in the README: run "nvm clean install" to build a jar.
