### ISSUE TITLE
Configure build path?

### ISSUE THREAD

**Issue by MichelleWinters** [GeyserMC/MCProtocolLib#386]
Get this error:
Multiple markers at this line
	- The type com.github.steveice10.mc.auth.exception.request.RequestException cannot be resolved. It is indirectly referenced 
	 from required .class files
	- The constructor MinecraftProtocol(String, String, boolean) refers to the missing type RequestException

when running code:
protocol = new MinecraftProtocol(username, password, false);

**Comment by Steveice10** [comment]
You should either add this library as a maven dependency in whatever build system you use, run 'mvn clean install' in the root of the repository to build a jar, or find a pre-built had to use.
