### ISSUE TITLE
Couple of things I cannot find

### ISSUE THREAD

**Issue by MichelleWinters** [GeyserMC/MCProtocolLib#387]
Hello there,
I am trying to find out how to do the following:
Respawn a player after recieving ServerEntityDestroyPacket
Make sure player takes knockback
and respawn player packet.

I don't expect the code to be written for me but links to where I may find the packet to work from or an answer that explains

**Comment by 109C** [comment]
http://wiki.vg/Protocol

It had a quite full list of packets.

**Comment by MichelleWinters** [comment]
I know it's 0x03 but I am unsure how to do that in MCProtocolLib? Also, ServerEntityDestroyPacket isn't picking up my player dying but it used to

**Comment by MichelleWinters** [comment]
Ok, found respawn.. And made a thing that detects death. Now just knockback and pushing etc

**Comment by Steveice10** [comment]
As @109C mentioned, http://wiki.vg/Protocol is a good resource for information on the protocol. The main intent behind MCProtocolLib is to provide the structures needed to use the protocol, and as such I don't generally provide much support on actually using it.
