### ISSUE TITLE
How to export proxy (autorskie)

### ISSUE THREAD

**Issue by nikodem218** [GeyserMC/MCProtocolLib#389]
How to export proxy (autorskie) in Eclipse

**Comment by szymex73** [comment]
http://lmgtfy.com/?q=eclipse+how+to+export+runnable+jar
OR if you're lazy: https://www.wikihow.com/Create-an-Executable-File-from-Eclipse

@Steveice10 Please close this

**Comment by kamcio96** [comment]
Lepiej sobie mózg zaimportuj

**Comment by ghost** [comment]
wypierdalać polacki

**Comment by ghost** [comment]
XDD

**Comment by PoLsKiPaLaCz** [comment]
`System.out.println("zabij sie");`

**Comment by yooniks** [comment]
@PoLsKiPaLaCz lol, lepiej popatrz na swoje posty tutaj
english: lol, maybe look at your posts/comments?
