### ISSUE TITLE
Better documentation of Proxy usage

### ISSUE THREAD

**Issue by bddvlpr** [GeyserMC/MCProtocolLib#391]
Unsure which argument does what.

For example:
`new TcpSessionFactory(proxy);`
and
`client.getSession().setFlag(MinecraftConstants.AUTH_PROXY_KEY, Proxy.NO_PROXY);`
and 
`MinecraftProtocol protocol = new MinecraftProtocol(username, password, false, proxy);`

Which one does what?

**Comment by Steveice10** [comment]
Passing a proxy to the TcpSessionFactory proxies the socket connection to the server. Passing a proxy as AUTH_PROXY_KEY proxies login verification with Mojang's servers when joining a server. Passing a proxy to the MinecraftProtocol constructor proxies the login request to Mojang's servers.

**Comment by bddvlpr** [comment]
Thanks!
