### ISSUE TITLE
Compiling MCProtocolLib

### ISSUE THREAD

**Issue by Tarasiu** [GeyserMC/MCProtocolLib#392]
Hi, sorry but I'm newbie. I'm trying to compile MCProtocolLib to jar. I know I must use Maven. When I trying  compiling this by maven I saw this error message https://hastebin.com/epegikumar.sql . What I must do to compile this?

**Comment by Steveice10** [comment]
This has nothing to do with MCProtocolLib. You need to install the Java JDK and/or have your environment variables properly set.
