### ISSUE TITLE
How to run proxy use eclipse

### ISSUE THREAD

**Issue by wda1234** [GeyserMC/MCProtocolLib#394]
english.
Hey.
How to run proxy use eclipse ?

does not work in a minecraft.
There is only a black hole.
And nothing shows

polska.
Hej mam problem nie działa mi proxy w eclipsie. xD Mam coś takiego że nie działają komendy i nic żadna komenda. Wbiłem ale nic się nie wyświetla jak czarna dziura. xD

**Comment by ghost** [comment]
XDDD

**Comment by wda1234** [comment]
zabij sie xD

**Comment by phase** [comment]
There is no proxy here.

**Comment by yooniks** [comment]
Here's example proxy: https://github.com/yooniks/CasualProxy
You can fork it, and change code :> (proxies ip and delay of bots connecting are broken, but I think u can fix it. I have fixed but I won't give that)
