### ISSUE TITLE
How to set block

### ISSUE THREAD

**Issue by UnixPL** [GeyserMC/MCProtocolLib#395]
Hello, I need set block on my server proxy, How i make it?  I use not supported version.

Dobra polskie kurwy jak postawić mam chuje blok na moim serwerze proxy spasione spaślaki kurwy wy jebane.

**Comment by koxlifeg** [comment]
little kid

**Comment by phase** [comment]
Read up on http://wiki.vg/Protocol

**Comment by yooniks** [comment]
chunks?
