### ISSUE TITLE
HOW TO DOWNLOAD MINECRAFT, JAVA AND MCPROTOCOLLIB?

### ISSUE THREAD

**Issue by KrafciG** [GeyserMC/MCProtocolLib#401]
HOW TO DOWNLOAD MINECRAFT, JAVA AND MCPROTOCOLLIB?
I DON'T KNOW.
(link please)
(and tutorial)   

                                                                                                                        (jebane Polskie kurwy to fake xD)
                                                                                                                                          (dla beki)

**Comment by KrafciG** [comment]
HOW TO DOWNLOAD MINECRAFT, JAVA AND MCPROTOCOLLIB?
I DON'T KNOW.
(link please)
(and tutorial)

**Comment by phase** [comment]
Google it. No one is going to hand you knowledge on a silver platter. You need to work for it.

**Comment by koxlifeg** [comment]
download mcprotocollib and compilate it ;)

**Comment by UnixPL** [comment]
go commit die.

**Comment by Versi0** [comment]
XDDDDDDDDDDDDDDDDDDDDDDDDDDD
