### ISSUE TITLE
Import using maven

### ISSUE THREAD

**Issue by Sapu98** [GeyserMC/MCProtocolLib#402]
Hi, I've been trying to import the project using maven, I have never used maven before, so im not sure if i did it in the right way cuz the project is full of errors...  I was wondering if you could tell to me how to do it properly x)

**Comment by Steveice10** [comment]
I would recommend looking up information on how to use maven. This issue tracker is for reporting library bugs.

**Comment by kompiuterkamerka** [comment]
mcprotocolib import plase help
in eclipse
