### ISSUE TITLE
MCProtocolib

### ISSUE THREAD

**Issue by kompiuterkamerka** [GeyserMC/MCProtocolLib#404]
create proxy server

**Comment by kompiuterkamerka** [comment]
add crashers to proxy

**Comment by phase** [comment]
This place is for issues about the library, not about proxies or whatever you’re doing. 

Can you tell me where you kids are coming from? I’d like to post *something* to indicate to people that this isn’t the place to go.

**Comment by kompiuterkamerka** [comment]
Place server proxy

wt., 22 maj 2018, 17:12 użytkownik Jadon Fowler <notifications@github.com>
napisał:
