### ISSUE TITLE
How to make so bot will connect with different ip?

### ISSUE THREAD

**Issue by DrOreo002** [GeyserMC/MCProtocolLib#409]
Title say it all

**Comment by Steveice10** [comment]
Title doesn't really say much... What do you mean different IP? If you want the server to think you're connecting from a different IP than your real one, you'll need to use a proxy.

**Comment by DrOreo002** [comment]
Yes, I mean so the bot will connect using a different ip than the real one. Do you know any tutorial for using proxy and stuff?

**Comment by DrOreo002** [comment]
It always said connection timed out for no reason. This is my code to create the proxy
`public static Proxy connectToVpn() {
		SocketAddress socket = new InetSocketAddress("42.104.84.107", 8080);
		return new Proxy(Proxy.Type.SOCKS, socket);
	}`

**Comment by 0-x-2-2** [comment]
It says timed out because the proxy you are using is slow

**Comment by DrOreo002** [comment]
Really?. Can I know any fast proxy?

I've tried 10 or maybe 20 proxy on this website https://www.socks-proxy.net ,  but none of them seems to be working
