### ISSUE TITLE
InvalidCredentialsException: Invalid token

### ISSUE THREAD

**Issue by perseus5** [GeyserMC/MCProtocolLib#410]
Hello, I'm running into an issue with invalid token while running it on my computer. I've grabbed the accessToken from launcher_profiles.json inside my Minecraft folder, booted the bot up, and it threw that error. At first I was just using email and password but I ran into the issue where I was being blocked by Mojang if I kept on making successful attempts by booting the bot up to test things? That doesn't make sense at all but it happened. That's why I switched over to using the accessToken instead. I can launch my Minecraft with that token inside the launcher, but using it in the bot doesn't work? Another thing I've tried is using email and pass, authenticate, print out the token, then reboot the bot back up with that token. Still didn't work. Not sure on the next step I should take, thanks 😃

**Comment by Steveice10** [comment]
When you log in with a token, the token is invalidated, and the client is issued a new one. Make sure you're grabbing the new token whenever the old one expires.

**Comment by perseus5** [comment]
Is that not what I'm doing when I authenticate with the pass, log the token, and then log back in with the token?

**Comment by Steveice10** [comment]
Do you happen to be using a proxy?

**Comment by perseus5** [comment]
Nope, proxy is set to Proxy.NO_PROXY. And I'm not behind any proxy myself. 

Do you think it's because I'm starting and stopping the jar? 

Here's what I'm doing:
1. Authenticate with password
2. Print the token
3. Stop the jar
4. Authenticate with token
5. Throws Invalid token

Is that what I'm supposed to be doing?

Also, have you had issues with being blocked my Mojang for constant correct attempts? is that actually a thing?

**Comment by Steveice10** [comment]
I honestly haven't done much with this library or Minecraft in general for a long while now; I just pop in to address bug reports and what not from time to time. All I can really be sure of here is that the auth servers don't like the token you're giving it, for some reason.

Can you elaborate on how you're retrieving and printing the auth token? Just to make sure you're getting a good token in the first place.

**Comment by perseus5** [comment]
Ah, well I appreciate you still keeping this active, it's a very cool project!

Here's how I'm connecting: 
(Protocol extends MinecraftProtocol)
Protocol protocol = new Protocol(credentials.getEmail(), credentials.getPassword(), false);
System.out.println(protocol.getAccessToken());

// Create client, set flags, etc, connect

This all works, because connecting to an online-mode server works just fine. So I just grab that token that was printed, stop the jar, change that line to:

Protocol protocol = new Protocol(credentials.getEmail(), "token", true);

boot it up, and that throws invalid token

**Comment by perseus5** [comment]
Sweet, it works! Unfortunately, you can only use it once before it says invalid token again. Any ideas?

**Comment by Steveice10** [comment]
Glad it's fixed. Like I mentioned earlier, you have to re-save the access token each time as it gets invalidated and re-issued when used.

**Comment by perseus5** [comment]
Sounds good, thanks for the help!
