### ISSUE TITLE
Internal network exception.

### ISSUE THREAD

**Issue by phoemeister** [GeyserMC/MCProtocolLib#413]
Hi, I'm trying send 1 bot to server and bot connect, but bot instantly disconnect. Disconnect reason is "Internal network exception.",
My logs: https://pastebin.com/Mpzmuhkx

**Comment by phoemeister** [comment]
I wanna add when I connect (bot forwards packets to me, and I to him) = same situation

**Comment by mikroskeem** [comment]
`java.lang.AbstractMethodError` there indicates that something is wrong with the netty inbound handler... if you haven't done anything with netty then you should check what version MCProtocolLib is using and what version you are providing on runtime.

**Comment by phoemeister** [comment]
fixed thanks.
