### ISSUE TITLE
Enhancement: Expose server address from client's handshake

### ISSUE THREAD

**Issue by mikroskeem** [GeyserMC/MCProtocolLib#414]
See [wiki.vg](http://wiki.vg/Protocol#Handshake)

**Comment by mikroskeem** [comment]
Clarification: Yes, one can add listener to grab this data from `HandshakePacket`, but having this available as a session flag would be great as well.

**Comment by 0-x-2-2** [comment]
it would be doing that internally so what is the difference

**Comment by mikroskeem** [comment]
What do you mean by internally?

**Comment by 0-x-2-2** [comment]
https://github.com/Steveice10/MCProtocolLib/blob/master/src/main/java/com/github/steveice10/mc/protocol/ServerListener.java

**Comment by Steveice10** [comment]
You really should just listen for a HandshakePacket; that's what MCProtocolLib would be doing itself to implement this, anyway.

**Comment by mikroskeem** [comment]
I was thinking that since [ServerListener.java#L66](https://github.com/Steveice10/MCProtocolLib/blob/master/src/main/java/com/github/steveice10/mc/protocol/ServerListener.java#L66) was already listening for it, then it could be easy to expose that information.
