### ISSUE TITLE
Problem with display nbt tag on item

### ISSUE THREAD

**Issue by idrizdi** [GeyserMC/MCProtocolLib#415]
ScreenShot: https://imgur.com/LAxdLcW
2 tags but not applied
My code: https://hastebin.com/urukihocid.js
The same with adding name to item 1nbt tag but nothing happen
@Steveice10

**Comment by UnixPL** [comment]
@Steveice10 close this.

**Comment by UnixPL** [comment]
Your code causes me a headache.
