### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by torasan0131** [GeyserMC/MCProtocolLib#418]
public static ArrayList<Integer> playeritem;

public void packetReceived(final PacketReceivedEvent event) {
if (autoez.Bot.goanni == true && event.getPacket() instanceof ServerSetSlotPacket && !PlayerListener.items.contains(((ServerSetSlotPacket) event.getPacket()).getItem())) {
	PlayerListener.playeritem.add(((ServerSetSlotPacket) event.getPacket()).getItem().getId());
}
PlayerListener.playeritem = new ArrayList<Integer>();
}
Why does this happen?

**Comment by ghost** [comment]
Why are you initializing the ArrayList after `PlayerListener.playeritem.add(((ServerSetSlotPacket) event.getPacket()).getItem().getId());`? I think that's causing the NullPointerException.
