### ISSUE TITLE
why java.lang.NullPointerException

### ISSUE THREAD

**Issue by leaking810** [GeyserMC/MCProtocolLib#421]
`public class PlayerListener
{
    private Server server;
    private boolean debug;
    public static ArrayList<Integer> items;
    public static ArrayList<String> playeritem;
    public static int windowId;
    
    public PlayerListener(final Server server) {
        this.debug = false;
        this.server = server;
    }
    
    
    public void addDefaultListeners(final Player player) {
        player.addListener(new SessionAdapter() {
            @Override
            public void packetReceived(final PacketReceivedEvent event) {
                if (event.getPacket() instanceof ServerKeepAlivePacket) {
                    event.getSession().send(new ClientKeepAlivePacket(((ServerKeepAlivePacket) event.getPacket()).getPingId()));
                }
                else if (event.getPacket() instanceof ServerChatPacket) {
                    System.out.println(((ServerChatPacket) event.getPacket()).getMessage().getFullText());
                }
                else if (event.getPacket() instanceof ServerPlayerHealthPacket) {
                    if (((ServerPlayerHealthPacket) event.getPacket()).getHealth() <= 0.0f) {
                        event.getSession().send(new ClientRequestPacket(ClientRequest.RESPAWN));
                    }
                }
                else if (event.getPacket() instanceof ServerOpenWindowPacket) {
                    PlayerListener.windowId = ((ServerOpenWindowPacket) event.getPacket()).getWindowId();
                    PlayerListener.items.clear();
                    PlayerListener.items = new ArrayList<Integer>();
                }
                else if (event.getPacket() instanceof ServerCloseWindowPacket) {
                    PlayerListener.items.clear();
                    PlayerListener.items = new ArrayList<Integer>();
                }
                else if (event.getPacket() instanceof ServerSetSlotPacket && !PlayerListener.items.contains(((ServerSetSlotPacket) event.getPacket()).getSlot())) {
                    PlayerListener.items.add(((ServerSetSlotPacket) event.getPacket()).getSlot());
                }
                else if (event.getPacket() instanceof ServerSetSlotPacket) {
                	autoez.player.PlayerListener.playeritem.clear();
                	PlayerListener.playeritem.add(((ServerSetSlotPacket) event.getPacket()).getItem().toString());
                	System.out.println(((ServerSetSlotPacket) event.getPacket()).getItem().toString());
                }
            }
                 
            @Override
            public void packetSent(final PacketSentEvent event) {
                if (PlayerListener.this.debug) {
                    System.out.println(event.getPacket().toString());
                }
            }
            
            @Override
            public void disconnected(final DisconnectedEvent event) {
                PlayerListener.this.server.playerList.remove(player);
                System.out.println(player.getCredentials().getLoginName() + " disconnected. Reason: " + event.getReason());
            }
        });
    }
    
    
    
    static {
        PlayerListener.items = new ArrayList<Integer>();
        PlayerListener.playeritem = new ArrayList<String>();
        PlayerListener.windowId = 0;
    }
}`
disconnected. Reason: java.lang.NullPointerException

**Comment by Steveice10** [comment]
Please provide the stack trace of the exception returned by DisconnectedEvent.getCause()

**Comment by leaking810** [comment]
`            @Override
            public void disconnected(final DisconnectedEvent event) {
                PlayerListener.this.server.playerList.remove(player);
                System.out.println(player.getCredentials().getLoginName() + " disconnected. Reason: " + event.getReason());
                System.out.println(event.getCause());
            }
        });
    }`
disconnected. Reason: java.lang.NullPointerException
java.lang.NullPointerException

**Comment by leaking810** [comment]
Reason: java.lang.NullPointerException
java.lang.NullPointerException
	at autoez.player.PlayerListener$1.packetReceived(PlayerListener.java:57)
	at com.github.steveice10.packetlib.event.session.PacketReceivedEvent.call(PacketReceivedEvent.java:51)
	at com.github.steveice10.packetlib.tcp.TcpSession.callEvent(TcpSession.java:142)
	at com.github.steveice10.packetlib.tcp.TcpSession$3.run(TcpSession.java:335)
	at java.lang.Thread.run(Unknown Source)

**Comment by leaking810** [comment]
PlayerListener.java:57 is 
`PlayerListener.playeritem.add(((ServerSetSlotPacket) event.getPacket()).getItem().toString());`

**Comment by Steveice10** [comment]
You need to check if getItem() returns a null value; this happens when the window slot is empty.
