### ISSUE TITLE
Unable to build source

### ISSUE THREAD

**Issue by Quois** [GeyserMC/MCProtocolLib#422]
When trying to build this source, I get an error.
![image](https://user-images.githubusercontent.com/30718500/44103150-c398c5d6-9feb-11e8-961f-40f66e37c245.png)
 When researching this error the only information I get is that "the error is reported in case the execution of a plugin failed due to some unforeseen event." and that you should contact the maintainer of the plugin quoted from https://cwiki.apache.org//confluence/display/MAVEN/PluginExecutionException. I'd love to know if there are any solutions to this or maybe if someone could like me the build. Thanks!

**Comment by Quois** [comment]
![image](https://user-images.githubusercontent.com/30718500/44137193-c8625b34-a06f-11e8-8848-e8b3d1967dba.png)

Tell me if you want the full stack trace of the errors or debug log.

**Comment by Steveice10** [comment]
In pom.xml, could you try changing the maven-surefire-plugin version to "2.22.0"? Apparently there's an incompatibility with Java 10 in the version currently used.

**Comment by Quois** [comment]
It worked, thank you so much!

**Comment by Steveice10** [comment]
Great, I'll make sure to update the plugin version across my repositories tomorrow.
