### ISSUE TITLE
Bot doesn't join game

### ISSUE THREAD

**Issue by Quois** [GeyserMC/MCProtocolLib#423]
I have used some of the example code to make a simple bot in a window application but when I click the button that's supposed to make the bot join the game, I get an error. 
![image](https://user-images.githubusercontent.com/30718500/44253368-aca49600-a1ff-11e8-9b6c-4b1ee6fa0d4a.png)
Source code: https://pastebin.com/uAC4pggZ

**Comment by Steveice10** [comment]
Gson is required by MCAuthLib, which is used by MCProtocolLib, but it doesn't seem to be present in your classpath. Make sure your build environment is set up with proper dependency management.
