### ISSUE TITLE
Raw data handling

### ISSUE THREAD

**Issue by ShayBox** [GeyserMC/MCProtocolLib#430]
Add raw data sending/receiving as an alternative to the lib handling packets.
Useful for making proxies, or if you don't need the overhead of the lib handling packets.

Maybe instead of adding a SessionAdapter listener, a RawAdapter listener, or something, Idk, not that much of a java dev.

**Comment by Steveice10** [comment]
The entire purpose of the library is to parse the protocol data. Raw data is outside of its scope, and frankly I don't see why you'd need the library at all to simply forward raw socket data.

**Comment by ShayBox** [comment]
To handle making the connection and construct servers and clients, rather than having to re-write a ton of code from the lib in my project, a simple listener that doesn't handle the data internally seems a lot easier.
