### ISSUE TITLE
Problem with dependencies 

### ISSUE THREAD

**Issue by Catzy44** [GeyserMC/MCProtocolLib#432]
MCProtocolLib is not building with dependencies.

To build with dependencies i need to add this (https://pastebin.com/DxpKjnMZ) to pom.xml, and then use "mcprotocollib-1.13.1-1-SNAPSHOT-jar-with-dependencies" file.

**Comment by Steveice10** [comment]
MCProtocolLib doesn't include dependencies in the JAR; usually, one would use an IDE or build tool that resolves all the necessary dependencies automatically.

**Comment by Catzy44** [comment]
Some time ago MCProtocolLib contained all dependencies, and i was confused after an update :D

**Comment by Catzy44** [comment]
The jar file doesn`t include basic dependencies like java.io etc.

**Comment by Steveice10** [comment]
It isn't supposed to, that's part of the Java standard library.

**Comment by Catzy44** [comment]
But when i try to run app i get "Class not found exception: java.io..."

**Comment by Steveice10** [comment]
There may be something wrong with your Java environment then, or how you're running your application.
