### ISSUE TITLE
Getting skin and cape after authorization

### ISSUE THREAD

**Issue by TheQmaks** [GeyserMC/MCProtocolLib#440]
It realizable?

**Comment by TheQmaks** [comment]
It can be parsed after auth by URL https://sessionserver.mojang.com/session/minecraft/profile/uuid
https://wiki.vg/Mojang_API#UUID_-.3E_Profile_.2B_Skin.2FCape

**Comment by Steveice10** [comment]
As described in that documentation, you should already be able to retrieve this information by getting the logged in GameProfile's properties. See https://github.com/Steveice10/MCAuthLib/blob/master/src/main/java/com/github/steveice10/mc/auth/data/GameProfile.java#L90

**Comment by TheQmaks** [comment]
It not work :/

**Comment by TheQmaks** [comment]
I've modified com.github.steveice10.mc.auth.util.HTTP.makeRequest(Proxy proxy, String url, Object input, Class<T> clazz) for printing response json and it not contains anything. All profile and texture information must be parsed from sessionserver by user UUID.

**It from Mojang authlib 1.5.25**
![image](https://user-images.githubusercontent.com/11361354/49937660-29126180-fee0-11e8-9296-09aa77f088af.png)
com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillGameProfile(GameProfile profile, boolean requireSecure)

**Comment by Steveice10** [comment]
I will look into implementing that, then.

**Comment by TheQmaks** [comment]
Ha-ha. It realized in com.github.steveice10.mc.auth.service.fillProfileProperties(GameProfile profile).
Just not used.
