### ISSUE TITLE
How to Respawn

### ISSUE THREAD

**Issue by MGW14** [GeyserMC/MCProtocolLib#441]
Hey, i tried for hours to Respawn the Player.
There are much other Issues, but i dont understand how to Respawn.

My Code:
`
public void packetReceived(PacketReceivedEvent event) {
    if (event.getPacket() instanceof ServerPlayerHealthPacket) {
        if (health <= 0.0) {
            if (((MinecraftProtocol) event.getSession().getPacketProtocol()).getSubProtocol() == SubProtocol.GAME) {
                client.getSession().send(new ServerRespawnPacket(dimension, difficulty, gamemode, worldType));
            }
        }
    }
}
`

Thanks for your help and sry for my really bad English

**Comment by phase** [comment]
Packets prefixed with `Server` are packets that are coming _from_ the server and going _to_ the client. The correct packet your client should send is a `ClientRequestPacket` with `ClientRequest.RESPAWN`.

Here's what I had in my bot:
https://github.com/phase/PhaseBot/blob/cc4302c642582ffe2dea2689483dbc69d87a623f/src/xyz/jadonfowler/phasebot/PacketHandler.java#L73-L77

**Comment by MGW14** [comment]
Yes it works. Thank you.
