### ISSUE TITLE
Ambiguous exmaples

### ISSUE THREAD

**Issue by Revxrsal** [GeyserMC/MCProtocolLib#446]
The single example provided is pretty ambiguous. If more documentation was provided for fields and lines 
it would clear a lot of things up. Also please split the example class into separate classes, in which every class shows an example usage of a concept from the library. It's very hard to understand which is which. Please provide better examples which are better-documented. Thanks!

**Comment by Steveice10** [comment]
The example is intended to show basic usage of the library, such as creating servers and clients or receiving and sending packets. As for the actual packet protocol, http://wiki.vg/ is already a great resource.
