### ISSUE TITLE
how to convert ItemStack.id to MC.id

### ISSUE THREAD

**Issue by mtricolici** [GeyserMC/MCProtocolLib#450]
Hi guys, I handle ServerSetSlotPacket packet and get ItemStack

but ItemStack.id (integer) has strange values, for example:

id=568 is for fishing rod, but it should be 346 
id=484 is for iron sword, but it should be 267

How to convert ItemStack.id to MC.id ?

Thanks

**Comment by 0-x-2-2** [comment]
568 is the internal item id. static item ids got removed in 1.13

**Comment by mtricolici** [comment]
thanks for reply 0-x-2-2. Where can I find internal item IDs of all items in 1.13? thanks
or how to detect that a specific ItemStack is a finshing rod ? (As I understand this id is not a static one anymore). I can't find official documentation anywhere.

**Comment by Steveice10** [comment]
Closing as not a bug.

**Comment by melluh** [comment]
Trying to figure out the same: Would like some assistance with this. I can't find any documentation anywhere.

**Comment by melluh** [comment]
I've figured this out. To get a JSON list of all IDs, run the following command in the same directory as a Notchian minecraft server.
`java -cp minecraft_server_1.13.2.jar net.minecraft.data.Main --all`
Then open generated/reports/index.json.

**Comment by mtricolici** [comment]
@MisterMelDev thank you for sharing this!

**Comment by NekoEpisode** [comment]
> I've figured this out. To get a JSON list of all IDs, run the following command in the same directory as a Notchian minecraft server. Then open generated/reports/index.json.`java -cp minecraft_server_1.13.2.jar net.minecraft.data.Main --all`

How to get it on Minecraft 1.21?
Thank you

**Comment by NekoEpisode** [comment]
> > I've figured this out. To get a JSON list of all IDs, run the following command in the same directory as a Notchian minecraft server. Then open generated/reports/index.json.`java -cp minecraft_server_1.13.2.jar net.minecraft.data.Main --all`
> 
> How to get it on Minecraft 1.21? Thank you

I found a way, open the server's jar file and edit the text in META-INF/main-class to net.minecraft.data.Main, then use java -jar (your server.jar) --reports, and you're going to get it
