### ISSUE TITLE
New Error

### ISSUE THREAD

**Issue by xiaonian233** [GeyserMC/MCProtocolLib#454]
When I login in the server I got https://hastebin.com/henusumuza.css
1.13.2

**Comment by ghost** [comment]
MCProtocolLib is currently undergoing an update to 1.14, which is not backwards compatible, nor does this try to support multiple versions. Your best bet would be to fork this repo before the commits that begin the transition to 1.14, download the source and build from it.

**Comment by xiaonian233** [comment]
I see,thx

**Comment by Steveice10** [comment]
Bug fixes to 1.13.2 will still be applied until the 1.14 update is finished, tested, and merged.

Not sure why the server is trying to spawn entity ID 85 (WitherSkull) with a spawn mob packet, but apparently the client is supposed to accept that, so I went and added all the missing entity IDs to MobType. That should fix the issue.
