### ISSUE TITLE
Making player login (extremely new)

### ISSUE THREAD

**Issue by vanshyadav17** [GeyserMC/MCProtocolLib#456]
Hey!
I'm new to this api, Im trying to make a player login, how do I do this with the API

I'm hopelessly lost...

I've understood authenticating users and getting their access token etc.

**Comment by TheSnoozer** [comment]
Maybe the [example](https://github.com/Steveice10/MCProtocolLib/blob/master/example/com/github/steveice10/mc/protocol/test/MinecraftProtocolTest.java) helps :-)

**Comment by Steveice10** [comment]
As mentioned, the example is a good starting resource for using the library. A good resource for the protocol in general is https://wiki.vg/Main_Page
