### ISSUE TITLE
All minecraft version

### ISSUE THREAD

**Issue by LoSunny** [GeyserMC/MCProtocolLib#468]
Can I know which version of MCProtocolLib supports 1.13 & 1.14? https://github.com/Steveice10/MCProtocolLib/releases

**Comment by Steveice10** [comment]
Apparently I never ended up tagging a 1.13 release, my bad. Here's the last commit before 1.14: https://github.com/Steveice10/MCProtocolLib/commit/75697372405d74dd84656ccd72f20975bbecba62

For 1.14, just use the latest commit for now. I'll make sure to tag a release sometime soon.

**Comment by LoSunny** [comment]
Can you make it in https://github.com/Steveice10/MCProtocolLib/releases ?

**Comment by LoSunny** [comment]
Also for 1.8 and 1.8.8
