### ISSUE TITLE
Ability to customize the library more

### ISSUE THREAD

**Issue by Cubxity** [GeyserMC/MCProtocolLib#470]
Hey there,

 I would like to be able to customize how the library functions more. F.ex not forcing to add the default "ClientListener" and "ServerListener" to make it barebone packet library. And I've been getting these exceptions and it closes the connection:

- `Caused by: java.lang.IllegalArgumentException: Key 0 has no mapping for value class com.github.steveice10.mc.protocol.data.game.entity.player.Hand.` 
- `io.netty.handler.codec.DecoderException: java.lang.IllegalStateException: Packet "ClientBlockNBTRequestPacket" not fully read.`

It would be nice to be able to configure that the library should just ignore that packet or throw the exception.

**Comment by Cubxity** [comment]
Bump @Steveice10

**Comment by Steveice10** [comment]
I have taken note and will address this sometime soon when I have the time. I'll see about adding an option to not register the standard listeners, but I don't plan on supporting ignoring errors as I'd rather they be reported and addressed.

**Comment by Steveice10** [comment]
Added.
