### ISSUE TITLE
IllegalArgumentException when joining Hypixel

### ISSUE THREAD

**Issue by lukeeey** [GeyserMC/MCProtocolLib#474]
```
io.netty.handler.codec.DecoderException: java.lang.IllegalArgumentException: Key 0 has no mapping for value class com.github.steveice10.mc.protocol.data.game.entity.player.Hand.
```

```
io.netty.handler.codec.DecoderException: java.lang.IllegalArgumentException: Value 1039 has no mapping for key class com.github.steveice10.mc.protocol.data.game.world.effect.WorldEffect
```

**Comment by Steveice10** [comment]
Are you using the latest version? That shouldn't happen if so.

**Comment by lukeeey** [comment]
Hmm thats weird, i did update and it fixed that error but i got a different error which doesnt seem to happen now

**Comment by lukeeey** [comment]
Ive just randomly saw this while i was doing other things 
![image](https://user-images.githubusercontent.com/32024335/62411643-1f17ad00-b5ee-11e9-9507-1e97f396aa1c.png)

**Comment by lukeeey** [comment]
Also i get this occationally 
```
`io.netty.handler.codec.DecoderException: java.lang.IllegalArgumentException: Key 0 has no mapping for value class com.github.steveice10.mc.protocol.data.game.entity.player.Hand.
```

**Comment by lukeeey** [comment]
Ive just started getting the error on my local spigot server so its not just a Hypixel issue

**Comment by Steveice10** [comment]
Can you check if it's working okay with the PRs I just merged?

**Comment by lukeeey** [comment]
It is a random occurrence (or i just dont know what causes it to occur) but ill tell you if i see the errors again.

Will it automatically update on maven?

**Comment by Steveice10** [comment]
Going to assume this ended up fixed.
