### ISSUE TITLE
Is a player state missing?

### ISSUE THREAD

**Issue by lukeeey** [GeyserMC/MCProtocolLib#478]
Looking at the PlayerState enum and with my knowledge of the Bedrock edition protocol, it seems weird that theres not a `STOP_ELYTRA_FLYING` value. Is there supposed to be one or not?

https://github.com/Steveice10/MCProtocolLib/blob/master/src/main/java/com/github/steveice10/mc/protocol/data/game/entity/player/PlayerState.java#L12-L13

**Comment by Steveice10** [comment]
According to the protocol wiki, there is not: https://wiki.vg/Protocol#Entity_Action

If you find anything suggesting otherwise, though, let me know and I can fix it.
