### ISSUE TITLE
Android: Connection timed out when connecting to external Server

### ISSUE THREAD

**Issue by ggmoritz** [GeyserMC/MCProtocolLib#486]
MCProtocolLib works fine on Android when connecting to a server running in the local wifi network. However, when connecting to external server ips the connection always times out. I tried multiple servers, all are working fine in the original client. Those servers are all compatible with 1.14.4. I can even use PickaxeChat to connect to that server on the same phone without any issues. I added the internet connection to manifest.

**Comment by Steveice10** [comment]
Have you checked that MCProtocolLib works to connect to these servers on a PC?

**Comment by ggmoritz** [comment]
@Steveice10 Yes, I did. It works perfectly fine on my PC with MCProtocolLib. I'm using the same servers, the same SessionAdapter and the same account.

**Comment by Steveice10** [comment]
And there's nothing on your device or in your app that might be interfering with the connection, like maybe a proxy? MCProtocolLib doesn't differentiate between local and remote connections in any way, so I'm not sure how this could be something its causing.

**Comment by ggmoritz** [comment]
@Steveice10 The only thing that might interfere with my connection in any way is my Adblocker, but it works fine with PickaxeChat. I disabled the adblocker and still get the same issue.  
It gets even stranger. One of the servers I tried yesterday now kicks me for "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: SB-Hub.com/104.128.57.82:25565".  
My guess is that there is either A) something is horribly wrong with my phone. I'll check it on another and keep you updated or B) I'm missing some permission or system restriction preventing me from accessing external servers.

**Comment by ggmoritz** [comment]
@Steveice10 Update: Same issue on my other phone. Both run pie tho.

**Comment by ggmoritz** [comment]
@Steveice10 Update 2: I found a single cracked server that works fine on my phone: "playmc.games".

**Comment by 0-x-2-2** [comment]
sounds like a protocol encryption issue 🤔

**Comment by Steveice10** [comment]
Don't think an encryption issue would cause connection timeouts. "Single cracked server" also implies to me that there were other cracked servers that didn't work. Let me know if that's not the case, though.

**Comment by ggmoritz** [comment]
@Steveice10 Any update? Have you tried it on Android yet?

**Comment by Steveice10** [comment]
I don't have a setup for testing on Android or really the time to put one together at the moment. I can say though that MCProtocolLib shouldn't have any part in differentiating between local servers and remote servers.

**Comment by ggmoritz** [comment]
@Steveice10 I think I found the root cause. It wasn't because premium, cracked, remote or local. The server(s) I'm trying to connect to uses **IPv6**. Now I could find that most servers are actually working, because IPv4 is way more common.   
  
Edit: The server domain (skyblock.net) is also a webpage. I guess that it might be important for the timeout.

Edit 2: **I FOUND THE ISSUE!** My PC was able to resolve the correct IP address for minecraft, which also worked on my phone. However MCProtocolLib on Android resolves an incorrect IPv6 address (probably the website)

**Comment by Steveice10** [comment]
Okay. Probably something to do with https://github.com/Steveice10/PacketLib/blob/master/src/main/java/com/github/steveice10/packetlib/tcp/TcpClientSession.java#79 then. I'll take a look at this domain when I have the chance.

**Comment by ggmoritz** [comment]
@Steveice10 I forgot to tell you: The actual server IP is IPv4 (the website was IPv6). I thought the server was IPv6 because McProtocolLib looked up the wrong address (but only on my phone).  

Sorry if I'm repeating myself, but I want to get of any misunderstanding.

**Comment by Steveice10** [comment]
Okay. I'll still try to take a look and see what the code is resolving and why.

**Comment by 0-x-2-2** [comment]
Add this to your entry point.

```java
System.setProperty("java.net.preferIPv4Stack", "true");
```

Afaik the official Minecraft client also does this.

**Comment by ggmoritz** [comment]
@o-x-2-2 wouldnt that also affect the rest of the application?

**Comment by 0-x-2-2** [comment]
> @o-x-2-2 wouldnt that also affect the rest of the application?

Correct but it should not be an issue at all.

**Comment by ggmoritz** [comment]
@0-x-2-2 Bad practice tho. Better explicitly specify when making the request. Also, when I use cmd to get the IPv4 from skyblock.net it returns an invalid IPv4 address. Minecraft must do something else different.

**Comment by 0-x-2-2** [comment]
Anything that requires IPv6 will still work in fact as I said before the official Minecraft client and old Java Launcher also does this. You only get this issue because it is trying to use the IPv6 IP that they don't have Minecraft on because Java Edition does not support IPv6 natively.

**Comment by ggmoritz** [comment]
@0-x-2-2 Still, it is a bad idea for a library to affect the rest of the application.

**Comment by 0-x-2-2** [comment]
> @0-x-2-2 Still, it is a bad idea for a library to affect the rest of the application.

I'm not saying the library should do this I am saying you should do this. This is also the functionality of the regular Minecraft client.

**Comment by ggmoritz** [comment]
@0-x-2-2 Oh, thats what you mean. I'll try.

**Comment by ggmoritz** [comment]
@0-x-2-2 Sorry for letting you wait that long, but I wanted to let you know that preferIPv4Stack doesn't make any difference.

**Comment by Steveice10** [comment]
Sorry for the long wait. If this is still an issue for you, could you try the latest source version? I made a change to PacketLib that could help with servers that use SRV DNS records.

**Comment by ggmoritz** [comment]
@Steveice10 The issue is still there with the latest commit. A combination with preferIPv4stack also doesn't work.

**Comment by Steveice10** [comment]
Is this still an issue with the latest MCProtocolLib? Just checking in since it's been quite a while.

**Comment by Steveice10** [comment]
Assuming fixed or otherwise no longer an issue due to lack of response.

**Comment by ggmoritz** [comment]
@Steveice10 Sorry I completely forgot about this issue. I was using a numeric IP as a workaround. I just checked the latest version (1.15-1) and the issue is still there. The phone resolves the wrong IP, probably from the website.

**Comment by Steveice10** [comment]
Could you try the latest MCProtocolLib/PacketLib? I think the issue may have been Android not supporting the method I used to do the SRV DNS lookup, so I've changed over to a library that should work.

**Comment by ggmoritz** [comment]
@Steveice10 Now I'm being disconnected because of this: "io.netty.handler.codec.DecoderException: java.lang.UnsupportedOperationException" Edit: Exact stacktrace: https://pastebin.com/6iWwURST

**Comment by Steveice10** [comment]
That's an unrelated bug that should be fixed now.

**Comment by ggmoritz** [comment]
@Steveice10 It's working now. HUGE thanks for fixing this.

**Comment by ggmoritz** [comment]
@Steveice10 This bug reappeared after you added the packetError event. The connections always times out, the remote address of the session is null. By using the direct ip it works. Also other domains that only have a minecraft server and not a web server in addition seem to work too.

**Comment by Steveice10** [comment]
Cannot reproduce. Using the latest commits of both PacketLib and MCProtocolLib, I can connect to the server tested on, "sb-hub.com", just fine.

**Comment by ggmoritz** [comment]
> Cannot reproduce. Using the latest commits of both PacketLib and MCProtocolLib, I can connect to the server tested on, "sb-hub.com", just fine.

@Steveice10 tested on android? I only tested "skyblock.net"

**Comment by Steveice10** [comment]
I just pushed a commit to add a flag to print DNS resolution errors, so give that a try and let me know what stack trace you get.

**Comment by ggmoritz** [comment]
> 
> 
> I just pushed a commit to PacketLib to add a flag to print DNS resolution errors, so give that a try and let me know what stack trace you get.

@Steveice10 I did session.setFlag(BuiltinFlags.PRINT_DNS_ERRORS, true) but nothing was printed. It just times out and it's the remote address is null at the point i check it

**Comment by Steveice10** [comment]
The remote address is null because it's retrieved from the underlying netty channel, which is null because the connection couldn't be established.

I've pushed another commit to change the DNS error printing flag to a general debug flag, and I've added some more debug messages that should either print the address/port it resolves or tell you why it couldn't resolve an SRV record.

**Comment by ggmoritz** [comment]
@Steveice10 05-30 23:59:49.028 11512 11702 I System.out: [PacketLib] No SRV records found.

**Comment by Steveice10** [comment]
Looks like dnsjava is failing to resolve the SRV record for some reason then. I've updated the dependency to the newest version that just came out a few days ago, so let me know if that helps. I also added the resolution result to the debug output.

**Comment by Steveice10** [comment]
Forgot to mention, if it still doesn't work and you're willing to experiment you could try changing the target Java version in PacketLib's pom.xml back to 1.7, as that's the only change I can think of that could possibly have an effect on this.

**Comment by Steveice10** [comment]
Discovered today that netty actually has built-in support for making DNS queries, so I've switched over to that to reduce dependencies. Let me know if that works out better for you on Android as well.

**Comment by Steveice10** [comment]
Managed to get a basic Android project setup to test MCProtocolLib, and I can confirm that the latest commit works to connect to "skyblock.net".

**Comment by ggmoritz** [comment]
@Steveice10 It still resolves to null on my phone. (Latest MCProtocolLib + PacketLib)

**Comment by Steveice10** [comment]
I would assume it has to do with your device or network then, because I can connect to the exact same server address just fine on my device.

**Comment by ggmoritz** [comment]
@Steveice10 It just doesn't work on my phone :/ Have you tried mobile data too? Do I maybe have to update MCAuthLib manually?

**Comment by Steveice10** [comment]
If you have the latest versions of MCProtocolLib and it's dependencies, it should work fine. When I get the chance I'll try on another device to double check.

**Comment by ggmoritz** [comment]
@Steveice10 this might be helpful https://stackoverflow.com/questions/56635898/dnsjava-library-return-no-records-found

**Comment by ggmoritz** [comment]
@Steveice10 This workaround works on my phone and dns-java. Not sure how you would do that with netty.
`System.setProperty("dns.server", "8.8.8.8")`

**Comment by Steveice10** [comment]
Hardcoding a specific DNS server is not something MCProtocolLib should be doing.

**Comment by ggmoritz** [comment]
@Steveice10 maybe provide a flag to set the dns server? The property thing only works for dns-java

**Comment by Steveice10** [comment]
It should already be either using the system DNS settings or falling back to Google's DNS, so I would check the DNS settings on your device.

Testing again, I did the following:
* Created a new project in Android Studio.
* Added the following to the generated build.gradle:
```
android {
    ...
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    ...
}
...
allprojects {
    repositories {
        maven { url 'https://jitpack.io' }
    }
}
...
dependencies {
    implementation 'com.github.Steveice10:MCProtocolLib:1.15.2-1'
}
```
* Added ```<uses-permission android:name="android.permission.INTERNET" />``` to the manifest.
* Put the following code on the auto-generated view's floating action button:
```
fab.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                new Thread(new Runnable() {
                    public void run() {
                        MinecraftProtocol protocol = new MinecraftProtocol(SubProtocol.STATUS);
                        Client client = new Client("skyblock.net", 25565, protocol, new TcpSessionFactory());
                        client.getSession().setFlag(MinecraftConstants.SERVER_INFO_HANDLER_KEY, new ServerInfoHandler() {
                            @Override
                            public void handle(Session session, ServerStatusInfo info) {
                                System.out.println("Version: " + info.getVersionInfo().getVersionName() + ", " + info.getVersionInfo().getProtocolVersion());
                                System.out.println("Player Count: " + info.getPlayerInfo().getOnlinePlayers() + " / " + info.getPlayerInfo().getMaxPlayers());
                                System.out.println("Players: " + Arrays.toString(info.getPlayerInfo().getPlayers()));
                                System.out.println("Description: " + info.getDescription());
                                System.out.println("Icon: " + info.getIconPng());
                            }
                        });

                        client.getSession().setFlag(MinecraftConstants.SERVER_PING_TIME_HANDLER_KEY, new ServerPingTimeHandler() {
                            @Override
                            public void handle(Session session, long pingTime) {
                                System.out.println("Server ping took " + pingTime + "ms");
                            }
                        });

                        client.getSession().connect();
                        while(client.getSession().isConnected()) {
                            try {
                                Thread.sleep(5);
                            } catch(InterruptedException e) {
                                e.printStackTrace();
                            }
                        }
                    }
                }).start();
            }
        });
```
* Ran the app on my phone, pressed the button, and got the following logcat output:
```
2020-06-17 12:48:58.163 11316-11488/com.github.steveice10.myapplication I/System.out: Version: SkyCord 1.8.x-1.15.x, 578
2020-06-17 12:48:58.164 11316-11488/com.github.steveice10.myapplication I/System.out: Player Count: 227 / 750
2020-06-17 12:48:58.165 11316-11488/com.github.steveice10.myapplication I/System.out: Players: [GameProfile{id=af74a02d-19cb-445b-b07f-6866a861f783, name=§a§lSkyblock §8| §fskyblock.net, properties=[]}, GameProfile{id=af74a02d-19cb-445b-b07f-6866a861f783, name=§6§l[ §e1.8 - 1.15.2 §6§l], properties=[]}, GameProfile{id=af74a02d-19cb-445b-b07f-6866a861f783, name=§a , properties=[]}, GameProfile{id=af74a02d-19cb-445b-b07f-6866a861f783, name=§fTwitter: §b@Skyblock, properties=[]}, GameProfile{id=af74a02d-19cb-445b-b07f-6866a861f783, name=§fStore: §ashop.skyblock.net, properties=[]}, GameProfile{id=af74a02d-19cb-445b-b07f-6866a861f783, name=§fForums: §dwww.skyblock.net, properties=[]}, GameProfile{id=af74a02d-19cb-445b-b07f-6866a861f783, name=§a , properties=[]}, GameProfile{id=af74a02d-19cb-445b-b07f-6866a861f783, name=§e§oThe home of Skyblock, properties=[]}]
2020-06-17 12:48:58.165 11316-11488/com.github.steveice10.myapplication I/System.out: Description: Skyblock ❘ Follow us on Twitter! @Skyblock
2020-06-17 12:48:58.165 11316-11488/com.github.steveice10.myapplication I/System.out: Now with less blocks & more sky!
2020-06-17 12:48:58.165 11316-11488/com.github.steveice10.myapplication I/System.out: Icon: [B@98ff690
2020-06-17 12:48:58.189 11316-11488/com.github.steveice10.myapplication I/System.out: Server ping took 24ms
```

If you want to test yourself, here's the generated APK: https://www.dropbox.com/s/3a84meluz3z5ar5/app-debug.apk?dl=1

**Comment by ggmoritz** [comment]
@Steveice10 This is everything your apk outputs on my phone: https://pastebin.com/n64xu1SF. The only thing which makes sense is `06-17 22:35:34.672 19796 19843 W erAddressStreamProvider: Default DNS servers: [/2001:4860:4860::8888:53, /2001:4860:4860::8844:53] (Google Public DNS as a fallback)`. It doesn't output anything else.  
  
My DNS settings are on the default and I also tried to manually change them with no success.

**Comment by Steveice10** [comment]
Added some debug output, here's what I get now:
```
2020-06-17 13:47:52.135 24304-24417/com.github.steveice10.myapplication I/System.out: [PacketLib] Attempting SRV lookup for "_minecraft._tcp.skyblock.net".
2020-06-17 13:47:52.155 24304-24417/com.github.steveice10.myapplication W/erAddressStreamProvider: Default DNS servers: [/2001:4860:4860::8888:53, /2001:4860:4860::8844:53] (Google Public DNS as a fallback)
2020-06-17 13:47:52.269 24304-24417/com.github.steveice10.myapplication I/System.out: [PacketLib] Found SRV record containing "242140121-sb-bungee-1.ddns.net:25565".
2020-06-17 13:47:52.721 24304-24422/com.github.steveice10.myapplication I/System.out: Version: SkyCord 1.8.x-1.15.x, 578
2020-06-17 13:47:52.722 24304-24422/com.github.steveice10.myapplication I/System.out: Player Count: 268 / 750
2020-06-17 13:47:52.722 24304-24422/com.github.steveice10.myapplication I/System.out: Players: [GameProfile{id=af74a02d-19cb-445b-b07f-6866a861f783, name=§a§lSkyblock §8| §fskyblock.net, properties=[]}, GameProfile{id=af74a02d-19cb-445b-b07f-6866a861f783, name=§6§l[ §e1.8 - 1.15.2 §6§l], properties=[]}, GameProfile{id=af74a02d-19cb-445b-b07f-6866a861f783, name=§a , properties=[]}, GameProfile{id=af74a02d-19cb-445b-b07f-6866a861f783, name=§fTwitter: §b@Skyblock, properties=[]}, GameProfile{id=af74a02d-19cb-445b-b07f-6866a861f783, name=§fStore: §ashop.skyblock.net, properties=[]}, GameProfile{id=af74a02d-19cb-445b-b07f-6866a861f783, name=§fForums: §dwww.skyblock.net, properties=[]}, GameProfile{id=af74a02d-19cb-445b-b07f-6866a861f783, name=§a , properties=[]}, GameProfile{id=af74a02d-19cb-445b-b07f-6866a861f783, name=§e§oThe home of Skyblock, properties=[]}]
2020-06-17 13:47:52.722 24304-24422/com.github.steveice10.myapplication I/System.out: Description: Skyblock ❘ Follow us on Twitter! @Skyblock
2020-06-17 13:47:52.722 24304-24422/com.github.steveice10.myapplication I/System.out: Now supporting 1.8 -> 1.15.2!
2020-06-17 13:47:52.722 24304-24422/com.github.steveice10.myapplication I/System.out: Icon: [B@72f3baf
2020-06-17 13:47:52.788 24304-24422/com.github.steveice10.myapplication I/System.out: Server ping took 65ms
2020-06-17 13:47:52.798 24304-24421/com.github.steveice10.myapplication W/System.err: Disconnected Event received: Finished
```

And here's the updated APK: https://www.dropbox.com/s/h2r964cadytazr6/app-debug2.apk?dl=1

**Comment by ggmoritz** [comment]
@Steveice10 https://pastebin.com/kkjJ2MMf now there seems to be a stacktrace.

**Comment by Steveice10** [comment]
It looks like for some reason it can't connect to the DNS server from your device. Perhaps it has something to do with it using the IPv6 addresses for Google's DNS?

**Comment by Steveice10** [comment]
You could try setting the system property "java.net.preferIPv6Addresses" to false and "java.net.preferIPv4Stack" to true, which [should tell netty to use the IPv4 addresses](https://github.com/netty/netty/blob/0fd0e7acbdd694380d89cca330484af0598fe6e0/resolver-dns/src/main/java/io/netty/resolver/dns/DefaultDnsServerAddressStreamProvider.java#L87). Although if that works, the real issue is probably that whatever device/emulator you're using doesn't seem to be able to connect to the IPv6 address.

**Comment by ggmoritz** [comment]
@Steveice10 That changed nothing for me, which android version do you use? Because apparantly the issue was introduced with 8.0 (https://developer.android.com/about/versions/oreo/android-8.0-changes#o-pri)

**Comment by Steveice10** [comment]
I'm using Android 10, and none of that seems relevant as it's falling back on the Google DNS server addresses built in to Netty anyway.

**Comment by ggmoritz** [comment]
@Steveice10 I really don't know what's happening here. I have this issue too with another phone on Android 9.0 (my main one is 10.0). I only use mobile data but I doubt it would have an affect.

**Comment by ggmoritz** [comment]
@Steveice10 could you try to add this line in your example?
`System.setProperty("dns.server", "2001:4860:4860::8888")`  
Wondering if your device can resolve an explicit IPv6 DNS or not

**Comment by Steveice10** [comment]
Still works, but I'm pretty sure it's not using that property, it's using Netty's Google DNS fallback, as shown by this line from logcat:
```W/erAddressStreamProvider: Default DNS servers: [/2001:4860:4860::8888:53, /2001:4860:4860::8844:53] (Google Public DNS as a fallback)```

**Comment by ggmoritz** [comment]
@Steveice10 I thought the 1.15 release of MCProtocolLib would use dns-java instead of Netty's lookup

**Comment by Steveice10** [comment]
No, dns-java was replaced with Netty's lookup.

**Comment by Steveice10** [comment]
Also, just tried it on a device running Fire OS 6 (based on Android 7) and it also works there.

**Comment by ggmoritz** [comment]
@Steveice10 ah i thought it was replaced in a later commit. I made a test which sets the DNS via dns-java (for testing, idk how to do that with netty).  Here's the apk if you want to test it. https://workupload.com/file/3x7HbJPps9N   
Since 2 of my devices have this issue I suspect it might be my network. I'll test it with a real wifi connection later.

**Comment by Steveice10** [comment]
If you want to try changing the default DNS servers Netty uses, you could try using reflection to modify [DefaultDnsServerAddressStreamProvider.DEFAULT_NAME_SERVER_LIST and DefaultDnsServerAddressStreamProvider.DEFAULT_NAME_SERVERS](https://github.com/netty/netty/blob/0fd0e7acbdd694380d89cca330484af0598fe6e0/resolver-dns/src/main/java/io/netty/resolver/dns/DefaultDnsServerAddressStreamProvider.java#L106), although the initializer in that file should already use the IPv4 addresses if the interface address is IPv4 or "java.net.preferIPv4Stack" is true.

**Comment by Steveice10** [comment]
The APK you posted seems to work on my device.

**Comment by ggmoritz** [comment]
@Steveice10 It just won't work on my devices here. And for some reason I can't use the number IP because that will kick me and demand to join via the official domain. I also tried to use reflection to change the domain but that didn't work out either.
