### ISSUE TITLE
Proxy login issue

### ISSUE THREAD

**Issue by vincenzopio** [GeyserMC/MCProtocolLib#487]
There is an issue while trying to login using the proxy.

i tried some proxies that actually works but the connection doesn't happen anyway.

`
Proxy proxy = new Proxy(Proxy.Type.HTTP, new InetSocketAddress(host, port));
Client client = new Client(HOST, PORT, protocol, new TcpSessionFactory(proxy));
` = doesn't work.

with 

`
Client client = new Client(HOST, PORT, protocol, new TcpSessionFactory(Proxy.NO_PROXY));
` = works.

**Comment by Steveice10** [comment]
I believe the problem is that you're using an HTTP proxy and not a SOCKS proxy.

**Comment by vincenzopio** [comment]
Steve it doesn’t work anyway with socks proxy

**Comment by vincenzopio** [comment]
you should wait a reply before closing an issue.

**Comment by vincenzopio** [comment]
As I said, proxy connection to server doesn’t work.
After I’m going to find where the problem is.

**Comment by Steveice10** [comment]
Yes, but what about it is not working? If you have an exception, could you post the stack trace?

Also, just in case, make sure the proxy you're connecting to is actually a socks proxy, and not that you're just passing SOCKS in as the type.

**Comment by vincenzopio** [comment]
There are no errors in console, no exceptions.

Yes I know how to use a proxy, and I checked them too.

**Comment by Steveice10** [comment]
Then what about it isn't working? If there aren't any exceptions, that generally means you've successfully connected to the server.

**Comment by vincenzopio** [comment]
So, in a nutshell, i started a BungeeCord server on a vps and tried to
connect with the proxy.

Without the proxy the connections starts, with the proxy nothing happens.

**Comment by Steveice10** [comment]
I'm guessing its probably timing out trying to connect to either the server or the proxy itself, then. I would recommend trying some other proxies, as that has tended to be the solution in the past.

**Comment by vincenzopio** [comment]
I tried using https proxies and socks proxies checked 2 times, I don’t know
what to do.

**Comment by vincenzopio** [comment]
I think the problem is in the Auth api, not in this one.

**Comment by Steveice10** [comment]
Auth does not use the proxy passed into TcpSessionFactory.
