### ISSUE TITLE
Client movement

### ISSUE THREAD

**Issue by alvaromrb** [GeyserMC/MCProtocolLib#492]
I can't move the clients at all, I am sending a PacketPlayerPositionPacket adding 0.15 every time to the X position, but the client is not moving

**Comment by Steveice10** [comment]
There have been various questions submitted in the past about player movement. I would recommend taking a look through the related closed issues first.

**Comment by alvaromrb** [comment]
I've seen them but they don't seem to work for me, this is my code, I've read the protocol wiki but it isn't working either:

```java
public void move() {
        new Thread(() -> {
            for (int i = 0; i < 10; i++) {

                playerX += 0.2;
                session.send(new ClientPlayerPositionPacket(false, playerX, playerY, playerZ));

                try {
                    Thread.sleep(50);
                } catch (InterruptedException ex) {
                    
                }
            }
        }).start();
    }
```

**Comment by TheSnoozer** [comment]
I'm not sure if the explanation in https://github.com/Steveice10/MCProtocolLib/issues/219#issuecomment-281014110 is fully accurate, but I have exactly seen this in the wild and can confirm this sounds reasonable and that you need to listen to `ServerPlayerPositionRotationPacket`(s) when you want to implement movements.

E.g. something along the lines of
```
        if ( event.getPacket() instanceof ServerPlayerPositionRotationPacket ) {
            ServerPlayerPositionRotationPacket packet = event.getPacket();
            getSession().send(new ClientTeleportConfirmPacket(packet.getTeleportId()));
            getSession().send( new ClientPlayerPositionRotationPacket( true, packet.getX(), packet.getY(), packet.getZ(), packet.getYaw(), packet.getPitch() ) );
        }
```

**Comment by alvaromrb** [comment]
Got it to work yesterday, thank you though @TheSnoozer

**Comment by TheSnoozer** [comment]
No worries, could you perhaps elaborate what fixed your issue? Was it in fact the `ServerPlayerPositionRotationPacket` or did you need to change something else? 
I'm pretty sure whoever actually uses github search and finds this issue would be interested in a solution ;-)

**Comment by alvaromrb** [comment]
> No worries, could you perhaps elaborate what fixed your issue? Was it in fact the `ServerPlayerPositionRotationPacket` or did you need to change something else?
> I'm pretty sure whoever actually uses github search and finds this issue would be interested in a solution ;-)

```java
location.x += 0.15;

            session.send(new ClientPlayerPositionPacket(false, location.x, location.y, location.z));

            try {
                Thread.sleep(50);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
```

It was just like that, my problem was that I was sending the ClientPlayerPositionPacket in another thread
