### ISSUE TITLE
io.netty.handler.codec.DecoderException

### ISSUE THREAD

**Issue by OnlyBMan** [GeyserMC/MCProtocolLib#495]
After updating to the latest MCProtocolLib I now get this error

> io.netty.handler.codec.DecoderException: java.lang.IllegalArgumentException: Value minecraft:nbt_compound_tag has no mapping for key class com.github.steveice10.mc.protocol.data.game.command.CommandParser.

**Comment by Redned235** [comment]
Getting this error as well.

**Comment by Steveice10** [comment]
Thanks for reporting. I'm hoping to take care of some open issues in bulk this weekend, so it should be fixed then.
