### ISSUE TITLE
Work around multiple versions

### ISSUE THREAD

**Issue by ShayBox** [GeyserMC/MCProtocolLib#502]
I'm trying to create a bungeecord plugin that creates a very simple mcprotocolib server as a fallback, it will send 3 packets to get the player in-game, and send them a chat message.

I realize this lib doesn't use external mappings like node-minecraft-protocol, you hard code each version into the lib, so to support an older version you have to compile an older lib version, but since this server is so simple, it sends the same data no matter what game version.

Is it possible to just send the client their game version, allowing them to connect anyway?

**Comment by Steveice10** [comment]
Apologies for the *very* late reply on this. Not sure if you've found some other solution to do what you're trying to accomplish by now, but you could take a sort of "sample" of the packets and handshake code you need and customize it for your needs. MCProtocolLib just isn't built with multiple versions in mind, only to track support for the latest Minecraft version.
