### ISSUE TITLE
Original Mojang translation for ServerChatPacket

### ISSUE THREAD

**Issue by SoKnight** [GeyserMC/MCProtocolLib#504]
Hello. I use this MCProtocolLib for my minecraft bot and this library is perfect.
But.. when I send anyone command using ClientChatPacket to server, I receive command feedback, but I don't see message, I see section of message from original Mojang translation file en_us.json (you can find it in version jar). For example: I send _/list_ command and receive _commands.list.players_... And nothing.. Just commands.list.players. I don't can online players list on server using command..
Can you fix it and add new feature "integration with original Mojang translation" or if this translation has license, can you look for other ways to fix such messages?

**Comment by Steveice10** [comment]
The message you're receiving is likely an instance of TranslationMessage, which contains both the identifier (in this case, "command.list.players") and a Strong array of formatting parameters to fill in the blanks. You can handle these messages however you wish, but I do not intend to provide/maintain a full set of translations to handle them for the user.
