### ISSUE TITLE
How do i change version or where do i get sourcecode for 1.8

### ISSUE THREAD

**Issue by peter81745** [GeyserMC/MCProtocolLib#505]
Hello,
I want to know how to change the version to 1.8 or where i can download version 1.8

**Comment by Steveice10** [comment]
I believe the last commit for 1.8 was this one: https://github.com/Steveice10/MCProtocolLib/commit/4ccf753002a9666a259649061afffa785c0731d6

You can either build it yourself or, if you use jitpack, you can specify a commit hash as the dependency version.
