### ISSUE TITLE
Error when using 1.8

### ISSUE THREAD

**Issue by peter81745** [GeyserMC/MCProtocolLib#507]
When i am using 1.8.8 or 1.8.7 as Protocol i always get following error:
`Disconnected: io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(18) + length(8) exceeds writerIndex(18): PooledUnsafeDirectByteBuf(ridx: 18, widx: 18, cap: 18)`

how do i fix that

Edit; the bot is connected for a second and automatically leaves and throws this error

**Comment by Steveice10** [comment]
1.8 is old and no longer supported. My policy is generally to only provide support and updates for the latest version.
