### ISSUE TITLE
Can't connect to server.

### ISSUE THREAD

**Issue by LuckyTheCat** [GeyserMC/MCProtocolLib#51]
http://pastebin.com/rJDAcqtM
The code above is just a modification of the example class. It should join the server and say a message, but it doesn't join the server. There are no errors it just says "Successfully authenticated user."

Thanks,
LuckyTheCat

**Comment by ghost** [comment]
Networking works in other thread. You need for a while freeze main thread. Try Thread.sleep(5000)

**Comment by LuckyTheCat** [comment]
Okay, thanks. I used to use this a while ago, but didn't have that problem. Works now.
