### ISSUE TITLE
Chat color codes do not work in ClientChatPacket

### ISSUE THREAD

**Issue by Revxrsal** [GeyserMC/MCProtocolLib#512]
Hello. In an attempt to send colored messages, I've been trying to use the color code symbol § along with the color code. 

**Expected behavior**: Send a colored message, or at least throw an exception.

**Actual behavior**: The color code symbol is removed from the message, leaving the color codes.
(e.g `§eHello` gets sent as `eHello`).

I'm aware that the actual Minecraft client does not allow to send the color code symbol, but using the library, not being limited by the Minecraft limitations in the client, I'm sure there is a workaround in this.

**Comment by Steveice10** [comment]
That is not how color is supposed to be sent. You should be making use of the Message class to form your chat messages, specifically by modifying the MessageStyle.

**Comment by Revxrsal** [comment]
How can I use the Message class and its subclasses in ClientChatPacket? Not sure if I missed anything, but I'm not trying to send a message to the client, but **from** the client to the server.

**Comment by Steveice10** [comment]
Ah. In that case, it's up to the server to process the message text. The client has no say in whether color codes like that will actually work.
