### ISSUE TITLE
Breaking block using packets does not work

### ISSUE THREAD

**Issue by Revxrsal** [GeyserMC/MCProtocolLib#513]
Hello. In an attempt to break a block (the block break should be instant, a pickaxe with high efficiency and haste mining a cobblestone), the actual client connected using the library does not execute any actions.

The block is straight above the player (hence, relative facing is down)

After monitoring the standard Minecraft client behavior when mining blocks, I got the following data:
`C07PacketPlayerDigging{position=BlockPos{x=-376, y=8, z=-1210}, facing=down, status=START_DESTROY_BLOCK}`
*START_DESTROY_BLOCK is START_DIGGING in the library*

No further related packets are sent; mentioning again that the break is instant, no packet indicating `STOP_DESTROY_BLOCK` (FINISH_DIGGING in the library) is sent, and no server animation packet is sent either.

Code I tried:
1. 
```java
ClientPlayerActionPacket mine = new ClientPlayerActionPacket(PlayerAction.START_DIGGING, new Position(-376, 6, -1210), BlockFace.DOWN);
client.getSession().send(mine);
ClientPlayerActionPacket finish = new ClientPlayerActionPacket(PlayerAction.FINISH_DIGGING, new Position(-376, 6, -1210), BlockFace.DOWN);
client.getSession().send(finish);
```
Does not do anything.

2. 
```java
ClientPlayerActionPacket mine = new ClientPlayerActionPacket(PlayerAction.START_DIGGING, new Position(-376, 6, -1210), BlockFace.DOWN);
client.getSession().send(mine); // No finish packet this time
```
Does not do anything either.

Am I doing anything wrong, or missing anything?

**Comment by Steveice10** [comment]
There are two things that I can think of off the top of my head:
* You are not in a position that can reach the block.
* Your client is not "complete enough to perform in-game actions". What I mean by this is that there is a sequence of packets usually expected to go back-and-forth to get a player properly in-game; see [here](https://wiki.vg/Protocol_FAQ) for more info on that. I believe the client is also supposed to send player position updates to the server about every second, which could affect it as well.

**Comment by 0-x-2-2** [comment]
The Minecraft server does not allow instantly destroying blocks. This library worked almost perfectly in my testing as long as you implemented the code correctly.

**Comment by Revxrsal** [comment]
> There are two things that I can think of off the top of my head:
> 
> * You are not in a position that can reach the block.
> * Your client is not "complete enough to perform in-game actions". What I mean by this is that there is a sequence of packets usually expected to go back-and-forth to get a player properly in-game; see [here](https://wiki.vg/Protocol_FAQ) for more info on that. I believe the client is also supposed to send player position updates to the server about every second, which could affect it as well.

* The player is straight under the block, so I believe they are in the appropriate position.
* I changed the code slightly, to send the ClientPlayerPositionRotationPacket every second with the data to only set the player's pitch to -90 (looking straight up), and after sending the ClientTeleportConfirmPacket packet, I send the mining packets. That also did not work as no behavior appeared on the bot.

> The Minecraft server does not allow instantly destroying blocks. This library worked almost perfectly in my testing as long as you implemented the code correctly.

That could be the reason why, but do you know how would I make it not instant then?

**Comment by Revxrsal** [comment]
**Update**: I tried to also send _ClientHeldItemPacket_ before, and then the mining packets, with animation packets in between (in result, it appears exactly like normal mining on Minecraft), but the block does not get affected. The client does indeed receive a _ServerBlockChangePacket_, with the new data set to 0 (as in air, so I believe the block is mined for the client), but on the other players' screen it does not change.

**Comment by Revxrsal** [comment]
**Update**: I found what the problem was: It simply was because the account did not have OP, and the block was protected by the standard vanilla protection. My bad 🤦‍♂ 

Thanks for your help.

**Comment by Beryl0** [comment]
> **Update**: I found what the problem was: It simply was because the account did not have OP, and the block was protected by the standard vanilla protection. My bad 🤦‍♂
> 
> Thanks for your help.

Hey, I've been having issues with the above and nothing seems to be working - Would you mind elaborating on what you done to get it to work? Discord is de_inferno#8584 if you would not mind messaging :)

**Comment by Revxrsal** [comment]
> > **Update**: I found what the problem was: It simply was because the account did not have OP, and the block was protected by the standard vanilla protection. My bad 🤦‍♂
> > Thanks for your help.
> 
> Hey, I've been having issues with the above and nothing seems to be working - Would you mind elaborating on what you done to get it to work? Discord is de_inferno#8584 if you would not mind messaging :)

By default, (vanilla) servers do not allow block breaking for non-op accounts around the spawn-point (where my bot happened to be). This is configurable in the server.properties
![image](https://user-images.githubusercontent.com/26172484/110690393-8e06b000-81ec-11eb-9ceb-0f747f54ac13.png)
