### ISSUE TITLE
Reconnect impossible

### ISSUE THREAD

**Issue by BlvckBytes** [GeyserMC/MCProtocolLib#515]
Hey!

I need to perform a reconnect (quit and join again), but it seems like this is impossible with the library's current structure. Is there a way to do this? The minecraft client itself also only authenticates once and can use this session multiple times... :(

**Comment by Steveice10** [comment]
The best way to go about reconnecting with MCProtocolLib is to fetch the client and access tokens from your old MinecraftProtocol instance and pass them to the constructor of a new one.

**Comment by BlvckBytes** [comment]
You know, the funny thing is... After a few hours of trying to understand the concepts behind all of this, I came up with just that - lol.

I am using the 1.8 version of this library, and I also think that some old(ish) and deprecated stuff is in there. But hey, it works amazingly well, huge thank you for writing this awesome lib!

I added this constructor:
```java
public MinecraftProtocol( GameProfile profile, String accessToken, String clientToken ) {
        this(SubProtocol.LOGIN);
        this.profile = profile;
        this.accessToken = accessToken;
        this.clientToken = clientToken;
    }
```

I saw that the only thing preventing me from rejoining basically was the fact that a closed TCPSession cannot be reused and the MinecraftProtocol is stuck at SubProtocol GAME. Now, I wrote the following code that takes the old MinecraftProtocol instance and reinits a client with a new TCPSession.

```java
public void refresh( MinecraftProtocol protocol ) {
    try {
      MinecraftProtocol newProt = new MinecraftProtocol( protocol.getProfile(), protocol.getAccessToken(), protocol.getClientToken() );
      this.client = new Client( this.address, this.port, newProt, new TcpSessionFactory( Proxy.NO_PROXY ) );
      listen();
    } catch ( Exception e ) {
      StringWriter errors = new StringWriter();
      e.printStackTrace(new PrintWriter(errors));
      SimpleLogger.getInst().log( "Error while trying to refresh MinecraftProtocol!", SLLevel.ERROR );
      SimpleLogger.getInst().log( errors.toString(), SLLevel.ERROR );
    }
  }
```

All of this is kept in a MCBot class I wrote, your code and variable names of course may differ.
If anybody else faces this issue, I hope that my comment may help. Again, huge thanks to Steveice10 for writing this and also responding so quickly to issues.
