### ISSUE TITLE
No way to control client movement 

### ISSUE THREAD

**Issue by amyipdev** [GeyserMC/MCProtocolLib#517]
Am I just dumb, or is there no way to control client movement? I'd like to implement Baritone into this, but I can't seem to find any way.

If there is, how would I add Baritone to it?

**Comment by Steveice10** [comment]
No idea what Baritone is, but you can move by sending the appropriate Client->Server packets in the correct way. There are multiple closed issues you can reference on how to do this, as well as the protocol wiki: http://wiki.vg/

**Comment by amyipdev** [comment]
@Steveice10 
1. Please re-open this.
2. Baritone is at cabaletta/baritone on GitHub, please look in to this and explain how I could make it compatible (I don't know how the Baritone API sends packets, help would be useful)
3. Wiki.vg returns a 502 error when trying to access it
