### ISSUE TITLE
MCProtocolLib data usage

### ISSUE THREAD

**Issue by amyipdev** [GeyserMC/MCProtocolLib#518]
How much RAM usage and network usage does mcpl typically use per player? (Doubt CPU stats could be given reliably)

**Comment by BlvckBytes** [comment]
That hugely depends on what you plan to do with your players. Usually only a keepalive packet is sent when no actions are taken, thus network traffic is next to nothing and the same could be said about the cpu.

If you plan to do complex stuff this of course increases. Your question isn't really complete imo.

**Comment by Steveice10** [comment]
I don't really have any statistics on this, but I don't think it should be too memory intensive other than whatever amount of memory Netty might use.
