### ISSUE TITLE
Client disconnects directly after connecting!

### ISSUE THREAD

**Issue by tikaros** [GeyserMC/MCProtocolLib#520]
Hello. I'm currently on a bot system. Unfortunately the bot loses the connection immediately after connecting and the following error is thrown. I have not found a solution. Do you have any ideas what could be the cause?

Thanks in advance!

https://pastebin.com/C6f3HZmL

**Comment by Steveice10** [comment]
What version of MCProtocolLib are you using, and in what environment (e.g. PC, Android)? A NullPointerException should not be possible at the line specified.

**Comment by tikaros** [comment]
I use the latest version of MCProtocolLib and for PC. I have not changed anything in the code and have used the test class. But I created my own cracked server and joined my account. Then I ran the test class but the bot did not enter the server and there was an error message...

**Comment by tikaros** [comment]
Have now tried again with the MinecraftProtocolTest class. The bot joint, stays very short and then comes this error. Do I have to send the KeepAlive packages myself?

https://pastebin.com/8KU1aPVi

**Comment by Steveice10** [comment]
Apologies for the delayed reply. I noticed your new log indicates you are connecting to a Spigot 1.8.8 server. What are you using to allow multi-version support on your server?

**Comment by Steveice10** [comment]
Closing due to lack of reply. Will reopen if this is still an issue.
