### ISSUE TITLE
Bot disconnects after connecting

### ISSUE THREAD

**Issue by JustYarka** [GeyserMC/MCProtocolLib#522]
Hello! My bot immediately after the entrance throws the error (https://pastebin.com/PDhrkGrP) and shuts down. I used the code from the example without changing anything. I had to reassemble the library as I changed the protocol to MinecraftConstants for 485 (1.14.2). I have not found a solution to this problem. Maybe I should just cut out the processing of this package.

**Comment by Steveice10** [comment]
Simply changing the protocol version constant will not make the library compatible with a different version; there are various protocol differences between most major versions.

If you want to use a 1.14.2, I would recommend using the source from before the first 1.15 tag.
