### ISSUE TITLE
[Help/Question] Printing detail error stack trace

### ISSUE THREAD

**Issue by pedxyuyuko** [GeyserMC/MCProtocolLib#523]
I suggest to add error log print like when the program cannot cannect to the server, it can reture error message and stack trace.

**Comment by Steveice10** [comment]
In most cases that an exception occurs, it will either be printed or provided in the corresponding disconnect event for you to process however you want. You can access it with the getCause() method.

Let me know if this solves your problem, or if there is some exception this for some reason does not apply to.

**Comment by pedxyuyuko** [comment]
> In most cases that an exception occurs, it will either be printed or provided in the corresponding disconnect event for you to process however you want. You can access it with the getCause() method. For some cases like connect exceptions, I believe they should be thrown by the call to connect.
> 
> Let me know if this solves your problem, or if there is some exception this for some reason does not apply to.

Like using the EventListener with DisconnectedEvent/DisconnectingEvent? 
```
    @Override
    public void disconnected(DisconnectedEvent event) {
        try {
            // if that is not normal disconnect/server close
            if ( event.getCause() != null ) throw event.getCause();
        } catch (Throwable throwable) {
            throwable.printStackTrace();
        }
    }
```

But it is like when I try to connect to the server first time. The server is unreachable, then the program will continue run.
![image](https://user-images.githubusercontent.com/39913604/78642598-90c69a00-78e5-11ea-88bd-d655ff42bbec.png)
I want get the stack trace when the ``connect()`` method failed. Do you have any suggestion? Thanks!

**Comment by Steveice10** [comment]
Try setting your connect timeout before calling connect.

**Comment by pedxyuyuko** [comment]
![image](https://user-images.githubusercontent.com/39913604/78646608-e1d98c80-78eb-11ea-862c-ba5ee7fc7552.png)
I think this is not working... 
![image](https://user-images.githubusercontent.com/39913604/78646623-eaca5e00-78eb-11ea-8ff7-91a9151df483.png)

**Comment by Steveice10** [comment]
Please also register your event handler before calling connect. Sorry for forgetting to mention that as well.

**Comment by pedxyuyuko** [comment]
> Please also add your event listener before calling connect. Sorry for forgetting to mention that as well.

Oh nice, It works! Thanks for your help and for this awesome project!
