### ISSUE TITLE
SessionService sometimes failing to fillProfileTextures

### ISSUE THREAD

**Issue by james090500** [GeyserMC/MCProtocolLib#528]
Sometimes, and I don't know why. When requesting a player profile data from https://sessionserver.mojang.com/session/minecraft/profile/{UUID} a singnature is added and the value returns a whole different JSON.

For example, I have attached 2 responses recieved from sessionserver.mojang.com one which SessionService can handle and one which it can't. The main difference between the two is the signature is missing from one of them and value is extremely different. This happens very rarely and can happen to any UUID with enough tries.

**Comment by james090500** [comment]
[(FAILS) cee3f57caa5445f8ad5f7faa5a6a1daf.txt](https://github.com/Steveice10/MCProtocolLib/files/4498223/FAILS.cee3f57caa5445f8ad5f7faa5a6a1daf.txt)
[(OK) c081aab64fef493b87066b2313ef6e5a.txt](https://github.com/Steveice10/MCProtocolLib/files/4498224/OK.c081aab64fef493b87066b2313ef6e5a.txt)

**Comment by Steveice10** [comment]
For clarification, what is the problem you're getting as a result of this different data? Is it throwing an exception, or something else? Because I believe the current auth code should support the signature field already.

I will make sure to take a look sometime soon and see if any auth stuff has changed since the last the code was updated, regardless.

**Comment by Steveice10** [comment]
Actually, I think I see the problem: the requireSecure argument to fillProfileTextures does not affect the signature check, so payloads without signatures are unusable. This will be corrected soon.

**Comment by james090500** [comment]
The actual exception being thrown is "Decrypted textures payload for for another user. (expected name null)"

**Comment by Steveice10** [comment]
Ah, it's because the profile instance you're filling doesn't have a username set. I'll just relax the requirements so that works.

**Comment by james090500** [comment]
Maybe. But if you decode the "value" for both the ok file and the fail file. You'll see how vastly different the return json is. I dont think fillProfileTextures can process the different json at all.

**Comment by Steveice10** [comment]
I've pushed changes bringing the code up to speed with the way Mojang handles it in 1.15.2. It seems they ignore most of the fields, which is why the different format works with their code.

Let me know if the latest changes fix your issue, or if there are still problems.

**Comment by Steveice10** [comment]
Gonna assume this is fixed and close the issue, since it worked in my testing. Let me know if this is not the case and I'll reopen the issue.
