### ISSUE TITLE
The name you sent was invalid!

### ISSUE THREAD

**Issue by WolfCr4wler** [GeyserMC/MCProtocolLib#532]
When I use the example provided in the git hub,
I get this error when i try to join a test server with my own account
Disconnected: The name you sent was invalid!

**Comment by Steveice10** [comment]
It sounds like you're trying to connect to an online-mode server. Did you replace the login credential constants at the top of the example with valid ones and turn on the verify users constant?

**Comment by WolfCr4wler** [comment]
its seems to be working now, btw is there a place with documentation or something?

**Comment by Steveice10** [comment]
There isn't really much in the way of library documentation at the moment. The example should demonstrate how to get started with the library though, and https://wiki.vg is a good resource for the Minecraft protocol in general.

**Comment by WolfCr4wler** [comment]
When i try to join a simple spigot server i get this error: Outdated server! I'm still on 1.8.8

**Comment by Steveice10** [comment]
You are trying to join a 1.8.8 server, while MCProtocolLib is currently on 1.15.2. You can try to go back and build a commit from back when 1.8.8 was the latest version, but I do not offer support/maintenance for old builds.

**Comment by WolfCr4wler** [comment]
ah so it only work on servers that have a bungeecord ? that support 1.8x to 1.15x?

**Comment by Steveice10** [comment]
The latest version only works on servers that support 1.15.2.
