### ISSUE TITLE
Entities doesn't spawn 

### ISSUE THREAD

**Issue by nosooqua** [GeyserMC/MCProtocolLib#533]
Hello. I don't know where I can get help with this library :(
I'm using MCProtocolLib 1.12.2-2 to create MC server proxy with ability to reconnect to proxy. Everything went well before i tried to write all entities to Map and spawn them on player reconnect.
I done everything from [this guide](https://wiki.vg/Protocol_FAQ#What.27s_the_normal_login_sequence_for_a_client.3F).
I send packets to spawn entities at the end of everything that is said in the guide above. Some entities spawns and some do not. I don't know, where my mistake is...
[The code I use to spawn entities](https://hastebin.com/iroqucikir.coffeescript).
[The code I use to store entities in a Map](https://hastebin.com/welifotugu.java).
[Entity and MobEntity classes](https://hastebin.com/uqowekojaf.java)
entityMap - is a ConcurrentMap with (Integer entityId, Entity entity).
Entity - is my class to store all about entity (like x, y, z, metadata, etc...)

**Comment by Steveice10** [comment]
Sorry for the late reply, but older versions of the library are not actively supported. Hope you managed to solve your issue by now, though.
