### ISSUE TITLE
World border

### ISSUE THREAD

**Issue by lukeeey** [GeyserMC/MCProtocolLib#534]
I've looked at wiki.vg at the format of the WorldBorder packet, and i'm looking at decompiled Minecraft source code for the packet.

The decompiled code looks as follows: 
![image](https://user-images.githubusercontent.com/32024335/80592622-a710d300-8a17-11ea-8624-045c05da82c2.png)

If you see the `size` in that screenshot, that is in the same place as `Portal Teleport Boundary` is supposed to me, but that seems to have a different description
![image](https://user-images.githubusercontent.com/32024335/80592741-d7587180-8a17-11ea-9fdc-f05e038ad232.png)

Is wiki.vg and MCProtocolLib up to date?

**Comment by Steveice10** [comment]
Can you check how that field is assigned/used in the source? Not sure why there would be both size and diameter fields.

**Comment by lukeeey** [comment]
There's this 
![image](https://user-images.githubusercontent.com/32024335/80635080-5323df80-8a53-11ea-8b9d-0185849d3b65.png)

And the size variable seems to be used for calculating the minX, maxY, minZ, maxZ.
*Side note: in MCProtocolLib it is named getCenterY() not Z*

```java
 private void func_212665_m() {
         this.minX = Math.max(WorldBorder.this.getCenterX() - this.size / 2.0D, (double)(-WorldBorder.this.worldSize));
         this.minZ = Math.max(WorldBorder.this.getCenterZ() - this.size / 2.0D, (double)(-WorldBorder.this.worldSize));
         this.maxX = Math.min(WorldBorder.this.getCenterX() + this.size / 2.0D, (double)WorldBorder.this.worldSize);
         this.maxZ = Math.min(WorldBorder.this.getCenterZ() + this.size / 2.0D, (double)WorldBorder.this.worldSize);
      }
```
That is in class `WorldBorder.StationaryBorderInfo`. The size parameter is the only one required for the construct and the initial size can be seen below:
![image](https://user-images.githubusercontent.com/32024335/80635427-c62d5600-8a53-11ea-971b-69cbcd12f439.png)

Actually i've just realised there is a method called `getDiameter()` which returns the size
![image](https://user-images.githubusercontent.com/32024335/80635595-012f8980-8a54-11ea-82a6-ee1f657a6043.png) and that is used here (this is the pseudocode shown on wiki.vg)
![image](https://user-images.githubusercontent.com/32024335/80635704-2b814700-8a54-11ea-9a0c-baf062997a5c.png)

So it seems the `size` is `diameter` and `diameter` is `radius`

**Comment by Steveice10** [comment]
Thanks for the info. I'll have to look into it further myself later to make sure I understand exactly what's going on with these fields.

**Comment by Heath123** [comment]
Size and teleport boundry might be the same thing

**Comment by lukeeey** [comment]
Im just mentioning about the naming mostly

**Comment by Steveice10** [comment]
Names have been updated to closer match the real field names.
