### ISSUE TITLE
Client disconnecting immediately upon connection

### ISSUE THREAD

**Issue by Quois** [GeyserMC/MCProtocolLib#536]
I'm trying to create a simple Minecraft bot which is only intended to send a chat message when connected and then stay in the server, but unfortunately, the bot joins for a split second, send the chat message, and then disconnects with an error (seen here: https://pastebin.com/pin9ecyT)
Any ideas what the issue could be? I'm pretty much using the example code at this point (https://pastebin.com/YzGTzzHz). Thanks in advance!

**Comment by Steveice10** [comment]
Could you make sure you're using the latest changes to MCProtocolLib? The stack trace doesn't match up with the current code, and I believe the issue you're having should be fixed already.

**Comment by Quois** [comment]
Thanks, that did solve the issue. I was using the 1.14.4 library. However, the latest release is 1.15.2, so how would I go about joining a server running an older version?

**Comment by Steveice10** [comment]
If you have MCAuthLib in your dependencies, make sure it's version 1.1 to match the 1.14.4 version of MCProtocolLib.

**Comment by Quois** [comment]
It's all working great! I've got one more unrelated question though, how would I log in using auth servers other than Mojang, for example The Altening?

**Comment by Steveice10** [comment]
You would probably have to modify MCAuthLib yourself to do that, as the auth URLs are hardcoded to Mojang's servers. Assuming this alternate auth server uses the same endpoints as Mojang's, it should just be a matter of changing out the URLs.

**Comment by Quois** [comment]
I'll look further into that, thanks!
