### ISSUE TITLE
This is what happens if you join a server with music in a jukebox playing: io.netty.handler.codec.DecoderException: java.lang.IllegalArgumentException: Value -1 has no mapping for key class

### ISSUE THREAD

**Issue by ggmoritz** [GeyserMC/MCProtocolLib#537]
Not much to say, it just disconnects with with the following cause: https://pastebin.com/n5NgRDr5

**Comment by ggmoritz** [comment]
It seems like it might not be the musics fault, the server is skyblock.net and I found this hotfix (Kotlin):

>     val values = MagicValues::class.java.getDeclaredField("VALUES").apply { isAccessible = true }.get(null) as MutableMap<Any, List<Any>>
>     values[BuiltinSound.AMBIENT_CAVE] = listOf(-1)

**Comment by Steveice10** [comment]
As far as I'm aware, -1 is not a valid sound ID. This is with the latest MCProtocolLib, right?

**Comment by ggmoritz** [comment]
@Steveice10 yes, latest (when i tested it)
Maybe a server sent an invalid sound id to crash bots? The official Client has no problem with it. I really though it was the jukebox but it seems like it isn't the problem

**Comment by Steveice10** [comment]
I think this is probably a result of some protocol version translators using -1 as a default sound value for untranslatable sounds. I've added a bit of code that should handle this, so let me know if it solves your problem.

**Comment by Steveice10** [comment]
Closing as fixed and tracking implementation of a proper fix in #540.

**Comment by Steveice10** [comment]
As an update, I dug into the vanilla client a bit more and realized that actually, while some things like entity types do have defaults, others that have been causing problems like sounds actually do not; if you launch Minecraft with the error log, you'll see that whatever thread is processing the packets is constantly printing NPE traces.

In light of this, I've decided to scrap the idea of default values and instead give library users more control over error handling. The latest PacketLib commit (which is now depended on by the latest MCProtocolLib commit) adds PacketErrorEvent, which has a method "setSuppress" that allows users to suppress the internal error handling and disconnect for any packet read/write errors that occur. Instead, apps are free to handle the error however they wish, perhaps by simply ignoring packets with bad values and printing a warning. I've also added some specific exception types for MagicValues related errors to make them easier to identify.

**Comment by ggmoritz** [comment]
@Steveice10 Huge thanks for fixing this. I noticed that I no longer get this issue without changing anything (except removing the hotfix). Is it handled by default now or did the server itself change it?

**Comment by Steveice10** [comment]
There was a hotfix in but I removed it in favor of the new solution, in case you may be on a different commit from the latest. I did also submit an issue ticket to ViaVersion and the problem got fixed there, but I doubt that would be in production servers yet.

It's also possible you just aren't encountering whatever was making the problematic sounds, now.
