### ISSUE TITLE
Add defaults for some value mappings.

### ISSUE THREAD

**Issue by ghost** [GeyserMC/MCProtocolLib#540]

**Comment by Steveice10** [comment]
Reposting this update from the more specific issue tickets here:

As an update, I dug into the vanilla client a bit more and realized that actually, while some things like entity types do have defaults, others that have been causing problems like sounds actually do not; if you launch Minecraft with the error log, you'll see that whatever thread is processing the packets is constantly printing NPE traces.

In light of this, I've decided to scrap the idea of default values and instead give library users more control over error handling. The latest PacketLib commit (which is now depended on by the latest MCProtocolLib commit) adds PacketErrorEvent, which has a method "setSuppress" that allows users to suppress the internal error handling and disconnect for any packet read/write errors that occur. Instead, apps are free to handle the error however they wish, perhaps by simply ignoring packets with bad values and printing a warning. I've also added some specific exception types for MagicValues related errors to make them easier to identify.
