### ISSUE TITLE
No discord server

### ISSUE THREAD

**Issue by colmalle** [GeyserMC/MCProtocolLib#543]
Can you open or include a discord server link for questions?

**Comment by heydryft** [comment]
Agree with this one. This needs a discord.

**Comment by Redned235** [comment]
If you need help with the protocol, feel free to join the #mcdevs IRC channel on freenode or look at https://wiki.vg.

**Comment by Steveice10** [comment]
Creating and managing a Discord server would add a lot of additional support burden. I would much prefer issues be reported through GitHub, or if there's some existing Minecraft development server I would be more open to occasionally answering questions there.
