### ISSUE TITLE
Missing generic.attackKnockback

### ISSUE THREAD

**Issue by TheMode** [GeyserMC/MCProtocolLib#547]
The attribute seems to be missing: https://github.com/Steveice10/MCProtocolLib/blob/master/src/main/java/com/github/steveice10/mc/protocol/data/game/entity/attribute/AttributeType.java

However, it is listed:
https://minecraft.gamepedia.com/Attribute#Modifiers
https://wiki.vg/Protocol#Entity_Properties

Who is in the wrong?

**Comment by Steveice10** [comment]
Fixed.
