### ISSUE TITLE
Data structure clean up work.

### ISSUE THREAD

**Issue by ghost** [GeyserMC/MCProtocolLib#548]

**Comment by Camotoy** [comment]
Just as a good place to put it - in the future there will likely be more values sent to us that don't have an enum value (for example, custom attribute values like Forge). We should have some graceful way of handling these values so they're still usable.

**Comment by Steveice10** [comment]
I'll make sure to keep that in mind. This will probably get pushed back to after 1.16 (other than message API since that's already done) to avoid complicating merging that in.

**Comment by Steveice10** [comment]
Closing as the status quo is acceptable and I both haven't and likely won't be getting around to making the rest of the proposed changes.
