### ISSUE TITLE
Bot disconnects after joining

### ISSUE THREAD

**Issue by tikaros** [GeyserMC/MCProtocolLib#551]
Hello.
I'm currently trying to write a bot system. However, an error occurs and the bot **disconnects** again directly after it has **entered the server**. Information: Minecraft version **1.8.8**, repos versions: **latest**. The **error**: https://haste.tiikoo.de/getoroziqi.bash The **test class** to start: https://haste.tiikoo.de/eqasebosin.java

I'd appreciate some help.

**Comment by Steveice10** [comment]
MCProtocolLib tracks the latest Minecraft version. Old versions are not supported.
