### ISSUE TITLE
Allow changing auth base URLs used internally.

### ISSUE THREAD

**Issue by ghost** [GeyserMC/MCProtocolLib#552]

**Comment by Steveice10** [comment]
Implemented in https://github.com/Steveice10/MCProtocolLib/commit/6c66d7e27ba7e3890f480e594525e6c80bbd549e

The way to customize authentication with proxies, custom URLs, etc. is to now create your own AuthenticationService/SessionService instances, customize them to your wishes, login, and pass them on to the MinecraftProtocol constructor.
