### ISSUE TITLE
Minecraft official client srv record resolution

### ISSUE THREAD

**Issue by MatteCarra** [GeyserMC/MCProtocolLib#555]
I've recently come across a minecraft server: cosmicprisons.com
I was unable to join the server using MCProtocolLib with the reason: "Please use the server domain to connect".
The reasoning behind this is that this particular server is inspecting the handshake packet for the server address, and it expects to find the SRV record, not the original domain.

The [handshake documentation](https://wiki.vg/Protocol#Handshake) says: `Hostname or IP, e.g. localhost or 127.0.0.1, that was used to connect. The Notchian server does not use this information. Note that SRV records are a complete redirect, e.g. if _minecraft._tcp.example.com points to mc.example.org, users connecting to example.com will provide mc.example.org as server address in addition to connecting to it. `

In order to follow the default minecraft client behaviour we should update the TcpSession host and port if the srv query resolves a response.
This would involve updating the PacketLib project, even though this is a Minecraft protocol specific change.

**Comment by Steveice10** [comment]
Should be fixed, thanks.
