### ISSUE TITLE
Chunk.set function not working correctly

### ISSUE THREAD

**Issue by Camotoy** [GeyserMC/MCProtocolLib#559]
Chunk.get works fine with Geyser - however something in chunk.set causes the block to be incorrectly written. This can be noticed in Geyser with chunk caching on - the first time you break a grass block, the particles are correctly written. However subsequent place and breaks in the same spot result in Chunk.get always returning 0. I believe the issue does not lie in FlexibleStorage but something in the Chunk function itself.

This may be why we had to put an ignore for equals and hash code in Chunk.

I'm aware that there is limited information provided here, so let me know if I can provide more detail.

**Comment by Tim203** [comment]
> This may be why we had to put an ignore for equals and hash code in Chunk.

Probably yeah

**Comment by Steveice10** [comment]
Fixed by pull request.
