### ISSUE TITLE
PlayerState.PERFORM_RESPAWN is missing

### ISSUE THREAD

**Issue by ggmoritz** [GeyserMC/MCProtocolLib#561]
I really hope I looked in the right place, the title says everything.

**Comment by Steveice10** [comment]
Could you provide more detail on what you’re trying to do? That’s not a value that exists for that enum as far as I know.

**Comment by Steveice10** [comment]
You may be looking for ClientRequest.RESPAWN

**Comment by ggmoritz** [comment]
@Steveice10 That's probably the right thing, I'll try it tomorrow. It's a bit confusing that some packets have a conpletely different name here (for example the game state change packet)

**Comment by Steveice10** [comment]
Yeah, there have been times in the past when packets were either implemented here before the wiki updates were finalized, plus some wiki names have changed over time.

**Comment by ggmoritz** [comment]
@Steveice10 Thanks, it worked like a charm.
