### ISSUE TITLE
The bot does not stay connected

### ISSUE THREAD

**Issue by mataxetos** [GeyserMC/MCProtocolLib#565]
After compiling and running the MinecraftProtocolTest example, the bot is able to connect to the server but right after it disconnects.

I am doing something wrong? or would that be his behavior?

IMG: https://i.imgur.com/8DDxriV.png

**Comment by Steveice10** [comment]
The example code is meant to disconnect quickly, yes. If you don't want it to, you should remove the call to disconnect.
