### ISSUE TITLE
Error on connect

### ISSUE THREAD

**Issue by Moose1301** [GeyserMC/MCProtocolLib#570]
`Disconnected: io.netty.handler.codec.DecoderException: com.github.steveice10.mc.protocol.data.UnmappedValueException: Value minecraft:available_biomes has no mapping for key class com.github.steveice10.mc.protocol.data.game.command.SuggestionType.
`
I get this when i try to join my localhost server

**Comment by Moose1301** [comment]
Code: https://pastebin.com/CQxwsM7D

**Comment by Steveice10** [comment]
Can you verify this is still happening on the latest code? It looks like the mapping is there and this shouldn't be happening.

**Comment by Moose1301** [comment]
This does still happen on the latest code.

**Comment by Steveice10** [comment]
Can you post the full stack trace?

**Comment by Moose1301** [comment]
Disconnected: io.netty.handler.codec.DecoderException: com.github.steveice10.mc.protocol.data.UnmappedValueException: Value minecraft:available_biomes has no mapping for key class com.github.steveice10.mc.protocol.data.game.command.SuggestionType.
All it says, In console there is no errors

This is console when i join:
[18:38:31 INFO]: Moose1301 joined the game
[18:38:31 INFO]: Moose1301 logged in with entity id 646 at ([world]76.55418220396979, 86.26781659836448, 219.16308737732535)
[18:38:32 INFO]: Moose1301 lost connection: Disconnected
[18:38:32 INFO]: Moose1301 left the game

**Comment by Moose1301** [comment]
IN console there is no errors

**Comment by Steveice10** [comment]
Along with the disconnect message, the event should have a causing exception that you can print.

**Comment by Moose1301** [comment]
https://pastebin.com/YsReVRX6

**Comment by Moose1301** [comment]
@Steveice10

**Comment by Steveice10** [comment]
Sorry for the delay, but I've been unable to reproduce this issue. As you can see [here](https://github.com/Steveice10/MCProtocolLib/blob/master/src/main/java/com/github/steveice10/mc/protocol/data/MagicValues.java#L1175), the value in question is indeed mapped, so there should be no exception if you're using the latest version.

**Comment by Moose1301** [comment]
This is my pom.xml:
https://pastebin.com/NzyeUTgT
I'm using the latest version right

**Comment by Steveice10** [comment]
No, the latest is 1.16.3-SNAPSHOT. Only the latest version of Minecraft is supported, and fixes are not backported to earlier versions.
