### ISSUE TITLE
latest example giving compilation error.

### ISSUE THREAD

**Issue by WolfCr4wler** [GeyserMC/MCProtocolLib#573]
latest example giving compilation error.

no suitable constructor found for MinecraftProtocol(com.github.steveice10.mc.auth.service.AuthenticationService)

protocol = new MinecraftProtocol(authService);
at this -> authService

**Comment by Steveice10** [comment]
You need to update your copy of the library. The example is kept up to date with the latest source code.

**Comment by WolfCr4wler** [comment]
I am using the latest version
