### ISSUE TITLE
problem with GameProfile

### ISSUE THREAD

**Issue by slowAccount0** [GeyserMC/MCProtocolLib#577]
![image](https://user-images.githubusercontent.com/71569534/93688780-b7aa0e80-fac8-11ea-8a68-f2f16615f404.png)

**Comment by Steveice10** [comment]
You don't seem to have the library included properly, the key mentioned in the exception message is bundled in the MCAuthLib JAR as a resource.

**Comment by slowAccount0** [comment]
> You don't seem to have the library included properly, the key mentioned in the exception message is bundled in the MCAuthLib JAR as a resource.

It turned out that one file was missing from resources, it's already working.
