### ISSUE TITLE
Bungeecord problem

### ISSUE THREAD

**Issue by GrayR0ot** [GeyserMC/MCProtocolLib#579]
Hello,

I've tryed using your lib to make a random player join my Bungeecord server.

It's working.

But when i ask the client to send a ClientChatPacket
using: event.getSession().send(new ClientChatPacket("/login " + AccountGenerator.defaultPassword));
It's not working. The bungeecord server console does not print anything.

I've trying using a single spigot server and it's working.

I'm asking about, if we can do something ?

**Comment by GrayR0ot** [comment]
@Steveice10

**Comment by Steveice10** [comment]
Hi, sorry for the late reply. Are you still experiencing this issue, and if so, could you share some more of your code so I can get an idea of what exactly is going on?

**Comment by GrayR0ot** [comment]
Here is the code for each session / client
`public static void login(final String username, String proxyString) {
        System.out.println("Login player " + username);
        MinecraftProtocol protocol = new MinecraftProtocol(username);
        final Location entitiyLocation = new Location(-924.5, 80, 27.5, 135F, 0F);
        //Proxy proxy = new Proxy(Proxy.Type.HTTP, new InetSocketAddress(proxyString.substring(0, proxyString.indexOf(":")), Integer.parseInt(proxyString.replace(proxyString.substring(0, proxyString.indexOf(":")), "").replace(":", ""))));
        final SessionService sessionService = new SessionService(Proxy.NO_PROXY);

        final Client client = new Client(Main.HOST, Main.PORT, protocol, new TcpSessionFactory(Proxy.NO_PROXY));
        //System.out.println("Proxy: " + proxy.toString());
        client.getSession().addListener(new SessionAdapter() {
            @Override
            public void packetReceived(PacketReceivedEvent receiveEvent) {
                if (receiveEvent.getPacket() instanceof ServerChatPacket) {
                    ServerChatPacket chatPacket = receiveEvent.getPacket();
                    Message message = chatPacket.getMessage();
                    if(!message.toString().startsWith("TextMessage(")) {
                        System.out.println("[SERVER] " + message);
                    }
                    if(message.toString().contains("Pour te lancer, tu peux utiliser ta")) {
                        client.getSession().send(new ClientChatPacket("/warfare"));
                    }
                } else if (receiveEvent.getPacket() instanceof ServerPlayerHealthPacket) {
                    ServerPlayerHealthPacket healthPacket = receiveEvent.getPacket();
                    System.out.println("Health: " + healthPacket.getHealth());
                    System.out.println("Food:" + healthPacket.getFood());
                    client.getSession().send(new ClientPlayerPositionPacket(true, 10294, 130, 8647));
                } else if (receiveEvent.getPacket() instanceof ServerJoinGamePacket) {
                    System.out.println("Dispatching login command");
                    client.getSession().send(new ClientChatPacket("/register 12345678* 12345678*"));
                } else if (receiveEvent.getPacket() instanceof DisconnectingEvent) {
                    System.out.println("Changing server!");
                }
            }

            @Override
            public void disconnected(DisconnectedEvent event) {
                System.out.println("Disconnected: " + event.getReason());
                if (event.getCause() != null) {
                    event.getCause().printStackTrace();
                }
            }
        });

        client.getSession().connect();
    }`

**Comment by Steveice10** [comment]
You seem to be using an older version of MCProtocolLib; for example, TcpSessionFactory takes a ProxyInfo instance now, not a java.net.Proxy. Try updating to the latest version, and see if that helps.

**Comment by GrayR0ot** [comment]
I was using the latest before but it was the same
Chat not working in bungeecord,

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by Steveice10** [comment]
Here's what I did:
* Modified the included example code to:
  * Not spawn a server (SPAWN_SERVER = false)
  * Connect to the default BungeeCord port (25577).
  * Send "/help" instead of the usual example message.
  * Not disconnect when a ServerChatPacket is received.
* Set up a completely default BungeeCord server with a completely default vanilla server behind it.

I ran the code and successfully received the results of "/help" back to my test client. Thus, I cannot reproduce your issue.

**Comment by Steveice10** [comment]
I would recommend checking that you are actually sending this packet, making sure it isn't perhaps being received after all (I don't think any messages ever got printed to the BungeeCord console, only that of the Minecraft server behind it), and also printing all chat messages you receive back, not just non-TextMessages.

**Comment by GrayR0ot** [comment]
Do you have the code example of your /help ?

**Comment by Steveice10** [comment]
Yes, it's just the example in the repository here but with the changes I mentioned. Here's a direct link to that: https://github.com/Steveice10/MCProtocolLib/blob/master/example/com/github/steveice10/mc/protocol/test/MinecraftProtocolTest.java

**Comment by GrayR0ot** [comment]
I've edited:

`public static void login(final String username, String proxyString) {
        System.out.println("Login player " + username);
        MinecraftProtocol protocol = new MinecraftProtocol(username);
        SessionService sessionService = new SessionService();
        sessionService.setProxy(Proxy.NO_PROXY);

        Client client = new Client(Main.HOST, Main.PORT, protocol, new TcpSessionFactory(null));
        client.getSession().setFlag(MinecraftConstants.ACCESS_TOKEN_KEY, sessionService);
        client.getSession().addListener(new SessionAdapter() {
            @Override
            public void packetReceived(PacketReceivedEvent event) {
                if(event.getPacket() instanceof ServerJoinGamePacket) {
                    //event.getSession().send(new ClientChatPacket("Hello, this is a test of MCProtocolLib."));
                } else if(event.getPacket() instanceof ServerChatPacket) {
                    Message message = event.<ServerChatPacket>getPacket().getMessage();
                    System.out.println("Received Message: " + message);
                    if(message.toString().contains("/login")) {
                        event.getSession().send(new ClientChatPacket("/login 12345678"));
                        //event.getSession().send(new ServerChatPacket("/login 12345678"));
                    }
                    //event.getSession().disconnect("Finished");
                }
            }

            @Override
            public void disconnected(DisconnectedEvent event) {
                System.out.println("Disconnected: " + event.getReason());
                if(event.getCause() != null) {
                    event.getCause().printStackTrace();
                }
            }
        });

        client.getSession().connect();
    }`

I'm receiving the /login suggestion in the console. But nothing happend with the `event.getSession().send(new ServerChatPacket("/login....."));`

**Comment by Steveice10** [comment]
Have you tried sending other commands like a simple "/help"?

**Comment by GrayR0ot** [comment]
yeah and simple message, nothing happend

**Comment by GrayR0ot** [comment]
I've tryed on simple spigot server it was working

**Comment by Steveice10** [comment]
If it's working on my end and for you on a Spigot server, I would say this is probably an issue related to your BungeeCord setup and not a MCProtocolLib bug.

**Comment by GrayR0ot** [comment]
Working with latest branch
