### ISSUE TITLE
Chunk transferData bug

### ISSUE THREAD

**Issue by MatteCarra** [GeyserMC/MCProtocolLib#580]
I have noticed a strange line in the Chunk code, but I may be wrong.

My understanding of chunks in Minecraft (before 1.16):
If bitsPerEntry <= 8,the storage contains the indexes of the block in the corresponding pallette slot.
If bitsPerEntry > 8, the storage (array of longs) contains directly block ids.
I think we might have a bug when the storage changes from the first condition to the second condition.
In fact theoretically we should have to
1. Create a new storage with bitsPerEntry = 14
2. For each block entry of the old storage, get the corresping id in the old pallette, and set **THE ID RETURNED BY THE PALLETTE** in the new storage.
3. profit

The bug:
Chunk has a method called set(int x, int y, int z, @NonNull int state): https://github.com/Steveice10/MCProtocolLib/blob/976c2d0f8900d11817f31c52ed46822eee7fb5e0/src/main/java/com/github/steveice10/mc/protocol/data/game/chunk/Chunk.java#L69
If this condition is true https://github.com/Steveice10/MCProtocolLib/blob/976c2d0f8900d11817f31c52ed46822eee7fb5e0/src/main/java/com/github/steveice10/mc/protocol/data/game/chunk/Chunk.java#L73
and bitsPerEntry is incremented to 9 we are in the case I described earlier.

So, when bitsPerEntry > 8 (second condition of the ternary operator) we have
https://github.com/Steveice10/MCProtocolLib/blob/976c2d0f8900d11817f31c52ed46822eee7fb5e0/src/main/java/com/github/steveice10/mc/protocol/data/game/chunk/Chunk.java#L83-L84
I would have expect this:
```
 this.storage = oldStorage.transferData(this.bitsPerEntry, (index) -> 
         this.bitsPerEntry <= 8 ? oldStorage.get(index) : oldStates.get(oldStorage.get(index))); 
```

**Comment by MatteCarra** [comment]
@Steveice10 @DoctorMacc @RednedEpic @rtm516 @Tim203

**Comment by MatteCarra** [comment]
I can make a pull request myself, but I would like to have a confirmation that this is a bug.

**Comment by Camotoy** [comment]
Just acknowledging I saw this! I'm not an expert in chunk data this far down so I'm unsure.

**Comment by Camotoy** [comment]
Do you think #582 is related?

**Comment by Steveice10** [comment]
I will try to take a closer look at this issue over the weekend.

**Comment by Steveice10** [comment]
Just pushed a full clean-up of the chunk storage code that should resolve any issues. From a basic client login test it seems to be functioning okay, but let me know if there's anything I overlooked.

**Comment by DaMatrix** [comment]
I tried plugging 2ac116a075fabd57ba8c23dd676a3dd185afe87d into Geyser, and basically everything relating to chunk caching no longer functions (returning invalid block IDs on block accesses). Unfortunately I don't have time for more extensive debugging, but I think something in your new commit is not quite right.

**Comment by MatteCarra** [comment]
I will have a look at the code this weekend.

While I'm at it, could you provide me a link to the new 1.16.* chunk changes?
I think I understood the concept behind it, but I have no idea where you found the MAGIC_VALUES and such.
I saw some other things that might be broken 1.16.* forward if I got the concept behind MAGIC_VALUES correctly.

**Comment by Steveice10** [comment]
The magic values are also what vanilla Minecraft use. I'm not sure where they come from exactly.

**Comment by MatteCarra** [comment]
Did you find them by decompiling Minecraft sources?
Could you please point me to the package and class I have to look for?
Thanks in advance.

**Comment by Steveice10** [comment]
Look for the BitStorage class.

**Comment by MatteCarra** [comment]
I think there might be a misunderstanding.
I'm asking where and how you found the MAGIC_VALUES that you are using in the BitStorage class, and where you found divideMultiply, divideAdd, divideShift formulas.

**Comment by Steveice10** [comment]
Yes, the class in vanilla is also called BitStorage.

**Comment by MatteCarra** [comment]
Yes, I think I was correct, but you fixed it then last commits.

So this is what I understood: Mojang gave up some space efficiency since Minecraft 1.16, by guaranteeing that a number is not stored across two different longs.
In the past if you had bits_per_entry=17, the first 3 numbers would be stored in one long, the 4th would be stored across two longs, by using the last 13 bits of the first long and 4 bits of the following.
Minecraft 1.16.* instead just wasted the last 13 bits of each long.

The problem that caused issue #582 was that you were still calculating the size (that you used to check for out of bound access in the FlexibleStorage) in the old way (optimal space efficiency): https://github.com/Steveice10/MCProtocolLib/blob/ddd5b3a03467bdabf3d22a4c3b88ffcc52ba1dce/src/main/java/com/github/steveice10/mc/protocol/data/game/chunk/FlexibleStorage.java#L51

You correctly hard coded the size to 4096 now.

**Comment by Steveice10** [comment]
Yep, I decided to just go through and synchronize how everything works with how it does in 1.16, plus some clean-ups like making the Palette classes to remove a bunch of bitsPerEntry checks.

**Comment by Steveice10** [comment]
I will go ahead and close this since the particular bugs in this issue have been resolved. If any new chunk related bugs crop up from the clean-up, please open a new issue.
