### ISSUE TITLE
PROXY

### ISSUE THREAD

**Issue by Piter1x** [GeyserMC/MCProtocolLib#581]
How to write own proxy discord: ●DJ PITER●#0003

**Comment by Piter1x** [comment]
pls help discord: ●DJ PITER● 0003

**Comment by wh1trope** [comment]
This section is for bug reporting, not for ask how to write a proxy.

**Comment by Piter1x** [comment]
???????

**Comment by Piter1x** [comment]
mozesz po polsku?

**Comment by michalkacz** [comment]
wykurwiscie sie bawisz qln

**Comment by HexlinGoidownik** [comment]
XDDDDDDDDDDDDDDDDDDDD

**Comment by piterex13** [comment]
dobra podrobka

**Comment by piterex13** [comment]
ale co ty pierdolisz

**Comment by freedyfazbear** [comment]
Nikt ci nie pomoże, jak nie wiesz jak to robic to sie nie bierz za to. A po drugie, to repozytorium jest angielskie i nikt z polski ci nie pomoże. A zaczynajac temat po angielsku, poczym piszac znaki zapytania i pozniej piszac "mozesz po polsku?" to trzeba miec 400iq i być bigbrainem.
