### ISSUE TITLE
1.16.3 Release

### ISSUE THREAD

**Issue by PaulBGD** [GeyserMC/MCProtocolLib#591]
There's no tag, so jitpack doesn't seem to be picking it up! I could just be using jitpack wrong though, I suppose.

**Comment by Steveice10** [comment]
Yes, there is no release build yet, and hence no tag. If you want you can target branches or specific commits using jitpack.

**Comment by PaulBGD** [comment]
Ah ok, that's fine. Is there anything that's a blocker for a 1.16 release?

**Comment by Steveice10** [comment]
The last blocker I'm aware of just got resolved, so assuming nothing crops up I'll be doing a release tag soon.

**Comment by Steveice10** [comment]
1.16.3 release has been tagged, 1.16.4 will be tagged in the near future if stable.
