### ISSUE TITLE
1.8 send chunk error

### ISSUE THREAD

**Issue by slowAccount0** [GeyserMC/MCProtocolLib#593]
When I send a packet for chunk, I get an error in the console. Please help. Version mcprotocollib 1.8
Code:
![image](https://user-images.githubusercontent.com/71569534/97093667-3527e800-164e-11eb-95f8-cc48a9e0b813.png)

![image](https://user-images.githubusercontent.com/71569534/97093622-dc584f80-164d-11eb-8d0b-0f32435b64c3.png)
![image](https://user-images.githubusercontent.com/71569534/97093638-fe51d200-164d-11eb-8728-102a329cd6e4.png)

**Comment by Steveice10** [comment]
Each chunk is a 16x16x16 block; Y 76 is out of the bounds of a single chunk. Instead you'll want to find the right chunk in the column and set the right block coordinate within that. I believe that would be chunk 4 in the column and Y 12.

Also, older versions of Minecraft are not actively supported.
