### ISSUE TITLE
Work can we move client ?

### ISSUE THREAD

**Issue by GrayR0ot** [GeyserMC/MCProtocolLib#594]
Hi,

I'm looking to make my client move like a random player. I'm using new PlayerMovePacket but we can't add any argument. Is there a way or not currently possible ?

Thanks

**Comment by Steveice10** [comment]
That's the base class. You'll want to use specific subclasses like ClientPlayerPositionPacket or ClientPlayerPositionRotationPacket. There should be some older closed issues from people getting their clients to moved if you need something to reference.
