### ISSUE TITLE
Packets

### ISSUE THREAD

**Issue by slowAccount0** [GeyserMC/MCProtocolLib#595]
Hi, how to get full packet that is sent to the server without "@719d80dc"? 
Example packet: ServerChunkDataPacket@719d80dc

**Comment by Steveice10** [comment]
Are you sure you're using the latest version of the library? All packets should have auto-generated toString methods.

**Comment by slowAccount0** [comment]
I am using version 1.8 of mcprotocollib. I fixed this bug using the toString method.

**Comment by Steveice10** [comment]
Okay. For future reference, support for older library versions is not provided.
