### ISSUE TITLE
How to get chat message as you would see in game?

### ISSUE THREAD

**Issue by a8underscore** [GeyserMC/MCProtocolLib#603]
I tried using
`Message messagepacket = event.<ServerChatPacket>getPacket().getMessage();`
and then using gson to get the message, but so much servers all have different ways of sending messages

**Comment by Steveice10** [comment]
You'll have to process the message based on what subclass it is; for example, a TextMessage just has the message content as plain text, and a TranslationMessage contains both a translation key to indicate what kind of message it is and formatting parameters to fill in placeholders.

You'll also have to make sure to pay attention to the MessageStyle for things like colors, formatting, etc. Messages can also have multiple children that follow their content, which you can retrieve with getExtra.
