### ISSUE TITLE
Invalid dimension CompoundTag in example

### ISSUE THREAD

**Issue by ghost** [GeyserMC/MCProtocolLib#604]
Hello!

I just tried to run a sample server on mcprotocollib and when I try to join the server using a Minecraft client I get this error.
![image](https://user-images.githubusercontent.com/69810642/99825731-b3957e00-2b57-11eb-92c0-c21b726997a4.png)

I used exactly the same code as in the example.
After ServerJoinGamePacket I added ServerRespawnPacket because without it my client was crashing when I tried to join the server.

Can you fix it?

**Comment by Camotoy** [comment]
To verify: you're on the latest 1.16.4 MCProtocolLib build?

**Comment by ghost** [comment]
Yes

**Comment by ghost** [comment]
Okay, I found a solution.
I used optifine and it caused the error
