### ISSUE TITLE
Minecraft Account Migration

### ISSUE THREAD

**Issue by MatteCarra** [GeyserMC/MCProtocolLib#610]
Microsoft has started migrating Mojang accounts to Minecraft accounts: https://help.minecraft.net/hc/en-us/articles/360050865492-JAVA-Account-Migration-FAQ
Is there a documentation anywhere about this or do we need to reverse engineer it?
I'm looking forward to work on this.
Thanks

**Comment by Steveice10** [comment]
See https://github.com/Steveice10/MCAuthLib/issues/9

**Comment by MatteCarra** [comment]
Thanks a lot, I'm starting to test the new authentication.
I will try sending a PR if I find a good enough solution.
