### ISSUE TITLE
Support for HAProxy PROXY protocol

### ISSUE THREAD

**Issue by mikroskeem** [GeyserMC/MCProtocolLib#611]
Adding support for both server and client parts in this library would be wonderful for various purposes (server - obvious; client - see Geyser for a good example)

I have a part done already in https://github.com/GeyserMC/Geyser/pull/1688, I'd like to know whether this feature would be accepted here or not.

**Comment by Steveice10** [comment]
Never heard of this before, but briefly looking through the PR you linked I don't see why I wouldn't accept it, if it's just some optional extra support code at the connection layer.

This would probably be more appropriate for the PacketLib repository than here, though.

**Comment by mikroskeem** [comment]
I'll open a PR to PacketLib at some point then.

**Comment by mikroskeem** [comment]
Client support added. I think this issue be kept open in case I or someone else PRs PROXY protocol support for server side as well.

**Comment by Steveice10** [comment]
For cleanliness sake I will close this issue, if server side support is ever desired it would probably be more appropriate as a PacketLib issue anyway.
