### ISSUE TITLE
Move on join

### ISSUE THREAD

**Issue by vinaidex** [GeyserMC/MCProtocolLib#616]
Hello, I need my bot to go several blocks in front after spawn, can you please tell me how to do this? 
(I use google translator)

**Comment by fikawka** [comment]
Move packet??

**Comment by vinaidex** [comment]
> Move packet??


For some reason it didn't work for me, can you give me the code?

**Comment by monobrov1234** [comment]
just send ClientPacketTeleportConfirm if receive is ServerPositionRotation packet and try to send move packets

if (receiveEvent.getPacket() instanceof ServerPlayerPositionRotationPacket) {
ServerPlayerPositionRotationPacket posPacket = receiveEvent.getPacket();
bot.getSession().send(new ClientTeleportConfirmPacket(posPacket.getTeleportId()));
}

**Comment by vinaidex** [comment]
> just send ClientPacketTeleportConfirm if receive is ServerPositionRotation packet and try to send move packets
> 
> if (receiveEvent.getPacket() instanceof ServerPlayerPositionRotationPacket) {
> ServerPlayerPositionRotationPacket posPacket = receiveEvent.getPacket();
> bot.getSession().send(new ClientTeleportConfirmPacket(posPacket.getTeleportId()));
> }

It does not work for me

**Comment by Steveice10** [comment]
I would recommend you check out https://wiki.vg/ as a good resource on all the packets available and how they work. This area is more for reporting bugs with the library and making feature requests, not getting help with using the Minecraft protocol.
