### ISSUE TITLE
bot falling handle

### ISSUE THREAD

**Issue by monobrov1234** [GeyserMC/MCProtocolLib#617]
How to handle falling of the bot?
or check if block in current position equals air

**Comment by Steveice10** [comment]
You should check for movement packets from the server to keep track of your position, as well as retaining data from chunk packets so you know the contents of the world.

**Comment by monobrov1234** [comment]
how to find out which chunk the bot is in?

**Comment by Steveice10** [comment]
If you take the position and divide by 16 (or bit shift right by 4), you should get the chunk coordinates. Likewise, if you take the position and modulo 16 (or bitwise-AND with 15), you should get the player's coordinates within the chunk.
