### ISSUE TITLE
Get player skins (tablist icons) while in offline mode

### ISSUE THREAD

**Issue by tycrek** [GeyserMC/MCProtocolLib#618]
My current project is a "proxy" of sorts for a specific group of Minecraft servers. The project connects your MC account to a server and also hosts its own server for the player to connect to. While the player is connected, the "proxy" forwards packets back and forth between the player and the server. If the players client crashes or their internet goes down, the account can still be logged in to the server.

Currently, we run the proxy servers with `server.setGlobalFlag(MinecraftConstants.VERIFY_USERS_KEY, false);` because we also use a Bungee server for connecting players. In total, players can connect to the target server in 3 ways:

1. Direct connection (proxy client must be offline, otherwise two of the same account try to join the same server)
2. Connect to proxy server directly (most common)
3. Connect to Bungee, then to proxy

When using number 3, player icons appear fine, most likely because the Bungee server is in online mode. However with number 2, they do not show up. I am aware this is by design; when we set `VERIFY_USERS_KEY` to `true`, icons appear fine.

What I am wondering is if it is possible to still get player skins for the tablist while in offline mode (`VERIFY_USERS_KEY` is `false`). I have searched through [Wiki.vg](https://wiki.vg/index.php?title=Protocol&oldid=14204#Player_List_Item) ([this](https://wiki.vg/Mojang_API#UUID_-.3E_Profile_.2B_Skin.2FCape) as well), [FastLogin](https://github.com/games647/FastLogin) (which we cannot use because our proxy is not a Spigot server), [CraftAPI](https://github.com/games647/CraftAPI) (unsure if this is applicable to what I need), [these lines](https://github.com/Steveice10/MCProtocolLib/blob/master/src/main/java/com/github/steveice10/mc/protocol/ServerListener.java#L106-L110) and [these lines](https://github.com/Steveice10/MCProtocolLib/blob/master/src/main/java/com/github/steveice10/mc/protocol/ServerListener.java#L184-L217) in [`ServerListener.java`](https://github.com/Steveice10/MCProtocolLib/blob/master/src/main/java/com/github/steveice10/mc/protocol/ServerListener.java), and [`    public GameProfile getProfileByServer`](https://github.com/Steveice10/MCAuthLib/blob/master/src/main/java/com/github/steveice10/mc/auth/service/SessionService.java#L71-L88) in [MCAuthLib `service/SessionService.java`](https://github.com/Steveice10/MCAuthLib/blob/master/src/main/java/com/github/steveice10/mc/auth/service/SessionService.java).

Most session-related things I've been able to figure out fine until now, but this part has be stumped. Any suggestions on how this can be accomplished?

**Comment by Steveice10** [comment]
I think the issue you're having is because in offline mode, Minecraft uses [a special UUID from on "OfflinePlayer:<username>"](https://wiki.vg/Protocol#Spawn_Player), which the client can't resolve a skin from. You'll need to do something like BungeeCord does [here](https://github.com/SpigotMC/BungeeCord/blob/c987ee199d3ec93ce13469deefb1e2787d97147c/proxy/src/main/java/net/md_5/bungee/tab/TabList.java#L26) to rewrite player list entry packets going from server to client such that the offline-mode UUID is replaced with a player's real UUID.

**Comment by tycrek** [comment]
> 
> 
> I think the issue you're having is because in offline mode, Minecraft uses [a special UUID from "OfflinePlayer:<username>"](https://wiki.vg/Protocol#Spawn_Player), which doesn't correspond to any real player. You'll need to do something like BungeeCord does [here](https://github.com/SpigotMC/BungeeCord/blob/c987ee199d3ec93ce13469deefb1e2787d97147c/proxy/src/main/java/net/md_5/bungee/tab/TabList.java#L26) to rewrite player list entry packets going from server to client such that the offline-mode UUID is replaced with a player's real UUID. You'll also need to copy the player's real profile properties into player list packets that add a player.
> 
> As a side note in case it's helpful, if at any point in your proxy you need to turn a UUID into a full profile, you should be able to use SessionService.fillProfileProperties with an empty GameProfile created from the UUID.

Thanks a bunch for the info, I'll try those out and get report back

**Comment by tycrek** [comment]
@Steveice10 took a stab at it with no luck. Here's my code in case you can spot anything:

```java
@Override
    public ServerPlayerListEntryPacket apply(ServerPlayerListEntryPacket packet, RMSProxyServer.RMSProxyServerConnection session) {
        List<PlayerListEntry> newEntries = new ArrayList<>();
        for (PlayerListEntry entry : packet.getEntries()) {
            if (entry.getProfile().getId() == null) continue;

            PlayerListEntry e = new PlayerListEntry(new GameProfile(entry.getProfile().getId(), entry.getProfile().getName()), entry.getGameMode(), entry.getPing(), entry.getDisplayName(), false);

            if (entry.getProfile().getProperties().size() > 0) {
                GameProfile.Property oldProp = entry.getProfile().getProperties().get(0);
                
                // Decode the JSON from the old property and set signatureRequired to false
                String newValue = new String(Base64.getDecoder().decode(oldProp.getValue().getBytes(StandardCharsets.UTF_8))).replace("true,", "false,");
                
                // Create a new property, re-encoded to base64
                GameProfile.Property newProp = new GameProfile.Property(oldProp.getName(), Base64.getEncoder().encodeToString(newValue.getBytes(StandardCharsets.UTF_8)));
                e.getProfile().getProperties().add(newProp);
            }

            newEntries.add(e);
        }
        return new ServerPlayerListEntryPacket(packet.getAction(), newEntries.toArray(new PlayerListEntry[0]));
    }
```

This is in the **outgoing** packet handler from the proxy server (offline mode) to the players game.

**Comment by tycrek** [comment]
```json
{
   "timestamp" : 1614619008497,
   "profileId" : "2934b03674af4aafb8f54eb9b1264776",
   "profileName" : "WabbitEmu",
   "signatureRequired" : false,
   "textures" : {
     "SKIN" : {
       "url" : "http://textures.minecraft.net/texture/d9312b3018e938685dfcf7103676538421bda8fb550cf934093ce76cb146ad51"
     }
   }
 }
```

this is the un-encoded value of `newProp`

**Comment by tycrek** [comment]
Looked in `latest.log` and found this:

`[10:45:53] [pool-3-thread-16/ERROR] [com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService]: Signature is missing from textures payload`

**Comment by Steveice10** [comment]
I don't think the client will accept it if you don't have a signature attached to the texture payload.

**Comment by Steveice10** [comment]
In the case of BungeeCord I believe this is how it works:

* BungeeCord is in "online mode" so it authenticates users, actual Minecraft servers behind it are in offline mode so they don't.
* When a player authenticates with BungeeCord, their real profile is cached.
* When the offline mode server sends a player list entry packet to BungeeCord, BungeeCord replaces the offline mode profile with the player's real profile cached from when they were authenticated.

**Comment by Steveice10** [comment]
It would help if you could lay out in a simple diagram or something what parts of your setup are connecting in online or offline mode, by the way.

**Comment by tycrek** [comment]
![image](https://user-images.githubusercontent.com/29926144/109559499-f8ef1300-7a97-11eb-8734-fb5f0ce18aca.png)

In the top scenario, players who connect to the proxy directly *cannot* see player icons, but players who connect via BungeeCord *can*.

In the bottom scenario, players who connect to the proxy *can* see player icons, but Bungee is now unable to forward players to their proxies.

> However BungeeCord has the advantage of authenticating with all connected players, whereas your proxy (if I understand correctly) will not and thus won't have everyone's profiles cached already.

I think I understand. Only one player connects to each proxy at a time. The proxy does have a tablist cache of every player and it sends these entries to the player on join.

I've logged each step of the process and I don't run into `OfflinePlayer:` anywhere, regardless if MCProtocolLib's server is online or offline

**Comment by Steveice10** [comment]
It's rather strange then that you aren't seeing player icons, since the list entries are being forwarded from an online-mode server. Might need to do some more research on this.

**Comment by tycrek** [comment]
Does MCProtocolLib's client automatically handle `EncryptionResponsePacket` and `EncryptionRequestPacket` from the target server? I believe the server portion of the lib does since I can get icons in online mode.

**Comment by Steveice10** [comment]
Yes, it does.

Could you print and share a sample of the player list entry packets you're getting from the target server on the proxy?

**Comment by Steveice10** [comment]
Actually, I think I have found the problem. I looked through decompiled client code for the player tab list, and it seems that if the client does not have an online-mode connection, it will not draw player heads.

**Comment by tycrek** [comment]
Ahhh ok, I see. Thank you for your help :)
