### ISSUE TITLE
Maven Central?

### ISSUE THREAD

**Issue by artnaseef** [GeyserMC/MCProtocolLib#619]
This project is awesome.  Thank you for the effort.

I was wondering if there are plans to publish the artifacts to Maven central.  While I appreciate the jitpack.io repository, my concern is security of the artifacts.

If you are considering it and want help, I can assist.

Thank you!

**Comment by Steveice10** [comment]
Thanks for the interest, but as I have been more casually maintaining this project these days I don't currently have any plans to set up and maintain artifacts in Maven central. Jitpack has been the most convenient way for me to provide artifacts to users of Maven and other dependency management systems without much effort on my part. So far I have had no reason to be concerned about the security of Jitpack, but if it is a problem for you there is always the option of compiling your own copies of artifacts from source.

**Comment by artnaseef** [comment]
Thank you for the response.  Somehow the other day, when I looked at the jitpack.io website, I only found a landing page with no other information nor links.  Today, I see all the documentation, including how artifacts get uploaded there.  That helps a lot.

FYI - I use OSSRH for Maven Central.  It appears to be similar to jitpack except for doing the builds itself.
