### ISSUE TITLE
Bot falling

### ISSUE THREAD

**Issue by maks1mov** [GeyserMC/MCProtocolLib#622]
How to make the bot react to the fall? For example, when a block is broken under it, he falls

**Comment by Steveice10** [comment]
If I remember correctly, the server will send you a ServerPlayerPositionRotationPacket or similar to indicate the player should move (in this case downwards), and the client will need to respond with a ClientTeleportConfirmPacket for each movement.

In general, I would recommend using https://wiki.vg/ as a good protocol resource. This area is more for reporting bugs with the library or making feature requests, not for help using the Minecraft protocol.
