### ISSUE TITLE
Bug with crafting books?

### ISSUE THREAD

**Issue by THCFree** [GeyserMC/MCProtocolLib#623]
Im not really sure if its a mcprotocollib issue but when you try to open a craftng book in any inventory kicks the user throwing a UnmappedValueException,
![jjCWG2zV](https://user-images.githubusercontent.com/65246569/112977705-a700e200-9156-11eb-9f49-c18ad6c1d14e.png)

**Comment by THCFree** [comment]
Thanks in advance for looking into it

**Comment by Steveice10** [comment]
Can you check if https://github.com/Steveice10/MCProtocolLib/commit/afca99c03994c04e81ebd8729154d4fa7517a0b1 fixes the issue?

**Comment by THCFree** [comment]
Tackling some problems and ill test it quick question did you remove the package message and all the classes inside for any reason in specific?

**Comment by THCFree** [comment]
Yea solves it ill close the issue thanks for looking into it :D
