### ISSUE TITLE
1.16.5

### ISSUE THREAD

**Issue by Valdoum** [GeyserMC/MCProtocolLib#624]
Could you update it for 1.16.5 pls ?

**Comment by Steveice10** [comment]
As far as I'm aware 1.16.4 and 1.16.5 are protocol-compatible, but I can get the version string updated soon just to be completely up-to-date.

**Comment by Camotoy** [comment]
Yes, 1.16.4 and 1.16.5 are protocol-compatible. You should have no issues with using MCProtocolLib.

**Comment by Steveice10** [comment]
https://github.com/Steveice10/MCProtocolLib/commit/19a928364ab23a64ce43e418ccfa9bcd4fcacf28
