### ISSUE TITLE
migration to new api

### ISSUE THREAD

**Issue by RumoEL** [GeyserMC/MCProtocolLib#627]
I am using third party code that uses an older version of your library.
what to replace this code with?

Chunk chunk=new chunk(true);//arg true
if(chunk.getBlocks() == null){//method getBlocks()
}
chunk.getBlocks().fill(0);//fill in getBlocks()

**Comment by Steveice10** [comment]
Without additional context behind what the code is doing, probably just create a new Chunk with no arguments and that's it.
