### ISSUE TITLE
Unable to set server brand

### ISSUE THREAD

**Issue by cubeserverdev** [GeyserMC/MCProtocolLib#628]
I am trying to set the server brand to "TestBrand" through a ``ServerPluginMessagePacket`` packet as specified in step 11 of the [normal login sequence for a client](https://wiki.vg/Protocol_FAQ#What.27s_the_normal_login_sequence_for_a_client.3F) but the client seems to still display ``null`` as the server brand. What am I doing wrong?

Relevant code:
```java
server.setGlobalFlag(MinecraftConstants.SERVER_LOGIN_HANDLER_KEY, (ServerLoginHandler) session -> {
    session.send(new ServerPluginMessagePacket("minecraft:brand", "TestBrand".getBytes()));
    session.send(new ServerJoinGamePacket(0, false, GameMode.CREATIVE, GameMode.CREATIVE, 1, new String[]{"minecraft:world"}, Util.getDimensionTag(), Util.getOverworldTag(), "minecraft:world", 100, 0, 16, false, false, false, false));
    session.send(new ServerPlayerAbilitiesPacket(true, true, true, false, 0.4f, 0.7f));
    session.send(new ServerSpawnPositionPacket(new Position(0, 128, 0)));
    session.send(new ServerPlayerPositionRotationPacket(0, 128, 0, 0, 0, 0));
});
```
Minecraft client debug menu:
![image](https://user-images.githubusercontent.com/83846259/117517626-98ce8e80-af6a-11eb-8f74-637956cb1216.png)

**Comment by Steveice10** [comment]
According to [this wiki page](https://wiki.vg/Plugin_channels#minecraft:brand) the message should be sent *after* the join game packet, so I would try that first and see if it works.

**Comment by cubeserverdev** [comment]
Sending the branding packet after the join game packet doesn't seem to work either.

**Comment by Steveice10** [comment]
Upon further research, it seems your payload will need to be prefixed with the string's length in varint format. You could leverage existing code from the library to assist in doing this like so (AFAIK vanilla leverages its own packet serialization code in the same way):

```java
ByteArrayOutputStream bOut = new ByteArrayOutputStream();
StreamNetOutput sOut = new StreamNetOutput(bOut); // Class from included PacketLib.
sOut.writeString("TestBrand");

byte[] payload = bOut.toByteArray();
session.send(new ServerPluginMessagePacket("minecraft:brand", payload));
```

**Comment by cubeserverdev** [comment]
That seems to have fixed it. Do all plugin message packets need to be prefixed with the string's length like this, or is this only the case for the branding packet?

**Comment by Steveice10** [comment]
I think it will depend on the channel; the packet itself only seems to define the channel string and a plain array of bytes to follow. It might be safe to assume that any official channel that uses a string for the data is written like this.

**Comment by cubeserverdev** [comment]
I'll assume so as well. Thank you for the help!
