### ISSUE TITLE
Trouble sending chunks to player

### ISSUE THREAD

**Issue by cubeserverdev** [GeyserMC/MCProtocolLib#629]
I am trying to send some chunks to a player, but the client doesn't seem to be receiving the ``ServerChunkDataPacket`` packet being sent in my ``ServerLoginHandler``. The client actively displays "Waiting for chunk.." in the debug info menu. Am I misunderstanding something about how I need to be using the ``Chunk`` and ``Column`` classes?

```java
Chunk chunk = new Chunk();
Chunk[] chunks = new Chunk[16];

for (int x = 0; x < 16; x++) {
    for (int y = 0; y < 16; y++) {
        for (int z = 0; z < 16; z++) {
            chunk.set(x, y, z, 1);
        }
    }
}

for (int i = 0; i < chunks.length; i++) {
    chunks[i] = chunk;
}

session.send(new ServerChunkDataPacket(new Column(0, 0, chunks, new CompoundTag[0], new CompoundTag(""))));
```

**Comment by Steveice10** [comment]
Chunks are always rough because they keep changing how the packets work. That being said, a few things I can think of:
* When you initially send chunks they should be what is considered "full chunks". In order for this to be the case, you need to use the other constructor of Column that includes biome data.
* This I am not fully sure is necessary to get chunks loaded, but you may need to set up the heightMaps NBT compound tag you are providing [as described here](https://wiki.vg/Protocol#Chunk_Data), rather than passing an empty tag with a blank name.

**Comment by cubeserverdev** [comment]
Passing in ``biomeData`` and ``heightMaps`` seems to have made it work but for some reason the client doesn't actually render the block textures until one of the blocks in the chunk is broken. 

![image](https://user-images.githubusercontent.com/83846259/117557528-9854f700-b041-11eb-88d4-630b84162294.png)


Relevant code: 
```java
Chunk chunk = new Chunk();
for (int x = 0; x < 16; x++) {
    for (int y = 0; y < 16; y++) {
        for (int z = 0; z < 16; z++) {
            chunk.set(x, y, z, y == 0 ? 1 : 0);
        }
    }
}

Chunk[] chunks = new Chunk[16];
chunks[5] = chunk;
session.send(new ServerChunkDataPacket(new Column(0, 0, chunks, new CompoundTag[0], new CompoundTag("MOTION_BLOCKING"), new int[1024])));
```

**Comment by Steveice10** [comment]
Not sure it will help with that but perhaps try also sending ServerUpdateLightPacket for the column you're sending? The idea being maybe it's not rendering because it hasn't received lighting data...?

**Comment by Steveice10** [comment]
Other idea is maybe it isn't rendering because the rendering relies on an accurate height map being generated instead of just an empty compound tag.

**Comment by Steveice10** [comment]
Lastly, there is a note on [this page](https://wiki.vg/Chunk_Format) that the "client does not render chunks that lack neighbors", which is probably the most promising lead. Maybe try sending more columns neighboring the center?

**Comment by cubeserverdev** [comment]
Sending a ``ServerUpdateLightPacket`` packet didn't seem to change the output. Passing in a height map didn't seem to change much either other than cause the client to display the "Waiting for chunks.." message to appear in the F3 menu. I'm most definitely messing something up but I'm just unable to put my finger on it.

```java
Chunk chunk = new Chunk();
for (int x = 0; x < 16; x++) {
    for (int y = 0; y < 16; y++) {
        for (int z = 0; z < 16; z++) {
            chunk.set(x, y, z, y == 0 ? 1 : 0);
        }
    }
}

Chunk[] chunks = new Chunk[16];
chunks[5] = chunk;
CompoundTag heightMap = new CompoundTag("MOTION_BLOCKING");
long[] heightMapArray = new long[256];
for (int i = 0; i < heightMapArray.length; i++) {
    heightMapArray[i] = 81;
}
// heightMap.put(new LongArrayTag("MOTION_BLOCKING", heightMapArray)); // Uncommenting this line causes the client to display the "Waiting for chunk.." message in the F3 menu.
session.send(new ServerChunkDataPacket(new Column(0, 0, chunks, new CompoundTag[0], heightMap, new int[1024])));
NibbleArray3d[] skyLight = new NibbleArray3d[18];
for (int i = 0; i < skyLight.length; i++) {
    skyLight[i] = new NibbleArray3d(1);
}
session.send(new ServerUpdateLightPacket(0, 0, false, skyLight, skyLight));
```

**Comment by Steveice10** [comment]
See my third post, it's most likely due to the client apparently not rendering chunks with no neighbors.

**Comment by cubeserverdev** [comment]
Oh, I saw your message after I sent my message. Sending more chunks to act as neighbors did seem to fix the rendering issue though!

Thanks again for the swift help, I appreciate it a lot.

**Comment by cubeserverdev** [comment]
Somewhat unrelated but does this library provide a Block/Material enum/utility that I can use to easily lookup block values while I'm trying to change the blocks within a chunk?

**Comment by Steveice10** [comment]
Unfortunately no, it does not provide an enumeration of blocks as their IDs rather volatile.
