### ISSUE TITLE
Server Clients stuck on "Loading Terrain"

### ISSUE THREAD

**Issue by madelynwith5ns** [GeyserMC/MCProtocolLib#630]
Using [this code](https://pastebin.com/ZvqCwPXb) the client when connecting using vanilla 1.16.5 just gets stuck on "Loading Terrain" indefinitely:
![image](https://user-images.githubusercontent.com/61560519/119572578-93e64900-bd78-11eb-842f-bae0edbad049.png)

I've tried sending the packet (`ServerJoinGamePacket`) multiple times or delaying it. I've also tried setting the dimension tags to `null` which went about as well as you'd expect.

I based this on an older commit of the example code given that `TcpServer` wasn't found in the 1.16.5-1 release.

**Comment by Steveice10** [comment]
You will probably just need more than ServerJoinGamePacket to get a vanilla client to go in-game properly. A good resource for the typical login packet sequence can be found [here](https://wiki.vg/Protocol_FAQ#What.27s_the_normal_login_sequence_for_a_client.3F), and there are multiple closed issues around sending things like chunk data that you could check out.

**Comment by madelynwith5ns** [comment]
Thanks for the help, I'll check it out.
