### ISSUE TITLE
physics

### ISSUE THREAD

**Issue by mitchmckinstry** [GeyserMC/MCProtocolLib#635]
Hi, I am trying to create a player that can move and look like a regular player, I was wondering how I can add the physics as the player currently just floats. I was also wondering how to simulate the inputs (like W, A, S, D, Jump, etc) to go along with the physics.

**Comment by mitchmckinstry** [comment]
I know how to move a player using
`new ClientPlayerPositionPacket()`
but I don't know how to stop the player from floating and to make the player move and step up on to slabs automatically.

**Comment by Steveice10** [comment]
You're going to need to implement the physics on the client side like the vanilla client does. This is out of the scope of MCProtocolLib.
