### ISSUE TITLE
Send player to other server

### ISSUE THREAD

**Issue by majorek31** [GeyserMC/MCProtocolLib#639]
Hi, i want to send player to other server if he's connecting through  ex. "play.myserver.com" 
i want to made it like:
if (e.getPacket() instanceof HandshakePacket){
 HandshakePacket = e.getPacket();
 if (packet.getHostname().equals("play.myserver.com")){
  // send the player to server 127.0.0.1:25567
}
}
but i don't know how to send player to this server

**Comment by majorek31** [comment]
@Steveice10 can you help me? plz

**Comment by Steveice10** [comment]
That's not really something you can just do so easily. Existing solutions like BungeeCord work by acting as a proxy for all network traffic, implementing some logic to login to/switch between servers and otherwise forwarding traffic.
