### ISSUE TITLE
throw exception when trying to connect to server

### ISSUE THREAD

**Issue by Nanboom233** [GeyserMC/MCProtocolLib#642]
- Disconnected: io.netty.handler.codec.DecoderException: com.google.gson.JsonParseException: Don't know how to turn null into a Component
- io.netty.handler.codec.DecoderException: com.google.gson.JsonParseException: Don't know how to turn null into a Component

**Comment by Camotoy** [comment]
We've seen this over at Geyser as well. Is this your server? Is there a stack trace?

**Comment by Nanboom233** [comment]
Sadly it's not my server so I don't know whether there is one or not.

**Comment by Nanboom233** [comment]
Sadly it's not my server.I found the exception when I was using another project program which is using MCProtocolLib library.
I contacted that auther and he told me the exception is throw directly from MCProtocolLib library.

**Comment by Camotoy** [comment]
Having a way to reproduce this would be the most helpful.

**Comment by Steveice10** [comment]
If the program outputs a stack trace to the console or logs, please post that as well. Otherwise I can't tell where exactly the error is coming from.

**Comment by Steveice10** [comment]
Whether or not this is caused by an issue with MCProtocolLib itself, I think that error message is actually coming from the server and not the library itself.

**Comment by Steveice10** [comment]
Whether or not this is caused by an issue with MCProtocolLib itself, the message definitely seems to be coming from the server, not the library. The error message is part of Minecraft's codebase and not Gson in general.
