### ISSUE TITLE
Close Window

### ISSUE THREAD

**Issue by Mcstudio-technik** [GeyserMC/MCProtocolLib#644]
Hi, How can I close inventory?

**Comment by Newspicel** [comment]
Hey I have done a little research,
here the wiki.vg Dokumentation: https://wiki.vg/Protocol#Close_Window_.28clientbound.29
and here the class for the packet: https://github.com/Steveice10/MCProtocolLib/blob/master/src/main/java/com/github/steveice10/mc/protocol/packet/ingame/server/window/ServerCloseWindowPacket.java
