### ISSUE TITLE
Crash report, using forge with optifine and replaymod

### ISSUE THREAD

**Issue by riky-dev** [GeyserMC/MCProtocolLib#645]
I was trying to record some clips on servers.
Whenever i quit the server to save the file, it loads to 4% then i get this error:
[error.txt](https://github.com/Steveice10/MCProtocolLib/files/7025512/error.txt)

Note: in single player it doesnt happen

**Comment by Steveice10** [comment]
* I do not make whatever mod this is, so I don't know what's going on with it.
* I only support the latest version of Minecraft. 1.8.9 is long past.
