### ISSUE TITLE
How to add whitelisted server

### ISSUE THREAD

**Issue by ghost** [GeyserMC/MCProtocolLib#646]
How can I prevent the bot from logging into the server from the .txt file?
whitelist.txt
ip:port

My join server code:
`    public void connect(String ip, int port2) {
        Client client = new Client(ip, port2, this.account, new TcpSessionFactory(this.proxy));
        client.getSession().addListener(new SessionListener(this));
        client.getSession().setConnectTimeout(6000);
        client.getSession().connect();
        this.session = client.getSession();
    }`

**Comment by Steveice10** [comment]
I'm not quite sure I understand, you want a whitelist of IP:Port combinations that you can connect with? Just use a Scanner over a FileInputStream and create a list that you compare to before connecting, or something similar.
