### ISSUE TITLE
Not receiving any packets after handshake + disconnecting after

### ISSUE THREAD

**Issue by ItzAmirreza** [GeyserMC/MCProtocolLib#650]
Hello there,
I started using this library last night and tried this example code provided in repo, but seems there are some additional args added in `TcpClientSession` like `Client` object(which is not stated nor used in test example), and I'm trying to get the status response from the server (I assume I'm doing alright I just followed wiki.vg connection stages), but after sending the handshake and required packets for status, I don't receive any packets from the server and it get's disconnected.
I would appreciate if you could help me out here what's wrong and a proper explanation of `Client`
Here is my code:
```java
public static void startLoop() throws InterruptedException {
        while (true) {

            if (!started) {
                started = true;
                System.out.println("initializing client");
                PacketProtocol packetProtocol = new MinecraftProtocol();
                SessionFactory sessionFactory = new TcpSessionFactory();
                //don't quite understand what's this client over here just filled it because it was needed for TcpClientSession vvv
                Client client = new Client("127.0.0.1", 25565, packetProtocol, sessionFactory);
                //connecting to local spigot server vvv
                Session realClient = new TcpClientSession("127.0.0.1", 25565, packetProtocol, client, null);

                realClient.addListener(new SessionListener() {
                    @Override
                    public void packetReceived(PacketReceivedEvent packetReceivedEvent) {
                        System.out.println("packet received");
                        if (packetReceivedEvent.getPacket() instanceof StatusResponsePacket) {
                            StatusResponsePacket packet = packetReceivedEvent.getPacket();
                            System.out.println("info packet received");
                            System.out.println(packet.getInfo());
                        }
                    }

                    @Override
                    public void packetSending(PacketSendingEvent packetSendingEvent) {

                    }

                    @Override
                    public void packetSent(PacketSentEvent packetSentEvent) {

                    }

                    @Override
                    public void packetError(PacketErrorEvent packetErrorEvent) {

                    }

                    @Override
                    public void connected(ConnectedEvent connectedEvent) {
                        System.out.println("connect");
                    }

                    @Override
                    public void disconnecting(DisconnectingEvent disconnectingEvent) {

                    }

                    @Override
                    public void disconnected(DisconnectedEvent disconnectedEvent) {
                        System.out.println("disconnect");
                    }
                });
                realClient.connect();
                System.out.println("listeners registered");
                if (realClient.isConnected()) {
                    sendInfo(realClient);
                }


            }

        }
    }
    public static void sendInfo(Session client) {
        client.send(new HandshakePacket(754, "127.0.0.1", 25565, HandshakeIntent.STATUS));
        client.send(new ClientRequestPacket(ClientRequest.STATS));
        client.send(new StatusPingPacket(41257));
        System.out.println("HandShake sent");
    }
    ```

**Comment by Steveice10** [comment]
Two things:
* If you still have a Client class at all you are on an older version of PacketLib (and I'm guessing MCProtocolLiv as well), in which case you should go back to an earlier version of the example code from the library version you're trying to use.
* You should not need to handle things like handshake and login packets; MCProtocolLib will handle these for you and take you up until the Play protocol state.

**Comment by ItzAmirreza** [comment]
Sorry maybe I misunderstood but you said `"you are on an older version of PacketLib (and I'm guessing MCProtocolLib as well)"` which is wrong, I don't think I'm using an old version I'm just using jitpack dependency of MCProtocolLib with version 1.16.5,  and then you said `"you should go back to an earlier version of the example code from the library"` which means I'm not using an old version? + I want to handle everything from scratch, from handshaking to play, do you suggest using PacketLib or MCProtocolLib? (I don't know the difference I just came here from wiki.vg reference)

**Comment by Steveice10** [comment]
PacketLib is a dependency of MCProtocolLib, so you don't really need to worry about it too much other than that how you create a client changed in 2.0, which was introduced in MCProtocolLib version "1.16.5-2". As long as you are using that version or later from jitpack there should be no Client class. Otherwise, go back into the example commit history to before the use of Client was removed.

Additionally, if you want to handle everything yourself you will need to set useDefaultListeners to false in your MinecraftProtocol instance before connecting.

**Comment by ItzAmirreza** [comment]
Thank you, I get the code working and packets working but as you said previously, it should lead me directly to the play packet if  I use the default Listeners which I do now, but it gets disconnected after the last ping packet and it doesn't join the server.(As far as I understood default listener also handles the keep alive packet).

![image](https://user-images.githubusercontent.com/20891968/131263190-4e47f27b-cb77-4b80-9ecb-96cb6f1d134c.png)
As you can see, the last packet that is sent by library is Status ping packet. It just get disconnected without any reason(also with disabling default listeners, it happens again) + just to let you know, the server is cracked

**Comment by Steveice10** [comment]
Status ping connections do not reach play, they end after the status request completes. If you want to login and reach ingame state, provide a username to the MinecraftProtocol constructor as in the example code.

**Comment by ItzAmirreza** [comment]
Thanks, the problem is fixed.
