### ISSUE TITLE
Microsoft migration problem

### ISSUE THREAD

**Issue by Kenshayy** [GeyserMC/MCProtocolLib#652]
As stated in the title, a lot of users already migrated to Microsoft authentication, and now we can't use the Lib anymore to authenticate accounts, since it only supports Mojang auth. Is there a way to make it working or we need to wait an update here?

Thanks

**Comment by Steveice10** [comment]
There is an issue and a pull request for this under MCAuthLib if you want to track this problem. It's still marked as a draft though and I'm unaware of its current status.

**Comment by Steveice10** [comment]
The PR has now been merged and Microsoft authentication is available in the latest commit of MCProtocolLib. Feel free to test and report back if there are any problems.

**Comment by Steveice10** [comment]
Note that I don't think 2fa is supported yet, as per https://github.com/GeyserMC/Geyser/issues/2496
