### ISSUE TITLE
Account Migration code Updated

### ISSUE THREAD

**Issue by CaledonianEH** [GeyserMC/MCProtocolLib#658]
I am currently trying to update my project to support the new Microsoft Migration switch, and am having issues finding updated documentation, and more importantly even creating a successful build. I would like to get an example for the new code required. Stacktrace below

`com.github.steveice10.mc.auth.exception.request.InvalidCredentialsException: Invalid credentials. Invalid username or password.`

**Comment by Steveice10** [comment]
Here's an example of an application using it: https://github.com/GeyserMC/Geyser/blob/master/connector/src/main/java/org/geysermc/connector/network/session/GeyserSession.java#L586

I'm guessing by the error string that in your case, you are still using the old authentication service instead of an MsaAuthenticationService.

Do note that support is not complete, e.g. 2FA is not currently supported.

**Comment by Camotoy** [comment]
Using the "authenticate from code" option does allow 2FA: https://github.com/GeyserMC/Geyser/blob/master/connector/src/main/java/org/geysermc/connector/network/session/GeyserSession.java#L633

**Comment by tycrek** [comment]
> old authentication service instead of an MsaAuthenticationService.

Uh-oh... I think the `MsaAuthenticationService` that the Geyser team was working on in a PR for the old (Steveice10's repo) got removed completely when the project transferred ownership to the Geyser team.

@Camotoy Does the Geyser team have plans to bring this back to the current codebase? It worked quite well for my team in the past. Also, are there plans to bring "auth from code" to MCPL as well? It would be incredibly beneficial to our upcoming projects.

**Comment by Camotoy** [comment]
It's all definitely still there. https://github.com/GeyserMC/MCAuthLib/blob/master/src/main/java/com/github/steveice10/mc/auth/service/MsaAuthenticationService.java#L63 with a link to the auth from code.

**Comment by tycrek** [comment]
Ahh my bad, looks like we're still on an old version of AuthLib. Thanks for the quick reply!
