### ISSUE TITLE
Request for Maintainer (FYI)

### ISSUE THREAD

**Issue by ghost** [GeyserMC/MCProtocolLib#659]

**Comment by Camotoy** [comment]
Thanks for reaching out! We’d definitely like to continue maintaining the project as MCProtocolLib has been an integral part of Geyser over the past 2 years that we’ve been utilizing it.

For transparency, some future changes we may implement include changing packet names and fields to match Mojang's own packet mappings (something the Minecraft development community has been attempting in general), as well as potentially utilizing some math and data classes from CloudburstMC.

**Comment by Steveice10** [comment]
Great, thanks for taking it on. I don't think I'm allowed by GitHub to transfer them into your organization directly, but if you remove your personal forks I can transfer the primary repositories to you, and then you can transfer them into the organization or whatever you think is best.

**Comment by lukeeey** [comment]
> Great, thanks for taking it on. I don't think I'm allowed by GitHub to transfer them into your organization directly, but if you remove your personal forks I can transfer the primary repositories to you, and then you can transfer them into the organization or whatever you think is best.
> 
> Let me know if you do so, or otherwise how you would like to proceed.

Hey! Feel free to transfer it to one of us, we're currently deciding which organization is best to house the project.

**Comment by Steveice10** [comment]
> Hey! Feel free to transfer it to one of us, we're currently deciding which organization is best to house the project.

I have sent you transfer requests for each of the repositories.

**Comment by lukeeey** [comment]
> > Hey! Feel free to transfer it to one of us, we're currently deciding which organization is best to house the project.
> 
> I have sent you transfer requests for each of the repositories.

Thank you! I will get it transferred to GeyserMC. I wish you luck on your future endeavours and thank you for this great project! Of course you're welcome to be involved in this future if you wish :)

**Comment by Steveice10** [comment]
Thank you as well for your team's contributions up to now, as well as being willing to fully take on the project. Best of luck with your plans for the future.
