### ISSUE TITLE
Proxy doesn't work

### ISSUE THREAD

**Issue by stenocyb** [GeyserMC/MCProtocolLib#66]
Proxies aren't working. I tried over 15, but none of them worked. I'm using MCProtocolLib 1.8.

My code:
Proxy proxy = new Proxy(Proxy.Type.SOCKS, new InetSocketAddress("59.108.48.37", 8080));
Client client = new Client("localhost", 25565, protocol, new TcpSessionFactory(proxy));
client.connect();

The client does not connect and it throws no exception. I hope you can help me and thanks for this awesome library!

**Comment by Steveice10** [comment]
Proxies have often had issues. It juyst uses normal Java proxies, so I'd expect it to work normally, but for some reason it always seems to have issues. I can't really do much to figure out what's wrong if it isn't giving any sort of error.

If the proxies you've tried are from a common list, try using different proxy sources. It might be a bad list of proxies.

**Comment by stenocyb** [comment]
I tried many proxies and checked them with a tool. The tool said, that these proxies are working. However, when a bot tries to join a server, nothing happens. If I use HTTP(s) proxies, of course, an error occurs, but if I use SOCKS 4/5 proxies, no error occurs. The Socket seems to be created successfully, so there must be a connection problem between the Socket and the minecraft server.

**Comment by Steveice10** [comment]
In that case, have you made sure it works fine without the proxy?

**Comment by stenocyb** [comment]
Yes, everywhing works fine without a proxy.

**Comment by stenocyb** [comment]
I really appreciate your work, but could you try to solve this problem? It would be really nice!

**Comment by Steveice10** [comment]
The problem is, if it isn't a problem with the socket being created or a problem with how the library communicates with a Minecraft server, I have no way of knowing where the problem lies. As long as the socket is being created properly, it should be no different from working without a proxy, unless the proxy itself is problematic.

**Comment by stenocyb** [comment]
I'm not sure if there isn't a problem with your library / the socket. I don't know what the problem is, because I'm not familiar with netty / your librarys. 

Couldn't you add some try-catch blocks to see what the error is (if that helps anything)?
I'm really frustrated, sorry.

**Comment by Steveice10** [comment]
Running the test example with the proxy you gave works fine for me. Seems to be a problem on your end.

**Comment by stenocyb** [comment]
Hm, if I run the test example with a socks proxy, it works. Also on my computer. 

In my project, I'm initializing a final Client variable. That may be the problem. This variable must be final, because I have to put it in an ArrayList. Any solution? Is there a(n other) way to force all the clients to send the same packet?

**Comment by phase** [comment]
if you get the global IP of your computer, you should be able to connect to it using a proxy
