### ISSUE TITLE
Bumping Java software version

### ISSUE THREAD

**Issue by Camotoy** [GeyserMC/MCProtocolLib#660]
We'd like to bump the Java version used in MCProtocolLib and its dependencies to, ideally, Java 16 (to be in line with Java Edition itself). For users of this library, please let us know if that works for your setup or if it's inconvenient.

**Comment by Newspicel** [comment]
Personally, I would find this a good adjustment, which I would welcome very much.

**Comment by tycrek** [comment]
Trying to switch all my/my orgs projects to Java 16, this would be a welcome change!

**Comment by kyngs** [comment]
If this is also a matter of: https://github.com/GeyserMC/PacketLib/; I need that to stay on Java 11, because I cannot find newer for ARMv6. So I have no issue with this bump, but I would be happy if you wouldn't bump PacketLib.

**Comment by ZomkaDEV** [comment]
> If this is also a matter of: https://github.com/GeyserMC/PacketLib/; I need that to stay on Java 11, because I cannot find newer for ARMv6. So I have no issue with this bump, but I would be happy if you wouldn't bump PacketLib.

Why not upgrade to better/newer hardware? Are you using an RPi Zero?

**Comment by SupremeMortal** [comment]
I'm going to have to disagree with this. Bumping the Java version of a library for the sake of keeping it in line with Java Edition, but not using any of the new language features is not worth it. There may also be Android developers that use this library, and moving to Java 16 could make it incompatible.

**Comment by kyngs** [comment]
> > If this is also a matter of: https://github.com/GeyserMC/PacketLib/; I need that to stay on Java 11, because I cannot find newer for ARMv6. So I have no issue with this bump, but I would be happy if you wouldn't bump PacketLib.
> 
> Why not upgrade to better/newer hardware? Are you using an RPi Zero?

Yes, I use an RPi zero, even that is overkill for the task. I am glad that I even managed to find Java 11 for it.

**Comment by MatteCarra** [comment]
I would find the change inconvenient for my usage. I have to agree with SupremeMortal.

**Comment by AlexProgrammerDE** [comment]
![image](https://github.com/GeyserMC/MCProtocolLib/assets/40795980/0c439fae-08d8-452f-9181-e4dab089a24f)
It appears java 17 has been released for raspberry pi zeroes.

**Comment by Camotoy** [comment]
MCProtocolLib now uses Java 17.

**Comment by Konicai** [comment]
Release `1.20.4-1` targets Java 8. Anything forward requires Java 17.
