### ISSUE TITLE
How to get block ID from chunk?

### ISSUE THREAD

**Issue by Tassf** [GeyserMC/MCProtocolLib#661]
(Sorry, I translate via google translator)
Don't throw me over to other links.
I received data about chunks, but when I call the get function on the chunk, it returns not what I need. Here at the stone ID 1, but it gives me 14 or the like. I saw similar questions, where people were told that they need to start the server and take block.json from there, but the IDs still do not converge !!!!! HOW WELL HOW to do it correctly ??????????? I rummaged all over Google, but I did not find ANYTHING. The server on which I play is from version 1.12 - 1.16. Maybe this is the problem? Or whatever. If necessary, I can throw off the code.

**Comment by Tassf** [comment]
I forgot to say...
I am using 1.16.5, I wanted to use 1.12.2 but it disconnects me due to the lack of a CompoundTag class ...

**Comment by Camotoy** [comment]
Hey! Please join GeyserMC's Discord at discord.gg/geysermc for support that doesn't involve bug reports. Thanks! 
(Also note that support for older versions may be limited)
