### ISSUE TITLE
ServerCombatPacket

### ISSUE THREAD

**Issue by t81lal** [GeyserMC/MCProtocolLib#67]
https://github.com/Steveice10/MCProtocolLib/blob/1.8/src/main/java/org/spacehq/mc/protocol/packet/ingame/server/ServerCombatPacket.java#L58

the eventType or state should be a varint according to the wiki. i assume you read a byte because a bigger type hasnt been observed?
<code>
        eventType = in.readVarInt();

```
    if (eventType == 1) {
        duration = in.readVarInt();
        entityId = in.readInt();
    } else if (eventType == 2) {
        playerId = in.readVarInt();
        entityId = in.readInt();
        message = in.readString();
    }
```

 </code>

**Comment by Steveice10** [comment]
Probably either a mistake or it was like that during the 1.8 snapshot documentation and was later fixed.
