### ISSUE TITLE
Cast issue for custom session services

### ISSUE THREAD

**Issue by ghost** [GeyserMC/MCProtocolLib#670]
java.lang.ClassCastException: class com.test.util.CustomSessionService cannot be cast to class com.github.steveice10.mc.auth.service.SessionService (com.test.util.CustomSessionService and com.github.steveice10.mc.auth.service.SessionService are in unnamed module of loader 'server.jar' @47c68ba2)
[17:14:33 WARN]:        at server.jar//com.github.steveice10.mc.protocol.ClientListener.packetReceived(ClientListener.java:68)
[17:14:33 WARN]:        at server.jar//com.github.steveice10.packetlib.event.session.PacketReceivedEvent.call(PacketReceivedEvent.java:51)
[17:14:33 WARN]:        at server.jar//com.github.steveice10.packetlib.tcp.TcpSession.callEvent(TcpSession.java:149)
[17:14:33 WARN]:        at server.jar//com.github.steveice10.packetlib.tcp.TcpSession.channelRead0(TcpSession.java:361)
[17:14:33 WARN]:        at server.jar//com.github.steveice10.packetlib.tcp.TcpSession.channelRead0(TcpSession.java:36)
[17:14:33 WARN]:        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
[17:14:33 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[17:14:33 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)

**Comment by Konicai** [comment]
Hi, it looks like `com.test.util.CustomSessionService` is your own class, which we have no idea of knowing what it contains. Please provide more information regarding what code you're actually running, and longer logs using https://mclo.gs/

**Comment by ghost** [comment]
> Hi, it looks like `com.test.util.CustomSessionService` is your own class, which we have no idea of knowing what it contains. Please provide more information regarding what code you're actually running, and longer logs using https://mclo.gs/

Custom session service is identical to sessionservice except the default_base_url is changed to a different service. The problem here is that clientlistener blindly casts the service to sessionservice despite custom services being supported.

**Comment by NathanKassab** [comment]
> > Hi, it looks like `com.test.util.CustomSessionService` is your own class, which we have no idea of knowing what it contains. Please provide more information regarding what code you're actually running, and longer logs using https://mclo.gs/
> 
> Custom session service is identical to sessionservice except the default_base_url is changed to a different service. The problem here is that clientlistener blindly casts the service to sessionservice despite custom services being supported.

This doesn't help anyone, please include a pastebin of the class in question. We cannot debug your code if we don't have access to it

**Comment by ghost** [comment]
> > > Hi, it looks like `com.test.util.CustomSessionService` is your own class, which we have no idea of knowing what it contains. Please provide more information regarding what code you're actually running, and longer logs using https://mclo.gs/
> > 
> > 
> > Custom session service is identical to sessionservice except the default_base_url is changed to a different service. The problem here is that clientlistener blindly casts the service to sessionservice despite custom services being supported.
> 
> This doesn't help anyone, please include a pastebin of the class in question. We cannot debug your code if we don't have access to it

I will comply but like i said before its nothing to do with my class (https://pastebin.com/5j1QD3Eg), its a problem with com.github.steveice10.mc.protocol.Clientlistener.java line 68.

**Comment by Redned235** [comment]
> > > > Hi, it looks like `com.test.util.CustomSessionService` is your own class, which we have no idea of knowing what it contains. Please provide more information regarding what code you're actually running, and longer logs using https://mclo.gs/
> > > 
> > > 
> > > Custom session service is identical to sessionservice except the default_base_url is changed to a different service. The problem here is that clientlistener blindly casts the service to sessionservice despite custom services being supported.
> > 
> > 
> > This doesn't help anyone, please include a pastebin of the class in question. We cannot debug your code if we don't have access to it
> 
> I will comply but like i said before its nothing to do with my class (https://pastebin.com/5j1QD3Eg), its a problem with com.github.steveice10.mc.protocol.Clientlistener.java line 68.

Your class needs to extend SessionService, not Service. It is not blindly being casted; a SessionService object is needed here for the authentication flow to complete.
