### ISSUE TITLE
Disconnect event reason is a string but its textcomponent

### ISSUE THREAD

**Issue by ghost** [GeyserMC/MCProtocolLib#671]
@Override
        public void disconnected(DisconnectedEvent event) {
            System.out.print("Disconnected: " + event.getReason());
            
event.getReason() returns a string but the above code prints this: `Disconnected: TextComponentImpl{content="", style=StyleImpl{color=null, obfuscated=not_set, bold=not_set, strikethrough=not_set, underlined=not_set, italic=not_set, clickEvent=null, hoverEvent=null, insertion=null, font=null}, children=[TextComponentImpl{content="Please...`

This event should return a textcomponent from event.getReason or turn the component into legacy string form before putting it into the event.

**Comment by Camotoy** [comment]
Confirmed from Geyser.

**Comment by Camotoy** [comment]
This should now be addressed by making the disconnect events take in a Component.
