### ISSUE TITLE
DataPalette has an int field 'globalPaletteBits' which is not used

### ISSUE THREAD

**Issue by MatteCarra** [GeyserMC/MCProtocolLib#676]
I was checking the ChunkSection.read method and I noticed it required a globalBiomePaletteBits.
I was not sure what it was and after inspecting the source I noticed that it was used to create a new DataPalette.
The problem is that it is not used there:
https://github.com/GeyserMC/MCProtocolLib/blob/acddfeeb51419abf06845a6fcd4fed14cacc4642/src/main/java/com/github/steveice10/mc/protocol/data/game/chunk/DataPalette.java#L21

Am I missing something?

**Comment by Camotoy** [comment]
*Seems* like you're correct that it is unnecessary, yes.

**Comment by onebeastchris** [comment]
Closing - this was resolved in the linked PR's.
