### ISSUE TITLE
ClientboundBlockDestructionPacket produces an error

### ISSUE THREAD

**Issue by Snowbelldog** [GeyserMC/MCProtocolLib#679]
Minecraft Wiki says the Destroy Stage can only be set from 0 to 9 but in the code is:
`if (stage >= 0 && stage <= 10)`
to fix change the 10 to 9

**Comment by Camotoy** [comment]
This was fixed: https://github.com/GeyserMC/MCProtocolLib/commit/69709912feb78f345e2c25dd2f9d9e6dfdc4e85f

Thanks anyway!
