### ISSUE TITLE
NoClassDefFoundError

### ISSUE THREAD

**Issue by JamieSinn** [GeyserMC/MCProtocolLib#68]
C:\Users\Jamie\Desktop>java -jar lotto.jar
Exception in thread "main" java.lang.NoClassDefFoundError: org/spacehq/packetlib
/SessionFactory
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
        at java.lang.Class.getMethod0(Unknown Source)
        at java.lang.Class.getMethod(Unknown Source)
        at sun.launcher.LauncherHelper.getMainMethod(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)
Caused by: java.lang.ClassNotFoundException: org.spacehq.packetlib.SessionFactor
y
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 6 more

Used the exact base example code, changing the relative things.
I built the jar and attached it to eclipse's project.

Maven gives the same error.

**Comment by Steveice10** [comment]
You don't have PacketLib included in the library jar. Building the library with maven should do it for you.

**Comment by JamieSinn** [comment]
C:\Users\Jamie\Documents\GitHub\ChatLoggingBot>mvn clean install
[INFO] Scanning for projects...
[WARNING]
[WARNING] Some problems were encountered while building the effective model for
com.sinndevelopment:chatloggingbot:jar:1.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-comp
iler-plugin is missing. @ line 19, column 21
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten t
he stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support buildin
g such malformed projects.
[WARNING]
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building chatloggingbot 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
Downloading: http://repo.spacehq.org/org/spacehq/mcprotocollib/1.8-SNAPSHOT/mcpr
otocollib-1.8-20140902.231145-1.pom
[WARNING] The POM for org.spacehq:mcprotocollib:jar:1.8-20140902.231145-1 is mis
sing, no dependency information available
Downloading: http://repo.spacehq.org/org/spacehq/mcprotocollib/1.8-SNAPSHOT/mcpr
otocollib-1.8-20140902.231145-1.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.373 s
[INFO] Finished at: 2015-01-23T10:46:42-05:00
[INFO] Final Memory: 6M/122M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project chatloggingbot: Could not resolve depe
ndencies for project com.sinndevelopment:chatloggingbot:jar:1.0-SNAPSHOT: Could
not find artifact org.spacehq:mcprotocollib:jar:1.8-20140902.231145-1 in spacehq
-repo (http://repo.spacehq.org/) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyReso
lutionException
C:\Users\Jamie\Documents\GitHub\ChatLoggingBot>

No dice

**Comment by JamieSinn** [comment]
And the jar I used was from a maven build of the repo.

**Comment by JamieSinn** [comment]
C:\Users\Jamie\Development\SinnDevBotMC>mvn clean install
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building SinnDevBot 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ SinnDevBot ---
[INFO] Deleting C:\Users\Jamie\Development\SinnDevBotMC\target
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ SinnDevBot

---

[WARNING] Using platform encoding (Cp1252 actually) to copy filtered resources,
i.e. build is platform dependent!
[INFO] Copying 0 resource
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ SinnDevBot ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding Cp1252, i.e. b
uild is platform dependent!
[INFO] Compiling 4 source files to C:\Users\Jamie\Development\SinnDevBotMC\targe
t\classes
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ Si
nnDevBot ---
[WARNING] Using platform encoding (Cp1252 actually) to copy filtered resources,
i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory C:\Users\Jamie\Development\SinnDevBot
MC\src\test\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ SinnDev
Bot ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ SinnDevBot ---
[INFO] No tests to run.
[INFO]
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ SinnDevBot ---
[INFO] Building jar: C:\Users\Jamie\Development\SinnDevBotMC\target\SinnDevBot-1
.0-SNAPSHOT.jar
[INFO]
[INFO] --- maven-install-plugin:2.4:install (default-install) @ SinnDevBot ---
[INFO] Installing C:\Users\Jamie\Development\SinnDevBotMC\target\SinnDevBot-1.0-
SNAPSHOT.jar to C:\Users\Jamie.m2\repository\com\sinndevelopment\sinndevbot\Sin
nDevBot\1.0-SNAPSHOT\SinnDevBot-1.0-SNAPSHOT.jar
[INFO] Installing C:\Users\Jamie\Development\SinnDevBotMC\pom.xml to C:\Users\Ja
mie.m2\repository\com\sinndevelopment\sinndevbot\SinnDevBot\1.0-SNAPSHOT\SinnDe
vBot-1.0-SNAPSHOT.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.253 s
[INFO] Finished at: 2015-01-23T10:52:08-05:00
[INFO] Final Memory: 14M/154M
[INFO] ------------------------------------------------------------------------
C:\Users\Jamie\Development\SinnDevBotMC>cd target

C:\Users\Jamie\Development\SinnDevBotMC\target>java -jar SinnDevBot-1.0-SNAPSHOT
.jar
Exception in thread "main" java.lang.NoClassDefFoundError: org/spacehq/packetlib
/packet/PacketProtocol
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
        at java.lang.Class.getMethod0(Unknown Source)
        at java.lang.Class.getMethod(Unknown Source)
        at sun.launcher.LauncherHelper.getMainMethod(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)
Caused by: java.lang.ClassNotFoundException: org.spacehq.packetlib.packet.Packet
Protocol
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 6 more

C:\Users\Jamie\Development\SinnDevBotMC\target>
