### ISSUE TITLE
there is such error: 

### ISSUE THREAD

**Issue by sebastianjnuwu** [GeyserMC/MCProtocolLib#692]
```
com.github.steveice10.mc.protocol.data.game.entity.metadata.BooleanMetadataType@603c1802 but we expected
```

Ah this error on my server it started to appear on the console and then the server just turned off coming search I got here! Can anyone explain to me the reason for this error and solution?

**Comment by Camotoy** [comment]
This is a Geyser error, and it's a result of plugins manually sending invalid entity metadata.

**Comment by sebastianjnuwu** [comment]
ok how to solve?
