### ISSUE TITLE
Chunk Loading with Schematics

### ISSUE THREAD

**Issue by Snowbelldog** [GeyserMC/MCProtocolLib#694]
i would load schematic as chunks but how can i get the ids. As far as i know has schematics a map with all block names (minecraft:stone), but a Chunk Section uses state ids that i can't find. Why use Minecraft a map that connect numbers to numbers? Do I understand something wrong?

Thanks for answer beforehand

Snowbelldog

**Comment by Redned235** [comment]
MCProtocolLib does not store mappings for block state -> runtime id. We do however have a json file for that we use in Geyser over at https://github.com/GeyserMC/mappings in `blocks.json`. These are ordered by their network id.

**Comment by Snowbelldog** [comment]
Thank you for the fast answer
