### ISSUE TITLE
How to track a players position?

### ISSUE THREAD

**Issue by DaanB1** [GeyserMC/MCProtocolLib#696]
I am trying to make a bot that keeps looking at a player, but I'm unable to properly find the coordinates of that player.
When a player enters renderdistance, I store its location using ClientboundAddPlayerPacket.
Then, when the player moves, I update the location using ClientboundMoveEntityPosPacket.

ClientboundMoveEntityPosPacket does not contain the coordinates of the entity, but rather the difference in coordinates compared to its previous location. The problem is that over time, small inaccuracies add up and eventually the bot has a completely different internal location of the player compared to its real location.

Is there a better way to approach this? Thank you for your time.

**Comment by Camotoy** [comment]
You should also listen to `ClientboundMoveEntityPosRotPacket`. `ClientboundTeleportEntityPacket` contains absolute numbers of an entity's position.
