### ISSUE TITLE
https://repo.opencollab.dev/maven-snapshots/com/nukkitx/ does not contain math nor fastutil

### ISSUE THREAD

**Issue by ogidevs** [GeyserMC/MCProtocolLib#704]
As the title says.

Is this meant to be?

My problem is, when trying to build dependencies with gradle using https://repo.opencollab.dev/maven-snapshots/ (1.19.2-SNAPSHOT) I get this error:
Could not HEAD 'https://repo.opencollab.dev/maven-snapshots/com/nukkitx/math/1.1.1/math-1.1.1.pom'. Received status code 409 from server: Conflict
Disable Gradle 'offline mode' and sync project

**Comment by Konicai** [comment]
https://repo.opencollab.dev/maven-releases contains math and fastutil.

You might be interested in using https://repo.opencollab.dev/main which combines both `maven-releases` and `maven-snapshots`
