### ISSUE TITLE
Processing chunks, physics bots on 1.12.2

### ISSUE THREAD

**Issue by itskekoff** [GeyserMC/MCProtocolLib#708]
Hi, I'm making bots on minecraft 1.12.2, I ran into a problem, I do not know how to get chunks, save chunks, determine where the player is, in which chunk the player is and how to add the physics of falling, movement. Can someone help me with this problem? It is advisable to send me the code.

**Comment by JustNanix** [comment]
Hey, you. Yes, you.

Close your eyes and take a few long, deep breaths. Feel your breath entering and leaving your body. Feel your feet connecting to the ground. Focus on those feelings. 

Now imagine you’re floating amongst the clouds. If thoughts come to you, let them drift past, like clouds. Do you feel a little bit better? Calmer? 

Carving out time — even just a few minutes — to clear your mind is important for your mental health. It’ll also help you focus and be more effective. With a clear mind, you can work more efficiently on what needs doing.

**Comment by itskekoff** [comment]
> Hey, you. Yes, you.
> 
> Close your eyes and take a few long, deep breaths. Feel your breath entering and leaving your body. Feel your feet connecting to the ground. Focus on those feelings.
> 
> Now imagine you’re floating amongst the clouds. If thoughts come to you, let them drift past, like clouds. Do you feel a little bit better? Calmer?
> 
> Carving out time — even just a few minutes — to clear your mind is important for your mental health. It’ll also help you focus and be more effective. With a clear mind, you can work more efficiently on what needs doing.

Thanks, I jumped off the roof. Can you seriously answer?

**Comment by Konicai** [comment]
MCProtocolLib is much more of a barebones protocol/packet library than a bot framework. You'll need to keep track of chunks, your player's position, etc yourself. As well as performing client side physics (eg controlling temptable entities) yourself. 

Getting chunks from the server is contained here: https://github.com/GeyserMC/MCProtocolLib/tree/master/src/main/java/com/github/steveice10/mc/protocol/packet/ingame/clientbound/level,
but the chunk/block data is presented in a pretty low-level format (Byte storage, NBT, ...).

If you're looking to create bots I would highly suggest looking into Mineflayer or similar projects
