### ISSUE TITLE
How do you even start to set this up? 

### ISSUE THREAD

**Issue by Niko454** [GeyserMC/MCProtocolLib#71]
Sorry for being a noob but I don't even know where to start within eclipse. When I import the project all the scripts give errors, and when I try to run test.java within eclipse it doesn't appear to be working either.  Am I doing something wrong? How would I make this work? Thanks in advance.

**Comment by Steveice10** [comment]
If you're trying to open MCProtocolLib in Eclipse, you'll need to make sure that you have the dependencies and what not set up in your work space. If I recall correctly, Eclipse has an option for importing Maven projects, so you could probably do that and point it to MCProtocolLib's pom.xml.

**Comment by Niko454** [comment]
New error: netty-buffer-5.0.0.Alpha1-SNAPSHOT.4a680a3 (repository: dirty)
netty-codec-5.0.0.Alpha1-SNAPSHOT.4a680a3 (repository: dirty)
netty-codec-http-5.0.0.Alpha1-SNAPSHOT.4a680a3 (repository: dirty)
netty-codec-memcache-5.0.0.Alpha1-SNAPSHOT.4a680a3 (repository: dirty)
netty-codec-socks-5.0.0.Alpha1-SNAPSHOT.4a680a3 (repository: dirty)
netty-common-5.0.0.Alpha1-SNAPSHOT.4a680a3 (repository: dirty)
netty-handler-5.0.0.Alpha1-SNAPSHOT.4a680a3 (repository: dirty)
netty-transport-5.0.0.Alpha1-SNAPSHOT.4a680a3 (repository: dirty)
netty-transport-rxtx-5.0.0.Alpha1-SNAPSHOT.4a680a3 (repository: dirty)
netty-transport-sctp-5.0.0.Alpha1-SNAPSHOT.4a680a3 (repository: dirty)
netty-transport-udt-5.0.0.Alpha1-SNAPSHOT.4a680a3 (repository: dirty)

Wont run?

**Comment by Niko454** [comment]
Cant seem to find it. If you could add me on skype @ the_original_niko it would help with communication. Once again id like to thank you

**Comment by Niko454** [comment]
Aight well theres progress. Everything seems working except the srv/main the error on run is: Editor does not contain a main type?

**Comment by Lukario45** [comment]
I will suggest that you use IntelliJ IDEA or Netbeans as they work best with Maven projects, The example is really useful if you know how to read it ;) also you can look at my MCThunder project if you are doing server side
