### ISSUE TITLE
ProjectileData not created for EntityType.ENDER_PEARL in ClientboundAddEntityPacket

### ISSUE THREAD

**Issue by 112batman** [GeyserMC/MCProtocolLib#716]
Tittle, should be easily fixable just by adding `EntityType.ENDER_PEARL` to the list on line 73/74

**Comment by onebeastchris** [comment]
Fixed in https://github.com/GeyserMC/MCProtocolLib/commit/53f1441f295180831d678f0f0330d65ece2f2fab - thanks for reporting.
