### ISSUE TITLE
Unable to properly open minecraft server and login

### ISSUE THREAD

**Issue by JSP1408** [GeyserMC/MCProtocolLib#719]
`
    public Server() {
        SessionService sessionService = new SessionService();
        sessionService.setProxy(AUTH_PROXY);

        TcpServer server = new TcpServer(HOST, PORT, MinecraftProtocol::new);

        server.setGlobalFlag(MinecraftConstants.SESSION_SERVICE_KEY, sessionService);
        server.setGlobalFlag(MinecraftConstants.VERIFY_USERS_KEY, VERIFY_USERS);
        server.setGlobalFlag(MinecraftConstants.SERVER_INFO_BUILDER_KEY, (ServerInfoBuilder) session ->
                new ServerStatusInfo(
                        new VersionInfo(MinecraftCodec.CODEC.getMinecraftVersion(), MinecraftCodec.CODEC.getProtocolVersion()),
                        new PlayerInfo(100, 0, new GameProfile[0]),
                        Component.text("Hello world!"),
                        null,
                        false
                )
        );

        server.setGlobalFlag(MinecraftConstants.SERVER_LOGIN_HANDLER_KEY, (ServerLoginHandler) session ->
                session.send(new ClientboundLoginPacket(
                        0,
                        false,
                        GameMode.SURVIVAL,
                        GameMode.SURVIVAL,
                        1,
                        new String[]{"minecraft:world"},
                        new CompoundTag("codec"),
                        "minecraft:overworld",
                        "minecraft:world",
                        100,
                        0,
                        16,
                        16,
                        false,
                        false,
                        false,
                        false,
                        null
                ))
        );

        server.setGlobalFlag(MinecraftConstants.SERVER_COMPRESSION_THRESHOLD, 100);

        server.bind();
    }

    @SuppressWarnings("ConstantConditions")
    private CompoundTag loadNetworkCodec() {
        try (InputStream inputStream = ClassLoader.getSystemClassLoader().getResourceAsStream("network_codec.nbt");
             DataInputStream stream = new DataInputStream(new GZIPInputStream(inputStream))) {
            return (CompoundTag) NBTIO.readTag((DataInput) stream);
        } catch (IOException e) {
            e.printStackTrace();
            throw new AssertionError("Unable to load network codec.");
        }
![javaw_VO36l9T4RR](https://user-images.githubusercontent.com/94943333/208493405-1f219bca-084c-4319-9995-af583f7e4687.png)

    }
`

I have this code right here, it should in theory let me create a minecraft server. I followed the instructions to create a server from the example directly however no matter what I change you can not log in. The image attached is the error you get.

**Comment by Konicai** [comment]
`new CompoundTag("codec")` doesn't call `loadNetworkCodec()`. But the error also looks like a real but invalid codec was sent. I'm not sure though, I could be wrong.

The example loads the network codec when the login packet is created, but really it should only be loaded once and cached. Also there is a Discord linked in the README of this project that you can join for help as well

**Comment by JSP1408** [comment]
I forgot to mention where I say "new CompoundTag("codec")" I'm aware that's wrong  and I forgot to revert that before sending the code but the error in the image I sent is for when I ran the code with loadNetworkCodec()

**Comment by FerusGrim** [comment]
Bit late, but the network codec from [the test package](https://github.com/GeyserMC/MCProtocolLib/blob/master/src/test/resources/networkCodec.nbt) works fine.
