### ISSUE TITLE
No tcp.TcpSessionFactory ?

### ISSUE THREAD

**Issue by justuser-31** [GeyserMC/MCProtocolLib#720]
`import com.github.steveice10.packetlib.tcp.TcpSessionFactory;`

Output:
`
gradle shadowJar && gradle build

> Task :compileJava FAILED
/home/void/Desktop/AMCBOT/MinecraftBOT/src/main/java/re/alwyn974/minecraft/bot/MinecraftBOT.java:40: error: cannot find symbol
import com.github.steveice10.packetlib.tcp.TcpSessionFactory;
                                          ^
`

Other works like `com.github.steveice10.mc.auth.data.GameProfile` and other
How to configure socks5/socks4 proxy then?

**Comment by Camotoy** [comment]
That class no longer exists. You're likely using an outdated PacketLib dependency.
