### ISSUE TITLE
Where is documentation?

### ISSUE THREAD

**Issue by justuser-31** [GeyserMC/MCProtocolLib#722]
Really, I don't see any documentation, only java code example.
Then how to known then how work with methods?

**Comment by HumanDuck23** [comment]
Same here, trying to work with this library but I have absolutely no clue how it works. At least a little bit of docs would be appreciated

**Comment by cxzlw** [comment]
Same.

**Comment by AlexProgrammerDE** [comment]
Javadocs can be found in the README now: https://github.com/GeyserMC/MCProtocolLib#javadocs

**Comment by onebeastchris** [comment]
Forgot to close - See the example (https://github.com/GeyserMC/MCProtocolLib/tree/master/example) and the javadocs for help. For other questions, please join the GeyserMC discord, and ask in the #mcprotocollib channel!
