### ISSUE TITLE
Pinging servers from lower versions or with ViaVersions causes a NullPointerException

### ISSUE THREAD

**Issue by geza3D** [GeyserMC/MCProtocolLib#726]
### The cause

This issue is caused by the fact that servers below 1.19.1 send the [ClientboundStatusResponsePacket](https://github.com/GeyserMC/MCProtocolLib/blob/master/src/main/java/com/github/steveice10/mc/protocol/packet/status/clientbound/ClientboundStatusResponsePacket.java#L56) without the *enforcesSecureChat* boolean field (previously also known as the *previewsChat* boolean field). Since this field is non-existent in lower versions, trying to do a **STATUS** connection to a server from these versions will fail, and throw a NullPointerException.

### The fix
Check if the field is null, and if it is, then default to false.

**Comment by onebeastchris** [comment]
We forgot to close this - it was fixed in https://github.com/GeyserMC/MCProtocolLib/commit/060a4ee6df05ca5b2a07e74193a9df386081e2f7. Thanks for reporting!
