### ISSUE TITLE
No Class Def Found Error: /org/spacehq/packetlib/packet/PacketProtocol

### ISSUE THREAD

**Issue by JamieSinn** [GeyserMC/MCProtocolLib#73]
# Build Logs and Error

C:\Users\Jamie\Documents\GitHub\LotteryBot\LotteryBot>mvn clean install
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building lotterybot 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ lotterybot ---
[INFO] Deleting C:\Users\Jamie\Documents\GitHub\LotteryBot\LotteryBot\target
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ lotterybot

---

[WARNING] Using platform encoding (Cp1252 actually) to copy filtered resources,
i.e. build is platform dependent!
[INFO] Copying 0 resource
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ lotterybot ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding Cp1252, i.e. b
uild is platform dependent!
[INFO] Compiling 2 source files to C:\Users\Jamie\Documents\GitHub\LotteryBot\Lo
tteryBot\target\classes
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ lo
tterybot ---
[WARNING] Using platform encoding (Cp1252 actually) to copy filtered resources,
i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory C:\Users\Jamie\Documents\GitHub\Lotte
ryBot\LotteryBot\src\test\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ lottery
bot ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ lotterybot ---
[INFO] No tests to run.
[INFO]
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ lotterybot ---
[INFO] Building jar: C:\Users\Jamie\Documents\GitHub\LotteryBot\LotteryBot\targe
t\lotterybot-1.0-SNAPSHOT.jar
[INFO]
[INFO] --- maven-install-plugin:2.4:install (default-install) @ lotterybot ---
[INFO] Installing C:\Users\Jamie\Documents\GitHub\LotteryBot\LotteryBot\target\l
otterybot-1.0-SNAPSHOT.jar to C:\Users\Jamie.m2\repository\ca\jamiesinn\lottery
bot\1.0-SNAPSHOT\lotterybot-1.0-SNAPSHOT.jar
[INFO] Installing C:\Users\Jamie\Documents\GitHub\LotteryBot\LotteryBot\pom.xml
to C:\Users\Jamie.m2\repository\ca\jamiesinn\lotterybot\1.0-SNAPSHOT\lotterybot
-1.0-SNAPSHOT.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.796 s
[INFO] Finished at: 2015-02-20T16:01:55-05:00
[INFO] Final Memory: 14M/154M
[INFO] ------------------------------------------------------------------------
C:\Users\Jamie\Documents\GitHub\LotteryBot\LotteryBot>cd target

C:\Users\Jamie\Documents\GitHub\LotteryBot\LotteryBot\target>java -jar lotterybo
t-1.0-SNAPSHOT.jar
Exception in thread "main" java.lang.NoClassDefFoundError: org/spacehq/packetlib
/packet/PacketProtocol
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
        at java.lang.Class.getMethod0(Unknown Source)
        at java.lang.Class.getMethod(Unknown Source)
        at sun.launcher.LauncherHelper.getMainMethod(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)
Caused by: java.lang.ClassNotFoundException: org.spacehq.packetlib.packet.Packet
Protocol
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 6 more

C:\Users\Jamie\Documents\GitHub\LotteryBot\LotteryBot\target>
## Building with Maven, using the exact sample code from the example.
# Pom File:

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

```
<groupId>ca.jamiesinn</groupId>
<artifactId>lotterybot</artifactId>
<version>1.0-SNAPSHOT</version>
<repositories>
    <repository>
        <id>spacehq-repo</id>
        <url>http://repo.spacehq.org/</url>
    </repository>
</repositories>
<build>
    <plugins>
        <plugin>
            <!-- Build an executable JAR -->
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-jar-plugin</artifactId>
            <version>2.4</version>
            <configuration>
                <archive>
                    <manifest>
                        <addClasspath>true</addClasspath>
                        <classpathPrefix>lib/</classpathPrefix>
                        <mainClass>ca.jamiesinn.lotterybot.LotteryBot</mainClass>
                    </manifest>
                </archive>
            </configuration>
        </plugin>
    </plugins>
</build>
<dependencies>
    <dependency>
        <groupId>org.spacehq</groupId>
        <artifactId>mcprotocollib</artifactId>
        <version>1.8-SNAPSHOT</version>
    </dependency>
</dependencies>
```

</project>

**Comment by Johni0702** [comment]
If you create a standalone jar file, you have to include your dependencies in the generated file.

When using maven, you can simply use the shade plugin to do that.
Have a look [here](https://github.com/Steveice10/MCProtocolLib/blob/1.8/pom.xml#L101) for an example on how to use it.

**Comment by Steveice10** [comment]
Exactly that.
