### ISSUE TITLE
Sending a chat packet kicks the bot from the server

### ISSUE THREAD

**Issue by Blackilykat** [GeyserMC/MCProtocolLib#732]
Using 1.19.4-snapshot
Basically, when I try to run client.send(new ServerboundChatPacket(..)) it just kicks the bot
Here's the code:
```
Main.client.send(new ServerboundChatPacket("test", Instant.now().toEpochMilli(), 0, null, 0, new BitSet()));
```
There's no stacktrace to send since there's no exception thrown

**Comment by Redned235** [comment]
You need to use the Clientbound packet as clients are only capable of receiving those. The serverbound packets are used for packets the client sends to the server.
