### ISSUE TITLE
Bug in Serialization of ClientboundCommandsPacket

### ISSUE THREAD

**Issue by artnaseef** [GeyserMC/MCProtocolLib#742]
I found a bug in ClientbountCommandsPacket serialization.  A pull request has been created: https://github.com/GeyserMC/MCProtocolLib/pull/741

It's a simple fix, however, I can give more information if needed.

I believe this was introduced in 1.19.4-1

**Comment by artnaseef** [comment]
Is there anything more I can do here to help in getting this resolved?  I believe it is a quick merge, but am happy to assist if more effort is needed.

**Comment by onebeastchris** [comment]
Closing this issue as the associated PR has been merged :p
