### ISSUE TITLE
ClientboundContainerSetSlotPacket setting nbt on a ItemStack object results in an Internal Exception by the client (1.19.1)

### ISSUE THREAD

**Issue by EpicBirb** [GeyserMC/MCProtocolLib#746]
![image](https://github.com/GeyserMC/MCProtocolLib/assets/68750348/ec795b26-b222-43f4-97a5-e8d31fb2517c)
![image](https://github.com/GeyserMC/MCProtocolLib/assets/68750348/958efbdb-a816-43f3-80eb-3fb80368b685)

**Comment by Camotoy** [comment]
We won't be fixing bugs for older MCProtocolLib versions. Sorry. :(
