### ISSUE TITLE
ClientboundContainerSetSlotPacket setting nbt on an ItemStack object results in an Internal Exception by the client (1.20.1 latest)

### ISSUE THREAD

**Issue by EpicBirb** [GeyserMC/MCProtocolLib#747]
repeat of #746 but for 1.20.1 (latest build from the repo)
![image](https://github.com/GeyserMC/MCProtocolLib/assets/68750348/149e8f20-0a01-4080-90ab-78d000f80a5c)
![image](https://github.com/GeyserMC/MCProtocolLib/assets/68750348/9465e567-e449-4f77-b8c9-e345bbb91586)

removing the nbt from the packet results in the client saying "Joining world"

**Comment by EpicBirb** [comment]
also when can we get a documentation for the library?

**Comment by Konicai** [comment]
What kind of documentation are you referring to? Packets and network data are almost certainly better covered by [wiki.vg](https://wiki.vg).
If javadocs are lacking then I understand.

**Comment by EpicBirb** [comment]
javadocs

**Comment by AlexProgrammerDE** [comment]
Javadocs can be found in the README now: https://github.com/GeyserMC/MCProtocolLib#javadocs

**Comment by onebeastchris** [comment]
ItemStacks don't use NBT anymore; and given that MCPL only supports fixes for latest versions, i'll close this. Thanks anyways!
