### ISSUE TITLE
Please release 1.20.4-2 ASAP

### ISSUE THREAD

**Issue by marlester-dev** [GeyserMC/MCProtocolLib#794]
The problem is that 1.20.4-1 has a snapshot version of kyori adventure and 1.20.4-2-SNAPSHOT is a snapshot itself. Snapshots mess up with my code and stability.

**Comment by AlexProgrammerDE** [comment]
Kyori adventure was already bumped to release: https://github.com/GeyserMC/MCProtocolLib/blob/eacfb2d03729ffcc6b7328d911fddca748a0c340/gradle/libs.versions.toml#L8
There will likely be a proper release with 1.20.6 support.

**Comment by onebeastchris** [comment]
Closing as completed with https://repo.opencollab.dev/#/maven-snapshots/org/geysermc/mcprotocollib/protocol/1.20.6-2-SNAPSHOT - thanks for reporting.
