### ISSUE TITLE
Multi version support

### ISSUE THREAD

**Issue by JFKingsley** [GeyserMC/MCProtocolLib#8]
Is there any chance of seeing multiple version support? 
Given the amount of code per packet I don't see why it should be too hard to somehow add support for multiple versions. Maybe even use some kind of plugin system to have versions as modules. 
It would be very useful for people trying to build bots and things that have support for multiple versions without having to checkout versions that had support but not the latest bug fixes.
Just a thought, Thanks,
Jonathan

**Comment by jesusthekiller** [comment]
Great idea, I would love it too! :D

**Comment by JFKingsley** [comment]
I have a couple ideas for doing it, will fork and see what I can do.

**Comment by JFKingsley** [comment]
I've got a fair bit of free time now, so if you ever do decide to run a rewrite you can count on me to push a fair chunk
