### ISSUE TITLE
Changing Protocol Version

### ISSUE THREAD

**Issue by stenocyb** [GeyserMC/MCProtocolLib#81]
Hello, I can't figure out how to change the protocol version, for example switch from 1.8 to 1.7.2 protocol version. If this hasn't been already added, it would be a nice feature and it would make your library even better!

Greetings, xTACTIXzZ

**Comment by phase** [comment]
There's already code for it in https://github.com/Steveice10/MCProtocolLib/tree/1.7.4

**Comment by Steveice10** [comment]
This isn't really feasible to do in a single library jar without a lot of pain and code duplication. You'll have to use a build from the 1.7.4 branch as previously mentioned.
