### ISSUE TITLE
Build of realese 1.20.6-1 was failed

### ISSUE THREAD

**Issue by Freyhold** [GeyserMC/MCProtocolLib#830]
Please re run, and put artifact on jitpack 
BUILD FAILED in 35s
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
Archive: :buildSrc:unspecified
Archive: org.geysermc.mcprotocollib:protocol:1.20.6-1
Archive: org.geysermc.mcprotocollib:example:unspecified
Publication: org.geysermc.mcprotocollib:protocol:1.20.6-1
Build tool exit code: 0
Looking for artifacts...
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
Looking for pom.xml in build directory and ~/.m2
Found artifact: org.geysermc.mcprotocollib:protocol:1.20.6-1
Found artifact: :buildSrc:unspecified
Found artifact: org.geysermc.mcprotocollib:example:unspecified
Found artifact: org.geysermc.mcprotocollib:protocol:1.20.6-1
2024-05-14T04:02:48.915103104Z
Exit code: 0

⚠️ ERROR: No build artifacts found
Expected artifacts in: $HOME/.m2/repository/buildSrc/unspecified

**Comment by Kas-tle** [comment]
Is there a reason you cannot use the opencollab maven repo for this?
https://repo.opencollab.dev/#/maven-snapshots/org/geysermc/mcprotocollib/protocol/1.20.6-2-SNAPSHOT

**Comment by onebeastchris** [comment]
Closing due to no further response.
