### ISSUE TITLE
Render Component as HTML

### ISSUE THREAD

**Issue by aljesco1337** [GeyserMC/MCProtocolLib#850]
I can get server's description like this:

```
client.setFlag(MinecraftConstants.SERVER_INFO_HANDLER_KEY, (session, info) -> {
    log.info("Description: {}", info.getDescription());
});
```

but is it possible to render all the components from description as HTML, considering the text decorations and styles?

**Comment by Camotoy** [comment]
Are you trying to show it on the web specifically then?

**Comment by aljesco1337** [comment]
yes

**Comment by Camotoy** [comment]
This is probably outside the scope of our project and into the Adventure library.

There's bits and bobs here: https://github.com/KyoriPowered/adventure-webui/blob/main/src/jvmMain/kotlin/net/kyori/adventure/webui/jvm/minimessage/hook/StandardRenderHooks.kt 

See https://docs.advntr.dev/index.html# for their docs and a link to their Discord for further help. Good luck!
