### ISSUE TITLE
Cant load the dependency.

### ISSUE THREAD

**Issue by DrWine** [GeyserMC/MCProtocolLib#855]
I tried using the maven dependency, using your dependency and even downgrading. It didn't work.

![image](https://github.com/user-attachments/assets/865c653d-5787-4ac3-bde5-6719322c9c79)

**Comment by DrWine** [comment]
Changing the dependency artifact id to "opencollab" didn't work either.

**Comment by Konicai** [comment]
For some reason `1.20.6-1` wasn't published. Try `1.20.6-2-SNAPSHOT` if you want to use `1.20.6`.

Note that `https://repo.opencollab.dev/main/` will proxy both 
- `https://repo.opencollab.dev/maven-snapshots/`
- `https://repo.opencollab.dev/maven-releases/`

so it is recommended to just use `https://repo.opencollab.dev/main/`

**Comment by Konicai** [comment]
Have you been able to find the right artifact?

**Comment by onebeastchris** [comment]
Closing due to no further response. Please let us know if you still face issues!
