### ISSUE TITLE
Bot Movement

### ISSUE THREAD

**Issue by marshallwalker** [GeyserMC/MCProtocolLib#88]
Hello, I'm writing a bot and I need to get them to move, Here is my methods to move the bots,
http://pastie.org/private/xaub378udajxyrskti7dw#17

I'm calling the panic method here 'onPlayerPositionRotationPacket'
Could you help me?

**Comment by marshallwalker** [comment]
EDIT: changed double speed = playerY - 1.62; -> double speed = 0.1;
Dosen't fix movement though

**Comment by marshallwalker** [comment]
Bump?

**Comment by heke85** [comment]
https://github.com/Steveice10/MCProtocolLib/issues/161

**Comment by TheSnoozer** [comment]
Example I found (that's not written by me):
In order to move use the following:
https://github.com/WTXDev/Riptide-1.8/blob/master/src/com/wtx/riptide/Riptide.java#L78

``` java
            x += 0.215;
            conn.getSession().send(new ClientPlayerPositionPacket(onGround, x, y, z));
            try {
                Thread.sleep(50);
            } catch (InterruptedException e) {
                // TODO Auto-generated catch block
                e.printStackTrace();
            }
```

works fine 4 me and as outline in #161 you need to do the following:

```
I figured out the problem - when recieving a ServerPlayerPositionRotationPacket the server needs a ClientTeleportConfirmPacket with the same TeleportID as the server sent with the packet.
```

See:
https://github.com/WTXDev/Riptide-1.8/blob/master/src/com/wtx/riptide/Riptide.java#L353

or use:

``` java
} else if (event.getPacket() instanceof ServerConfirmTransactionPacket) {
                                        final ServerConfirmTransactionPacket p = event.getPacket();
                                        bot.getSession().send(new ClientConfirmTransactionPacket(p.getWindowId(),
                                                p.getActionId(), p.getAccepted()));

```
