### ISSUE TITLE
Moving a player?

### ISSUE THREAD

**Issue by Thallen** [GeyserMC/MCProtocolLib#90]
I cannot seem to be able to move the player. I have tried sending position packets with very small increments and a small delay, but no dice. Would you mind providing an example of simply moving the player across the x, or z axis?

**Comment by Steveice10** [comment]
Some info regarding player movement can be found here: https://github.com/Steveice10/MCProtocolLib/issues/32

**Comment by Thallen** [comment]
Thanks for the quick reply, but I have already seen both issues regarding it. It looks like the ClientPlayerPositionRotationPacket constructor has changed since then and I am not sure what the 'stance' is.

**Comment by Steveice10** [comment]
It doesn't exist anymore. It's probably safe to ignore.

**Comment by Thallen** [comment]
Alright, I got it working, but do you have any idea how to make it more natural looking instead all jumpy

**Comment by Steveice10** [comment]
Smooth out your movement, e.g. set a destination to walk to and do it gradually little by little.

**Comment by Thallen** [comment]
It works. The only thing left is implementing gravity. Right now I am replying to 'ServerPlayerPositionRotationPacket' packets. I have a for loop that adds 0.1 each time to the x position and sends a movement packet with a small delay afterwards. The constructor for the 'ClientPlayerPositionPacket' takes a boolean that represents whether the player is on the ground, or not. I am not sure how I can tell if the player is on the ground and whether I should decrement the y axis, or not.

**Comment by Steveice10** [comment]
For properly telling whether the player is on the ground, you could store block info from chunk packets and check if they're standing on a solid block. I don't recall if there's an easier way to do it or not, although if I remember correctly the server doesn't really mind if the on-ground value is incorrect, although it may cause some glitches with certain actions.
