### ISSUE TITLE
Misuse of @Override annotation

### ISSUE THREAD

**Issue by ShawnTuatara** [GeyserMC/MCProtocolLib#92]
I pulled down this project and my Eclipse is giving a number of errors on methods annotated with `@Override` that don't actually implement a method of the superclass or interface. This doesn't specifically cause an error in compilation but is misleading to new developers wanting to follow the code. Is there any reason for this or just a code style that this project uses?

**Comment by Steveice10** [comment]
Can you point out a specific location?

**Comment by devversion** [comment]
In Eclipse, by importing the Maven Project, there are a few errors by implementing the class Packet.

For example by:
- public void read(NetInput in)
- public void write(NetOutput out)
- public boolean isPriority()

These methods are marked with the @Override Annotation, but they only implementing an interface and not a class, so you have to remove the @Override Annotation.

**Comment by devversion** [comment]
I commited some changes to fix that little error :+1: 
Here is the Pull Request: 
- #95

**Comment by Steveice10** [comment]
Using @Override is perfectly valid for interface methods.

**Comment by devversion** [comment]
Yes I didn't say, that @Override is not valid. The Problem is, that the most Java Runtimes (for example JRE-5) complaining about that Annotation. So if this Project is an API, it should be usable for every Java Runtime.

But I have to say, you did awesome work with yout Headless Client ir Server. Just using now a higher Runtime.

**Comment by devversion** [comment]
So the Solution for that Issue is @ShawnTuatara, changing the Java Runtime to a higher Version. Since JRE 6 its possible to use the @Override Annotation for Interface Methods

**Comment by Steveice10** [comment]
I do not plan on providing support for Java runtimes from 2004. There's no reason to be using Java 5 in 2015.

**Comment by devversion** [comment]
Sorry, but the most Eclipse Versions are compiling in Java 5 Level, so there are a few Errors, but its okay.

**Comment by Steveice10** [comment]
Eclipse let's you set the target version in the project options.

**Comment by devversion** [comment]
Yes, I realized that I'am using the JRE5, but now I changed it to Java 8. JRE5 thats the default Eclipse Runtime, so its good to inform @ShawnTuatara about this.
