### ISSUE TITLE
PlayerDeathPacket

### ISSUE THREAD

**Issue by phase** [GeyserMC/MCProtocolLib#97]
Is there a PlayerDeathPacket anywhere? I'm trying to respawn the player after he's died.

**Comment by Steveice10** [comment]
https://github.com/Steveice10/MCProtocolLib/blob/1.8/src/main/java/org/spacehq/mc/protocol/packet/ingame/server/ServerRespawnPacket.java

Please actually look before you open an issue about where a packet is. If you can't find the source file, you can look around [here](https://github.com/Steveice10/MCProtocolLib/blob/1.8/src/main/java/org/spacehq/mc/protocol/MinecraftProtocol.java#L197) to match packet IDs to their classes.
